### PR TITLE
Bugfix FXIOS-8389 [v126] Fixes duplicate FxA sessions

### PR DESCRIPTION
**Pull request by tarikeshaq**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-8389)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/18599)

## :bulb: Description
Passes on the LOGIN web channel message to the fxa component, setting the user's session token. Also stops requesting the session scope, when singing in using email and password

**NOTE**: This should not land until, the following is true.. to make sure of that, I'm keeping this a draft till then
- https://github.com/mozilla/application-services/pull/6111 is landed and
- FxA's Train 1.277.1 is in production for testing, I'll confirm here once that's true (should be on Feb 7th)

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [x] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [x] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Review by cyndichin — APPROVED** [review]
thanks @tarikeshaq! looks good to me, but also tagging @nbhasin2 for a second pair of eyes since its related to login

**Review by nbhasin2 — APPROVED** [review]

**Comment by nbhasin2** [comment]
Waiting for BR!

**Comment by nbhasin2** [comment]
The smoketest 2 always fails, one last try

**Comment by tarikeshaq** [comment]
Rebased then bitrise turned green!

**Pull request merged**
