### PR TITLE
Add FXIOS-6505 [v123] Show back forward list from browser coordinator

### PR DESCRIPTION
**Pull request by FilippoZazzeroni**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-6505)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/14599)

## :bulb: Description
I linked this pr to a closed issue, it's shouldn't be close, because the issue was split in two pr. 
Added show of `BackForwardListViewController` from `BrowserCoordinator`. 
All the modified unrelated files are there because i ran the swiftlint cli, if i should restore as previous state let me know, thank you.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [x] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by lmarceau** [comment]
Hello @FilippoZazzeroni, for the Swiftlint warnings, it's preferable to have them in another PR. I find it curious as I locally do not see those warnings. Maybe @adudenamedruby has some ideas as to what is happening here?

**Comment by FilippoZazzeroni** [comment]
Hi @lmarceau yes sure, i'm going to revert the swiftlints for this PR. I'm curios too to understand the reason, it's the first time that the linter corrects me this amount of warnings, i don't know, i didn't update or change anything related to swiftlint.

**Comment by FilippoZazzeroni** [comment]
Ok @lmarceau @adudenamedruby my bad, i was running swiftlint from the `firefox-ios/firefox-ios ` folder so the linter was not finding the `.swiftlint.yaml`. Now should be all good.

**Review by lmarceau — APPROVED** [review]

**Comment by adudenamedruby** [comment]
Wow, I wrote an answer and then I got pulled into a meeting and never finished it. Apologies.

**Comment by adudenamedruby** [comment]
Also, @FilippoZazzeroni, if you have swiftlint installed, Xcode should be running swiftlint each time you build now. I've fixed that issue. :)

**Comment by FilippoZazzeroni** [comment]
@adudenamedruby ok perfect thank you nice to hear that.

**Pull request merged**
