### PR TITLE
Bug 1410986 - Remove removeObserver in deinit when added in viewDidLoad and init

### PR DESCRIPTION
**Pull request by kusumotoa**

### CODE REVIEW

**Comment by kusumotoa** [comment]
Sorry "You are not authorized to access bug 1410974."....
What should I do?

**Comment by garvankeeley** [comment]
Not sure, I am trying to find out why that bug is marked as a security issue (and thus locked for viewing). In the meantime, I just noticed a merge conflict, can you resolve that and update the patch?

**Comment by kusumotoa** [comment]
Thank you very much. 🙇 
I can resolve conflicts!!

**Comment by kusumotoa** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1410986
↑↑↑
I can submit again.

**Comment by garvankeeley** [comment]
I updated the PR title for that new bug you filed.

**Comment by kusumotoa** [comment]
Thank you, you've been so helpful. ！！！！！ 🙇‍♀️

**Pull request merged**
