### PR TITLE
Bugfix FXIOS-10574 Protection panel tweaks Design QA

### PR DESCRIPTION
**Pull request by petruSt24**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-10574)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/23161)

## :bulb: Description

Updated the design of the protection panel based on the feedback from [design](https://www.figma.com/design/fYqZbJCyoO4IO0LxgSRWW8/Unified-Trust-Panel?node-id=10179-54811&node-type=frame&t=p8Zv94Rhe9Og1H6x-0)
## :pencil: Checklist
You have to check all boxes before merging
- [X] Filled in the above information (tickets numbers and description of your work)
- [X] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Review by MattLichtenstein — COMMENTED** [review]
I noticed a few outstanding UI discrepancies between the current implementation and the [spec](https://www.figma.com/design/fYqZbJCyoO4IO0LxgSRWW8/Unified-Trust-Panel?node-id=10178-1326&node-type=canvas&t=Gzkb3eSdI6Ds013g-0). Are these supposed to accounted for?

| Actual | Expected |
| ------------- | ------------- |
| Favicon background is a rounded rectangle | Favicon background should be circlular |
| The website title is bolded | The website title should not be bolded |
| Spacing + centering of text inside the box with the fox image is incorrect | Spacing between labels should be less, and content should be vertically centered |
| Privacy settings link has less leading margin | Privacy settings link should have equal leading margin as the "Clear cookies and site data" button above it |

**Comment by petruSt24** [comment]
Simulator Screenshot - iPhone 15 - 2024-11-21 at 21 00 32
@MattLichtenstein thank you for the suggestions, I replaced the stackView with a UIView to fix the spacing issue and updated the margin for the settings link button, but the website title is not bolded and it uses the menu navigation bar, they should look the same

**Comment by MattLichtenstein** [comment]
@petruSt24 it looks like we are changing the font of the `HeaderView` title from body to headline in [HeaderView::setupDetails](https://github.com/mozilla-mobile/firefox-ios/blob/a2525595d6ca93a3ade4849f88b87d3769af7c32/BrowserKit/Sources/ComponentLibrary/Headers/HeaderView.swift#L184). Seems like this, and the corner radius of the favicon are artifacts of the old tracking protection panel and seem to need updating

**Review by MattLichtenstein — CHANGES_REQUESTED** [review]
The connection details title and status text also do not seem to be centered when one of the labels are taking up more than one line
Simulator Screenshot - iPhone 16 - 2024-11-22 at 11 25 12

**Review by MattLichtenstein — APPROVED** [review]

**Pull request merged**
