### PR TITLE
Fixed #6730: open apps preview should hide all screens in private browsing

### LINKED ISSUE #6730: [Private browsing] Open apps preview should hide all screens in private browsing
1. Go to private opened tabs view (clear all opened private tabs)
2. Double tap home button (or swipe up) to scroll through open apps

Expected:
Hides private opened tabs homescreen

Actual:
Shows private opened tabs homescreen

Note: When a new tab is opened in private mode, this should also be hidden as well in the open apps view.

File (1)
IMG_0025

### PR DESCRIPTION
**Pull request by hariszaman**
* Added missing firefoxHomeViewController for hiding
* Added missing emptyPrivateTabsView for hiding

### CODE REVIEW

**Comment by dnarcese** [comment]
Simulator Screen Shot - iPhone 11 - 2020-06-11 at 16 51 13

**Comment by AmyYLee** [comment]
> @AmyYLee pinging for UX review
> Simulator Screen Shot - iPhone 11 - 2020-06-11 at 16 51 13

Hi, 

Can you use Ink 90 #1D1133 for the screen? This is part of the new colour palette (not photon). Thanks

**Comment by hariszaman** [comment]
New color added.

**Comment by hariszaman** [comment]
Does the BuddyBuild failing requires action from my side?

**Comment by dnarcese** [comment]
> Does the BuddyBuild failing requires action from my side?

@hariszaman Nope! We are working on it on our side and I will merge this once BuddyBuild is passing.

**Pull request merged**
