### PR TITLE
Add FXIOS-5714 [v112] Change german pocket discover link

### PR DESCRIPTION
**Pull request by razvanlitianu**
[FXIOS-5714](https://mozilla-hub.atlassian.net/browse/FXIOS-5714) https://github.com/mozilla-mobile/firefox-ios/issues/13165
For German users, the pocket link leads to a localized version of the website.

IMG_0293

### CODE REVIEW

**Review by adudenamedruby — APPROVED** [review]

**Comment by adudenamedruby** [comment]
Heya @razvanlitianu, for future reference, for reviews, if we could please do it in the reviewer section, rather than assigning it to someone. Thanks and great work. :)

**Comment by razvanlitianu** [comment]
> Heya @razvanlitianu, for future reference, for reviews, if we could please do it in the reviewer section, rather than assigning it to someone. Thanks and great work. :)

Will do! Thanks for the review!

**Review by lmarceau — APPROVED** [review]

**Comment by lmarceau** [comment]
Closing and reopening to retrigger BR.

**Comment by mte-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Project coverage: 30.14%</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Edited 1 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 0 files</td>
    </tr>
  </tbody>
</table>

## Client.app: Coverage: 27.03
| File | Coverage ||
| --- | --- | --- |
PocketProvider.swift | 84.21% | ✅

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against aaae06b0c601a2da13cd92677dd495ffd42d6b52
</p>

**Comment by nbhasin2** [comment]
@Mergifyio backport release/v110.2

**Comment by DonalMe** [comment]
@Mergifyio backport release/v111.0

**Pull request merged**
