### PR TITLE
BugFix FXIOS-7440 [v120] Updated from iOS 14 to 15 (Droped iOS 14 Support)

### PR DESCRIPTION
**Pull request by AakifNadeem**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7440)
Resolved Issue #16479 

## :bulb: Description
Updated iOS 14 to 15 in Common.xconfig
Also, I had to make changes in Widget Build Settings as it was not picking development targets from common.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by nbhasin2** [comment]
If we are to do this then it would be best to also update Readme so that it mentions iOS 15

**Comment by AakifNadeem** [comment]
@nbhasin2 I've updated Readme as well. Kindly have a look at it.

**Review by thatswinnie — APPROVED** [review]

**Review by nbhasin2 — APPROVED** [review]

**Comment by nbhasin2** [comment]
Bigger question is when should we land this cc @OrlaM @yoanarios @clarmso ?

**Comment by isabelrios** [comment]
As @clarmso mentioned we will need to update the test devices in bitrise.yml to use iOS 15, currently we are using 14.6.

**Comment by clarmso** [comment]
> As @clarmso mentioned we will need to update the test devices in bitrise.yml to use iOS 15, currently we are using 14.6.
> 
> Anyways, I'm not sure but looks like this PR has not run on Bitrise yet and so the red mark...

@isabelrios @nbhasin2 Oops. I mixed up XCode version and iOS version. We are currently using iOS 16.4 and XCode 14.3.1 in our testing currently.

https://github.com/mozilla-mobile/firefox-ios/blob/main/bitrise.yml#L177

https://github.com/mozilla-mobile/firefox-ios/blob/main/bitrise.yml#L189

**Comment by isabelrios** [comment]
> > As @clarmso mentioned we will need to update the test devices in bitrise.yml to use iOS 15, currently we are using 14.6.
> > Anyways, I'm not sure but looks like this PR has not run on Bitrise yet and so the red mark...
> 
> @isabelrios @nbhasin2 Oops. I mixed up XCode version and iOS version. We are currently using iOS 16.4 and XCode 14.3.1 in our testing currently.
> 
> https://github.com/mozilla-mobile/firefox-ios/blob/main/bitrise.yml#L177
> 
> https://github.com/mozilla-mobile/firefox-ios/blob/main/bitrise.yml#L189

right, I also mixed numbers.. 16.4 is the correct one, then this PR should be good... let's trigger bitrise and see

**Comment by isabelrios** [comment]
The build is failing because of the warnings: Number of warnings is:       **91**. This is greater than build threshold: 8

**Comment by AakifNadeem** [comment]
@isabelrios yes dear I just took the pull from the main branch. Most of the warnings are due to Xcode 15 (duplicate libraries) issues.

**Comment by clarmso** [comment]
> @isabelrios I just took the pull from the main branch. Most of the warnings are due to Xcode 15 (duplicate libraries) issues.

@AakifNadeem 😄 We are still using XCode 14.3.1 at the moment. XCode 15 support is coming soon. Please use XCode 14.3.1 for the work until we announce XCode 15 support. The team has discovered some code updates that are XCode 15 specific.

**Comment by AakifNadeem** [comment]
@isabelrios I've updated the branch with the latest main branch kindly let me know what bitrise issue?

**Comment by OrlaM** [comment]
Looks like the warnings are still there even after the 15 update. 
"91. This is greater than build threshold: 12"

**Comment by OrlaM** [comment]
I just took a look at the warnings this introduces and they are not trivial to solve. I'd recommend for now just increasing the warning count. You can do this by updating [these values](https://github.com/mozilla-mobile/firefox-ios/blob/b9d6833276a89bbdddfbfd325df10297e90591ff/test-fixtures/generate-metrics.sh#L7C1-L8C22).
I'll create some follow up tickets to go back through and address the deprecations.
You can try setting both values to 92.

**Comment by OrlaM** [comment]
This task is starting to block other work so in the interest of time I have branched off of your branch to continue the work. The commits are still attributed to you so will still show up as yours in the history. 
I will close this PR and the work will continue in this one https://github.com/mozilla-mobile/firefox-ios/pull/16897

**Pull request closed without merging**
