### PR TITLE
Build FXIOS-8134 [v123] Upgrade Taskgraph to v7.x + update deps

### PR DESCRIPTION
**Pull request by ahal**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-8134)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/18100)

## :bulb: Description
There has been a major Taskgraph release that contains several backwards incompatible changes. Let's update to it before we start work on building out more tasks.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [x] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [x] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by ahal** [comment]
@isabelrios I'm not sure what to do about the bitrise failure. I tried logging into Bitrise with my Github, but am getting a 500 error from Bitrise.

**Comment by isabelrios** [comment]
> @isabelrios I'm not sure what to do about the bitrise failure. I tried logging into Bitrise with my Github, but am getting a 500 error from Bitrise.

That’s not an error is that the build has not started. We need to trigger it manually. I will add you to Bitrise so that you can do that. In the meantime I will trigger it for you.

**Comment by isabelrios** [comment]
@ahal I have run `taskgraph full` in this branch and I get some errors that I don't get in main...
```
File "/opt/homebrew/lib/python3.9/site-packages/taskgraph/config.py", line 130, in load_graph_config
    raise Exception(f"Couldn't find taskgraph configuration: {config_yml}")
Exception: Couldn't find taskgraph configuration: taskcluster/ci/config.yml
```

**Review by bhearsum — APPROVED** [review]

**Comment by isabelrios** [comment]
I was using an older version of taskgraph, after updating to the same version here, everything are working fine.

**Review by isabelrios — APPROVED** [review]

**Pull request merged**
