### PR TITLE
Bug 1345231 - Cast nils to NSNull to properly stringify our JSON payloads

### PR DESCRIPTION
**Pull request by sleroux**
Mirror of https://github.com/mozilla-mobile/firefox-ios/pull/2557 for the master branch.

### CODE REVIEW

**Comment by sleroux** [comment]
> Please say "writtingOptionsKeys" is a typo on your end, not a misspelling in the library…

Nope that's the library. Looks like the author has since updated it and fixed the spelling.

> Do you still need the .utf8?

Nope. That's a different API :)

**Comment by sleroux** [comment]
I've gone ahead and landed this on v7.x - @rnewman unless there are some additional things you want resolved could you go ahead and approve this? Thanks!

**Comment by rnewman** [comment]
Let me know when you have a fix for the reader mode issue…

**Comment by sleroux** [comment]
Going to close this in favor of @justindarc's patch which fixes the reader mode issue this patch introduces.

**Comment by sleroux** [comment]
PR referenced in last comment: https://github.com/mozilla-mobile/firefox-ios/pull/2575

**Pull request closed without merging**
