### PR TITLE
Refactor try to workaround temporary unit tests bitrise

### PR DESCRIPTION
**Pull request by isabelrios**
Unit tests are failing and getting stuck very often #11145 , let's see if the issue is due to the use of M1 or there are other reasons for those issues

### CODE REVIEW

**Comment by isabelrios** [comment]
First round all Unit Tests passed. Re-running several times to be sure we don't face the failure mentioned in the description

**Comment by isabelrios** [comment]
Second round, unit test failure: `AdjustTelemetryHelperTests.testFirstSessionPing()`

**Comment by isabelrios** [comment]
Third round two unit tests failures:
```
	ClientTests:
		AdjustTelemetryHelperTests.testDeeplinkHandleEvent_GleanCalled()
		AdjustTelemetryHelperTests.testFirstSessionPing()
```
https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/70c841b0-4e2f-43d6-99a6-69726a8c393f

**Comment by isabelrios** [comment]
Four round, with the AdjustTelemetryHelperTests disabled, all unit tests ✅ 
https://app.bitrise.io/build/4ac33779-c089-422f-80ac-c78d0bad3dbe

**Review by electricRGB — APPROVED** [review]

**Pull request closed without merging**
