### PR TITLE
Bugfix FXIOS-6560 [v116] Credit card sync pulls in incorrect formatting 

### PR DESCRIPTION
**Pull request by petruSt24**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-6560)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/14687)

### Description
fixed the inconsistency in the Credit Card Sync between desktop and mobile

### Pull requests checks where applicable
- [X] Fill in the three TODOs above (tickets number and description of your work)
- [X] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [ ] Unit tests written and passing
- [ ] Documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by nbhasin2** [comment]
@petruSt24 do you have a small video or gif that you can attach with the fix
Basically did you try it with the desktop cards?

**Comment by petruSt24** [comment]
> @petruSt24 do you have a small video or gif that you can attach with the fix Basically, did you try it with the desktop cards?

I did test it with the desktop variant but I didn't make a video of it

**Comment by lmarceau** [comment]
@petruSt24 could you attach a video to the PR? I think we need this to move the PR forward?

**Comment by nbhasin2** [comment]
Tested this locally, should be good to merge cc @petruSt24 @lmarceau 
image

**Review by nbhasin2 — APPROVED** [review]

**Comment by nbhasin2** [comment]
image
@petruSt24 can you check if the sync'ed cards are valid?

Also, you will need to rebase before we merge due to a warning error

**Comment by petruSt24** [comment]
I changed only the way the data is shown by forcing the year to have only the last 2 numbers and the uppercased the cardType to be handled correctly by the existing method. On the desktop variant you can add a card with only 14 numbers, which can't be done on mobile, and when syncing that kind of card it will show as invalid on mobile.

**Comment by nbhasin2** [comment]
@Mergifyio backport release/v116

**Pull request merged**
