### PR TITLE
Refactor FXIOS-8968 - Update Fonts related to Accessory view to use FXFontStyles

### PR DESCRIPTION
**Pull request by bmihai23**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-8968)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/19805)

## :bulb: Description
- This PR updates the font styles used in AccessoryViewProvider, TPAccessoryInfo, and AutofillAccessoryViewButtonItem classes to improve consistency and adaptability to dynamic font sizes.

**AccessoryViewProvider  - Before**
| Portrait  | Landscape | 
| ------------- | ------------- |
| Simulator Screenshot - iPhone 15 Pro - 2024-06-25 at 21 47 38 | Simulator Screenshot - iPhone 15 Pro - 2024-06-25 at 21 47 41 |

**AccessoryViewProvider - After**
| Portrait  | Landscape | 
| ------------- | ------------- |
| Simulator Screenshot - iPhone 15 Pro - 2024-06-25 at 21 50 39 | Simulator Screenshot - iPhone 15 Pro - 2024-06-25 at 21 50 43 |

**TPAccessoryInfo - Before**
| Portrait  | Landscape | 
| ------------- | ------------- |
| Simulator Screenshot - iPhone 15 Pro - 2024-06-25 at 22 02 47 | Simulator Screenshot - iPhone 15 Pro - 2024-06-25 at 22 02 49 |

**TPAccessoryInfo - After**
| Portrait  | Landscape | 
| ------------- | ------------- |
| Simulator Screenshot - iPhone 15 Pro - 2024-07-04 at 11 04 49 | Simulator Screenshot - iPhone 15 Pro - 2024-07-04 at 11 04 53 |

**AutofillAccessoryViewButtonItem - Before**
| Portrait  | Landscape | 
| ------------- | ------------- |
| Simulator Screenshot - iPhone 15 Pro - 2024-06-25 at 22 20 16 | Simulator Screenshot - iPhone 15 Pro - 2024-06-25 at 22 20 41 |

**AutofillAccessoryViewButtonItem - After**
| Portrait  | Landscape | 
| ------------- | ------------- |
| Simulator Screenshot - iPhone 15 Pro - 2024-07-04 at 11 08 21 | Simulator Screenshot - iPhone 15 Pro - 2024-07-04 at 11 08 24 |
 

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Review by adudenamedruby — APPROVED** [review]

**Comment by adudenamedruby** [comment]
@cwzilla heya, just asking you to verify UI looks!

**Comment by cwzilla** [comment]
Hi @bmihai23, thank you for the screenshots!

Just 2 small changes I noticed:
- For `TPAccessoryInfo`, should we update 'BLOCKS' heading use the bold style?
- For `AutofillAccessoryViewButtonItem`, can we update the 'Use saved card' font to the bold style as well?

Thank you!

**Comment by bmihai23** [comment]
> Hi @bmihai23, thank you for the screenshots!
> 
> Just 2 small changes I noticed:
> 
> * For `TPAccessoryInfo`, should we update 'BLOCKS' heading use the bold style?
> * For `AutofillAccessoryViewButtonItem`, can we update the 'Use saved card' font to the bold style as well?
> 
> Thank you!

Hi @cwzilla, thanks for the heads up, I just updated the code to use bold instead of regular text style and also updated the screenshots. Please let me know if should I change anything else, thanks again

**Comment by cwzilla** [comment]
> > Hi @bmihai23, thank you for the screenshots!
> > Just 2 small changes I noticed:
> > 
> > * For `TPAccessoryInfo`, should we update 'BLOCKS' heading use the bold style?
> > * For `AutofillAccessoryViewButtonItem`, can we update the 'Use saved card' font to the bold style as well?
> > 
> > Thank you!
> 
> Hi @cwzilla, thanks for the heads up, I just updated the code to use bold instead of regular text style and also updated the screenshots. Please let me know if should I change anything else, thanks again

Thanks for the changes! Looks good :)

**Review by adudenamedruby — APPROVED** [review]

**Comment by adudenamedruby** [comment]
Heya @bmihai23. Can you rebase against `main`, please. There was an issue that was causing the build pipeline to fail. It's been fixed, however. Let's get that in here, get it passed, and then merge this PR. :)

**Comment by bmihai23** [comment]
> Heya @bmihai23. Can you rebase against `main`, please. There was an issue that was causing the build pipeline to fail. It's been fixed, however. Let's get that in here, get it passed, and then merge this PR. :)

Ola @adudenamedruby, thanks for the heads up. I just merged the main branch into this one, let me know if I need to do anything else. Thank you

**Pull request merged**
