### PR TITLE
Bugfix FXIOS-8450 [v123] Fix private mode issues

### LINKED ISSUE #18740: [Tab tray refactor] Incorrect tabs are displayed  in tab tray after a private tab is closed
### Scenario 1: 
1. Have 3 normal browsing tabs opened 
1. Have 3 private browsing tabs opened
1. Open the tab tray -> Navigate to the private browsing 
1. Close one Private tab 
1. Check the thumbnails  that are displayed

### Scenario 2: 
1. Have 1 normal browsing tabs opened 
1. Have 3 private browsing tabs opened
1. Open the tab tray -> Navigate to the private browsing 
1. Close one Private tab 
1. Check the behavior 
1. Repeat the steps 3->5 to close all private tabs 

### Expected behavior
Scenario 1: 

Private tab thumbnails should be displayed 

Scenario 2: 
Tab tray should stay opened. 

### Actual behavior
Scenario 1: 

Normal tab thumbnails are displayed be displayed under the Private tab section.

Scenario 2: 
Tab tray closes and the latest private tab opens. When the last private tab is closed the normal tab opens. 

Notes:

Same issue reproduces while felt-privacy experiment is on  

### Device & build information
* Device: iPhine 14+ (16.0.2) 
* Build version: 123 (38801) & v9000 (38860) 
* First seen version: ? 

*# 
*## Notes
Attachments: <
!--- Screenshots or screen recordings are very helpful for reproducing|width=200,height=183!
 -->

[https://github.com/mozilla-mobile/firefox-ios/assets/124251579/f9b19770-d3d5-4b76-bbf5-6315cc5525e9](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/f9b19770-d3d5-4b76-bbf5-6315cc5525e9)

[https://github.com/mozilla-mobile/firefox-ios/assets/124251579/e3385b68-283c-40be-97a0-512b202883dc](https://github.com/mozilla-mobile/firefox-ios/assets/124251579/e3385b68-283c-40be-97a0-512b202883dc)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8450)

### PR DESCRIPTION
**Pull request by OrlaM**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-8450)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/18728)
Also fixes #18740 

## :bulb: Description
Update what happens when private tabs are closed

## :pencil: Checklist
You have to check all boxes before merging
- [ ] Filled in the above information (tickets numbers and description of your work)
- [ ] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by OrlaM** [comment]
@MergifyIO backport release/v123 release/v124

**Comment by dataports** [comment]
I think the links in the description for the Github ticket and the [extra ticket #18728](https://github.com/mozilla-mobile/firefox-ios/issues/18728) are reversed!

I checked the behavior of 18728 and it's still not working quite right. When the last tab in private mode is closed it still goes back to the normal tab tray, the title just doesn't change on the Tab Manager header for some reason 🤔 

https://github.com/mozilla-mobile/firefox-ios/assets/5545720/afcef8df-cadf-4e99-ab1b-e10fd74d87ad

**Comment by OrlaM** [comment]
@dataports this should be working correctly now.

**Review by dataports — APPROVED** [review]
LGTM!

**Comment by dataports** [comment]
Hope you don't mind, I went ahead an merged this because I was hoping it would fix some issues on my branch that I'm seeing

**Pull request merged**
