### PR TITLE
Fix #5877 - [iPad][iOS 12.x] Library panel buttons are cut off

### LINKED ISSUE #5877: [iPad][iOS 12.x] Library panel buttons are cut off
Device: iPad Air 2
iOS: 12.3
Build: 21.0 (16901)

Steps to reproduce
1. Go to Library pane

Actual results:
- Library panel but labels are cut. 

Note:
- Issue also reproducible on master 13c33989cd7b
- Not reproducible on iPhone
Screen Shot 2019-12-09 at 5 59 09 PM

### PR DESCRIPTION
**Pull request by nbhasin2**
Fixed the bottom right padding issues on iPad for Bookmark View.

image

### CODE REVIEW

**Comment by muhasturk** [comment]
Same #5878 PR already created before you push.

**Comment by garvankeeley** [comment]
@muhasturk thanks for chiming in, I commented here https://github.com/mozilla-mobile/firefox-ios/pull/5878#issuecomment-563465282 that we are in a rush. But I would prefer to land the PR from you since you authored it, so please let me know thanks

**Comment by muhasturk** [comment]
I got it, if you are in a rush no problem just pick you need it.

**Comment by garvankeeley** [comment]
Thanks for understanding!

**Pull request merged**
