### PR TITLE
Refactor [v105] Add missing locales: et and si

### PR DESCRIPTION
**Pull request by isabelrios**
I think we need to add to the project the missing locales so that at least the import works... This PR is adding those.

I have checked that after I do this, I can import the changes for those locales locally.  

cc @electricRGB @flodolo as it is related to: https://github.com/mozilla-mobile/firefox-ios/issues/11391git

### CODE REVIEW

**Comment by flodolo** [comment]
Should we add them to shipping-locales.txt?

**Comment by isabelrios** [comment]
> Should we add them to shipping-locales.txt?

oh now that you mention.. yeah for firefox-iOS it may be needed as well as it still uses that list if I'm not mistaken...

**Comment by flodolo** [comment]
I think so https://github.com/mozilla-mobile/LocalizationTools/blob/main/Sources/LocalizationTools/main.swift#L41-L47

**Comment by isabelrios** [comment]
Yeah, they have to be added but also added as a locale to the project... pa-IN https://github.com/mozilla-mobile/firefox-ios/blob/31bf92549aa064cf49b34d949d7112c552b916f3/shipping_locales.txt#L67 was already in the shipping-locales.txt file but it was not being imported.. so looks like both are needed.

**Comment by flodolo** [comment]
> was already in the shipping-locales.txt file but it was not being imported.. so looks like both are needed.

That looks like an issue we should have on file. Any chance you could do it? At least to explain what you did manually, and possibly for someone to find an automated fix.

**Comment by isabelrios** [comment]
@electricRGB I added en-US. Before adding it there was only one file localized:
Captura de Pantalla 2022-07-29 a las 11 19 02

After adding it, there are more files localized:
Captura de Pantalla 2022-07-29 a las 11 19 51

I think that is what was missing with this locale for the issue you were seeing?

Have in mind that I'm not including the localized files changes after the string import, that will happen in the github action once this lands.

**Comment by isabelrios** [comment]
> > was already in the shipping-locales.txt file but it was not being imported.. so looks like both are needed.
> 
> That looks like an issue we should have on file. Any chance you could do it? At least to explain what you did manually, and possibly for someone to find an automated fix.

I think the issue will be fixed with this PR, even though the locale was in the shipping-locales.txt list, it was not added to the project so the files could not found to do the import. Now that the locale has been added as et and en-US, I would expect the string import works once this PR lands

**Comment by isabelrios** [comment]
> > > was already in the shipping-locales.txt file but it was not being imported.. so looks like both are needed.
> > 
> > 
> > That looks like an issue we should have on file. Any chance you could do it? At least to explain what you did manually, and possibly for someone to find an automated fix.
> 
> I think the issue will be fixed with this PR, even though the locale was in the shipping-locales.txt list, it was not added to the project so the files could not found to do the import. Now that the locale has been added as et and en-US, I would expect the string import works once this PR lands

I'm afraid I was not right with my comment above... pa-IN was already added, the import should work for that locale... Sometimes with locales with similar names we have seen issues not matching the name here with pontoon and/or the l10n repo...
In order to not tl make this PR more complex, if you agree I will fix here the `et` and `en-US` issue and investigate the pa-IN in a different one

**Comment by flodolo** [comment]
> I'm afraid I was not right with my comment above... pa-IN was already added, the import should work for that locale... Sometimes with locales with similar names we have seen issues not matching the name here with pontoon and/or the l10n repo...

That shouldn't be the issue with pa-IN specifically: it's `pa-IN` in the l10n repository, Pontoon, and even in the target-language within the XLIFF file. Even if I export Punjabi from XCode, it's exported as `pa-IN` (not `pa`).

Import seems to be working: tested locally with both XCode and script, and I get the same two strings in the [pending PR](https://github.com/isabelrios/firefox-ios/pull/10/files#diff-39bfa6fdce4be00712139432afd7b8a95dccb4a605477180ce07daeb3a031af6) in your repository?.

**Comment by isabelrios** [comment]
> Import seems to be working: tested locally with both XCode and script, and I get the same two strings in the [pending PR](https://github.com/isabelrios/firefox-ios/pull/10/files#diff-39bfa6fdce4be00712139432afd7b8a95dccb4a605477180ce07daeb3a031af6) in your repository?.

Oh, I forgot  about that PR and the fix to the import string github action. Then for pa-IN the import works... in fact the issue for firefox is for `si` not `pa-IN`  🤦‍♀️  my bad, was confused with focus... sorry about all the noise about that... 
I will add `si` as I have done for `et` in this PR

**Comment by electricRGB** [comment]
LGTM. :)

**Comment by isabelrios** [comment]
> LGTM. :)

@electricRGB Thanks for looking at this PR, I have "officially" asked for your review, otherwise I can't land 🙈

**Comment by isabelrios** [comment]
I tested that adding `si` works when the import sting runs: https://github.com/isabelrios/firefox-ios/pull/11/files#diff-541ebedafb25f148366b11e6ac39ae96052a0ce031bd26f9a3b5abaaaaaf5e5a

**Comment by flodolo** [comment]
> I tested that adding `si` works when the import sting runs

Thanks. I think the most urgent thing is fixing these two locales, then we can look in a long term solution (which is likely to write proper code for the patch I have in my LocalizationTools fork)

**Review by electricRGB — APPROVED** [review]

**Pull request merged**
