### PR TITLE
Refactor FXIOS-7995 [v123] Improve PasswordManagerOnboardingViewController

### PR DESCRIPTION
**Pull request by bmihai23**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7995)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/17839)

## :bulb: Description
- Refactored UI element declarations in PasswordManagerOnboardingViewController using .build for cleaner syntax.
- Deprecated 'titleEdgeInsets' for continueButton and instead configured button properties directly.
- Introduced a private struct UX to centralize and organize constant values related to user experience.

| Portrait  | Landscape | 
| ------------- | ------------- |
| Simulator Screenshot - iPhone 15 Pro - 2023-12-21 at 09 36 50 | Simulator Screenshot - iPhone 15 Pro - 2023-12-21 at 09 37 13 |

| Portrait  | Landscape | 
| ------------- | ------------- |
| Simulator Screenshot - iPhone 15 Pro - 2023-12-21 at 09 37 11 | Simulator Screenshot - iPhone 15 Pro - 2023-12-21 at 09 37 13 |

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Review by cyndichin — APPROVED** [review]
thank you for this update! 🔥 Another enhancement if you are interested is to investigate the possibility of using the `PrimaryRoundedButton` and `LinkButton` from our Component Library to replace these UI elements

**Comment by bmihai23** [comment]
> thank you for this update! 🔥 Another enhancement if you are interested is to investigate the possibility of using the `PrimaryRoundedButton` and `LinkButton` from our Component Library to replace these UI elements

Thank you for your feedback

**Comment by cyndichin** [comment]
> > thank you for this update! 🔥 Another enhancement if you are interested is to investigate the possibility of using the `PrimaryRoundedButton` and `LinkButton` from our Component Library to replace these UI elements
> 
> Thank you for your feedback

I noticed you closed the PR, any issues with merging this in? Or did you want to address the enhancement? I can also open a separate ticket up, let me know what works best for you!

**Comment by bmihai23** [comment]
> > > thank you for this update! 🔥 Another enhancement if you are interested is to investigate the possibility of using the `PrimaryRoundedButton` and `LinkButton` from our Component Library to replace these UI elements
> > 
> > 
> > Thank you for your feedback
> 
> @bmihai23 I noticed you closed the PR, any issues with merging this in? Or did you want to address the enhancement? I can also open a separate ticket up, let me know what works best for you!

There is no other issue, when I tried to respond to you, I pressed ‘Close with comment’ instead of ‘comment’. I think @lmarceau opened an issue to continue working on these two buttons. You can merge this PR. Thanks again 🙏🏻

**Comment by cyndichin** [comment]
great, thank you so much @bmihai23!

**Pull request merged**
