### PR TITLE
Automation/xcui test automation prototype

### PR DESCRIPTION
**Pull request by horatiupurec**
Created a new prototype for XCUITests, which has the purpose to better organise and improve the  UI test scripts.
Refactored the ActivityStreamTest suite to illustrate the prototype.

### CODE REVIEW

**Comment by isabelrios** [comment]
Hi @horatiupurec! you have done a great work here! sorry it is taking some time to review but I will be on it soon. Thanks!

**Comment by isabelrios** [comment]
There is one thing that I'm not very sure about...adding all the tests into the Tests folder may break the [Sync Integration test](https://github.com/mozilla-mobile/firefox-ios/tree/master/SyncIntegrationTests)s and the [Localization tests](https://github.com/mozilla-mobile/firefox-ios/wiki/Screenshots-for-Localization#running-from-the-command-line) (have in mind that we launch them using scripts, so the paths may have to be updated too...)

I tried to have the first ones working and so far I can't...but I may be missing a path updated or so...if you could verify that both kind of tests work with these changes, that would help.

A different approach would be to have the Helpers folders as you created, but the tests in the root XCUITests directory since that directory only contains these kind of tests...

**Comment by horatiupurec** [comment]
> There is one thing that I'm not very sure about...adding all the tests into the Tests folder may break the [Sync Integration test](https://github.com/mozilla-mobile/firefox-ios/tree/master/SyncIntegrationTests)s and the [Localization tests](https://github.com/mozilla-mobile/firefox-ios/wiki/Screenshots-for-Localization#running-from-the-command-line) (have in mind that we launch them using scripts, so the paths may have to be updated too...)
> 
> I tried to have the first ones working and so far I can't...but I may be missing a path updated or so...if you could verify that both kind of tests work with these changes, that would help.
> 
> A different approach would be to have the Helpers folders as you created, but the tests in the root XCUITests directory since that directory only contains these kind of tests...

It makes sense, as I wasn't aware about the "Sync Integration test" (I will get up-to-date about this and try a solution, or, at least, I could move the tests back to the test target's root folder).

**Comment by isabelrios** [comment]
Some comments after our meeting: 
- Move tests files into the root XCUITests directory
- Agree on having the new helpers, new checks, constants and elements classes
- Think about how to use the steps into FxScreenGraph or the best way to keep using it as it is with this new approach for refactoring the tests.

As said, I really appreciate the help to improve our automated test environment. We could add your idea to improve once we iterate about what we talked.

**Comment by horatiupurec** [comment]
Moved the test class files back into the root XCUITests directory.
I am thinking about a way of using the FxScreenGraph class for steps implementation. It's a great implementation that I was not aware of, but I will integrate it in the prototype to replace the static TestStep class.

**Pull request closed without merging**
