### PR TITLE
Refactor FXIOS-6775 [v116] Remove BrowserSyncManager class and sync manager experiment logic

### PR DESCRIPTION
**Pull request by lougeniaC64**
[FXIOS-6775](https://mozilla-hub.atlassian.net/browse/FXIOS-6775)
[15085](https://github.com/mozilla-mobile/firefox-ios/issues/15085)

### Description
This PR is the first of three PRs that will remove the sync manager experiment code and the obsolete sync code used by `BrowserSyncManager`. My initial plan of splitting these changes out between the code that's modified and the code that's removed wasn't feasible, but I've tried to separate these changes out as best as I can without making the reviews overwhelming or managing the branches for the PRs onerous. 

This PR includes the following:
- Removal of the `BrowserSyncManger` class
- Removal of the sync manager Nimbus experiment code
- Updates to the `BrowserProfile` class to remove the Nimbus experiment branch logic and update the sync functions to remove reliance on the `OldSyncReason` and `OldSyncResult` types (these types will be completely removed in the second cleanup PR)
- Removal of related tests
- Removal of or updates to dependent logic as needed

**NOTE:** It may be easier to start the code review with [Profile.swift](https://github.com/mozilla-mobile/firefox-ios/pull/15086/files#diff-d08b9cccc66a4d6392978928ba91ef19f02df000077650a4db9bb01874436354) as the vast majority of the changes in this PR result from the changes made in that file.

### Pull requests checks where applicable
- [ x ] Fill in the three TODOs above (tickets number and description of your work)
- [ x ] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [ ] Unit tests written and passing
- [ ] Documentation / comments for complex code and public methods

### CODE REVIEW

**Review by OrlaM — APPROVED** [review]
LGTM

**Comment by lmarceau** [comment]
This test failed more than once in BR, seems not to be a fluke 
Screenshot 2023-06-21 at 1 57 49 PM

**Review by nbhasin2 — APPROVED** [review]

**Comment by lougeniaC64** [comment]
> This test failed more than once in BR, seems not to be a fluke

My apologies @lmarceau , I thought I was experiencing the usual timeout of that test and didn't see that the failure was caused by a legitimate issue.

I think I'm going to remove this test because it's going to be time consuming to fix and I'm working on a PR that targets v117 that will replace the temp sync metrics with ones we've defined in A-S. This change will basically be re-implementing #14243 and removing the associated temp sync logic. For context, the reason this test is failing is because the device data can't be retrieved in [syncRustEngines](https://github.com/mozilla-mobile/firefox-ios/blob/4ecc008047a25e281a3547ec7d23c804b4dd842d/Providers/RustSyncManager.swift#L423) because it's empty and needs to be mocked.

I also think `testSyncPingIsSentOnSyncOperation` has decreasing value for us at this point. It's highly unlikely that we'll make a change that will prevent the sync ping from being sent before the temp sync metrics are removed. And if such a change does occur, it'll be fairly obvious in our sync metrics dashboard.

@OrlaM @nbhasin2 since you previously approved, let me know if you have any reservations about this removal.

**Comment by lmarceau** [comment]
Green! Merging!

**Pull request merged**
