### PR TITLE
Bugfix FXIOS-8225 [v124] Unit Test Failure: testUpdateEnginePrefs_addressesDisabled

### PR DESCRIPTION
**Pull request by jnrahme**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-8225)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/18279)

## :bulb: Description
Unit Test Failure: testUpdateEnginePrefs_addressesDisabled fix

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by OrlaM** [comment]
Please rerun the tests on bitrise a few times to verify it's actually fixed.

**Comment by clarmso** [comment]
> Please rerun the tests on bitrise a few times to verify it's actually fixed.

I will do so later today and report the test results here.

**Comment by clarmso** [comment]
Running the updated test 1000 times on Bitrise 🎉 : https://app.bitrise.io/build/2b79cb23-165f-40e2-8633-0c3c5d8098bc

Running the whole test file 100 times on Bitrise: https://app.bitrise.io/build/940c2949-05fc-4477-b0c9-5f8c05efd128
* `RustSyncManagerTests.testGetEnginesAndKeys()` once

**Review by clarmso — APPROVED** [review]

**Review by OrlaM — APPROVED** [review]

**Comment by isabelrios** [comment]
Let's land this and keep monitoring the tests.. Thanks!

**Comment by clarmso** [comment]
@mergifyio backport release/v123

**Pull request merged**
