### PR TITLE
Fix sharing wrong link after visiting certain URL resources

### PR DESCRIPTION
**Pull request by junbio**
This PR fixes the issue where the wrong link would be shared after visiting certain URLs with a resource type such as PDF, image, etc, and then navigating back. #8626

### CODE REVIEW

**Comment by nishant2718** [comment]
hey! 👋  Looking into this - will update you @junbio

**Comment by nishant2718** [comment]
Sorry it took a bit - can you write out your testing steps?

**Comment by junbio** [comment]
1. Go to https://arstechnica.com/gadgets/2021/06/huaweis-harmonyos-will-rollout-to-100-android-models-over-the-next-year/
2. Tap image in slideshow
3. Tap share
4. Tap back button
5. Tap share

**Comment by nishant2718** [comment]
Okay, just my thoughts. 

Your solution works, but I'm hesitant because we're resetting that tab property inside a WKNavigationDelegate func. I think we should try to isolate tab specific changes to within either TabManager, or Tab itself. 

I think it's good to reset this property in `Tab.swift`. 

What you can do write an extension on `Tab` and conform it to `URLChangeDelegate`. You'll have to implement `func tab(_ tab: Tab, urlDidChangeTo url: URL)`.

We have an observer inside Tab, `observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey: Any]?, context: UnsafeMutableRawPointer?)`. Inside here, you can invoke your func and reset the temporaryDocument property. 

@lmarceau what do you think? Did I overlook something?

**Comment by junbio** [comment]
>Your solution works, but I'm hesitant because we're resetting that tab property inside a WKNavigationDelegate func.

webView(_:decidePolicyFor: navigationResponse decisionHandler:) also resets the tab's temporaryDocument property directly; the issue is that it's not called if the page was cached (as would be the case if going back). It seems like since webView(_:decidePolicyFor: navigationAction decisionHandler:) is always called it would be a better place to reset the property.

**Comment by nishant2718** [comment]
Since we use KVO in conjunction with WKWebView, that shouldn't be an issue. That observation will always be called on each page load. You can double check by breakpointing in that observation as well.

I'd try keeping WKNavDelegate as pure as possible, and going with resetting in tab would likely be a good way.

**Review by nishant2718 — CHANGES_REQUESTED** [review]
I suggest utilizing KVO inside Tab for this. See the earlier comment for details.

**Comment by junbio** [comment]
Made the changes as requested. Thanks!

**Comment by lmarceau** [comment]
@junbio I tested with the changes (with [steps](https://github.com/mozilla-mobile/firefox-ios/pull/9955#issuecomment-1036430747)), but I still see the image link after pressing back. Did I overlook something?

https://user-images.githubusercontent.com/11338480/160191887-88f8658d-94d0-4d5e-93b1-b59c22eb8eff.mp4

**Comment by junbio** [comment]
That's odd since it works on my end. Can you try setting a breakpoint inside URLChangeDelegate and seeing if it's called? Thanks!

**Comment by lmarceau** [comment]
@junbio Ok I know what happened. I had rebased onto `main` and by rebasing it's not working anymore 🤔 I tested without rebasing and it works on this branch though. Would you mind having a look?

**Pull request closed without merging**
