### PR TITLE
Bugfix FXIOS-4761 [v106] Remove QuickLinkSelectionIntent

### PR DESCRIPTION
**Pull request by lmarceau**
# [FXIOS-4761](https://mozilla-hub.atlassian.net/browse/FXIOS-4761) https://github.com/mozilla-mobile/firefox-ios/issues/11596
- Rename WidgetIntents to QuickActionIntent 
- Remove QuickLinkSelectionIntent
- Fix bug where top sites widget data wasn't saved since widgetManager was released in app delegate

### CODE REVIEW

**Comment by lmarceau** [comment]
This will also fix #11666

**Review by nbhasin2 — APPROVED** [review]

**Comment by lmarceau** [comment]
Build is green [here](https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/22fdb961-3425-4ddb-ad4c-a21be6927d5d)
Screen Shot 2022-08-22 at 3 48 30 PM

**Comment by flodolo** [comment]
I think this might potentially mess up localization.

When extracting strings, the file now changes from `WidgetKit/Base.lproj/WidgetIntents.intentdefinition` to `WidgetKit/Base.lproj/QuickActionIntent.intentdefinition`. I can deal with that by running the import script with a different parameter.

But:
1. You moved around .strings files in this PR. The next time the GH workflow imports strings, I think it's going to re-create the old files.
2. If I make the change on the l10n repository (updating the filename in XLIFF), what happens if we try to uplift those translations to the v105 branch? Will they be imported and used correctly?

2 might work because the .strings files will be still there, but it's something to keep an eye out for.

**Comment by flodolo** [comment]
For now, I've exposed the strings and manually reverted the change to that filename, so that we can localized the 2 broken strings (Close, Automatic)

**Comment by flodolo** [comment]
Since I'm working on this https://github.com/mozilla-mobile/LocalizationTools/pull/2, I can actually test import one single locale and answer some questions.

Importing an existing XLIFF with the `WidgetIntents.intentdefinition` doesn't re-create the file. `xcodebuild` raises a couple of warnings, which is OK.

```
--- xcodebuild: WARNING: WidgetKit/Base.lproj/QuickActionIntent.intentdefinition: File not found in the XLIFF
--- xcodebuild: WARNING: WidgetKit/Base.lproj/WidgetIntents.intentdefinition: File not found in the project
```

I think point 2 can be ignored, since these are very old strings, and it's unlikely to have an impact if we can't import strings for a cycle.

**Comment by lmarceau** [comment]
I'll open a PR to revert the name change, sorry for the trouble

**Pull request merged**
