### PR TITLE
Bugfix #10135 [v99] Correct loading spinner direction for sync loading 

### PR DESCRIPTION
**Pull request by finebel**
This PR corrects the behaviour described in #10135.

New:

https://user-images.githubusercontent.com/46824694/156393165-4bde8cbe-6cd1-4bbc-bc64-395efbe07be2.mov

### CODE REVIEW

**Comment by finebel** [comment]
While correcting the spinner direction, I found out that there is a `SyncMenuButton` class in the Codebase. This class is apparently not used at the moment. Am I missing something or could the class be removed?

**Comment by electricRGB** [comment]
Hey @finebel. Thanks so much for this and for your other contributions :)

However, I think a better solution for this is to actually flip the icon. Nearly universally, spinners spin clockwise and we should follow this implementation. By spinning the icon around, we fix the issue and respect the clockwise spin. :)

**Comment by finebel** [comment]
Sounds reasonable.  
We could flip the icon by using `imageView.transform = CGAffineTransform(scaleX: -1, y: 1)`. Would this be ok?

**Comment by electricRGB** [comment]
Yeah, the transform is totally fine. We're not showing a ton so it's not a lot of work to do.

**Review by electricRGB — APPROVED** [review]

**Comment by lmarceau** [comment]
@finebel The SyncMenuButton file needs to be removed from the pbxproj as well, otherwise this won't build

Screen Shot 2022-03-04 at 3 07 40 PM

**Comment by finebel** [comment]
Sorry, I forgot to include this file in the commit. Will add it later.

**Pull request merged**
