### PR TITLE
Refactor FXIOS-9524 Update share icon with latest from Acorn

### PR DESCRIPTION
**Pull request by thatswinnie**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-9524)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/21082)

## :bulb: Description
Adds the new share icon, replaces the usage of the old icon and removes the old icon.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

## Screenshots
**Before**
Simulator Screenshot - iPhone 15 Pro Max - 2024-07-19 at 09 49 46
Simulator Screenshot - iPhone 15 Pro Max - 2024-07-19 at 09 49 51

**After**
Simulator Screenshot - iPhone 15 Pro Max - 2024-07-19 at 09 48 07
Simulator Screenshot - iPhone 15 Pro Max - 2024-07-19 at 09 48 11

### CODE REVIEW

**Comment by thatswinnie** [comment]
@cwzilla Could you please verify that this is indeed the correct share icon? Thx!

**Review by PARAIPAN9 — APPROVED** [review]

**Review by cyndichin — APPROVED** [review]

**Comment by thatswinnie** [comment]
Waiting for @cwzilla (on PTO) to take a look.

**Comment by cwzilla** [comment]
> Waiting for @cwzilla (on PTO) to take a look.

Looks good! Thank you.

**Review by isabelrios — APPROVED** [review]

**Comment by isabelrios** [comment]
General Bitrise is green, no need to retry, the test that failed automatically passed in a retry for Smoketest for focus

**Pull request merged**
