### PR TITLE
Bugfix FXIOS-8296 [v124] Fix data format issues for credit cards when autofilling

### PR DESCRIPTION
**Pull request by issammani**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-8296)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/18404)

## :bulb: Description
This PR:
- Stringifies payload data when autofilling 
- Enforces payload data shape for cc data for both autofill and capture cases.
- Modifies returned data from swift to return ints for `cc-exp-month` and `cc-exp-year`.
- Fixes ( screen recordings in the respective issues )
  - #18387 
  - #18373 
  - #18379  
  - #18239

#### :warning: NOTE
This solution will modify the payload into the shape swift expects right before sending it. Ideally we should have standard normalized record format between Desktop and iOS. This will be tackled in the future in  [FXCM-810](https://mozilla-hub.atlassian.net/browse/FXCM-810).

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] ~~Wrote unit tests and/or ensured the tests suite is passing~~
- [ ] ~~When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)~~
- [ ] ~~If needed I updated documentation / comments for complex code and public methods~~

### CODE REVIEW

**Review by nbhasin2 — APPROVED** [review]

**Comment by nbhasin2** [comment]
image
Test failures - Its because of how the formatting changed

**Comment by issammani** [comment]
>  Test failures - Its because of how the formatting changed

Oops missed that one. This is now fixed in https://github.com/mozilla-mobile/firefox-ios/pull/18406/commits/7ae51d804af1a1f4feb1cd8923b97ea6c156f10b. I ran the tests locally and it's all green now 😄 
Screenshot 2024-01-28 at 13 26 24

**Review by nbhasin2 — APPROVED** [review]

**Comment by nbhasin2** [comment]
https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/8ec37c73-d6e9-4d62-8202-15bd8c996df4

**Comment by nbhasin2** [comment]
@Mergifyio backport release/v123

**Pull request merged**
