### PR TITLE
Revert FXIOS-7151 [v116] Revert private mask icon update

### PR DESCRIPTION
**Pull request by thatswinnie**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7151)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/15900)

## :bulb: Description
This removes the `privateModeLarge` icon and restores the previously used icons.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Review by clarmso — APPROVED** [review]

**Comment by thatswinnie** [comment]
﻿﻿@mergifyio backport release/116

**Comment by lmarceau** [comment]
@thatswinnie the backport didn't work. Also, we should have one for 117 as well I think?

**Comment by thatswinnie** [comment]
https://github.com/Mergifyio backport release/v116

**Comment by thatswinnie** [comment]
@Mergifyio backport release/v117

**Pull request merged**
