### PR TITLE
Bugfix FXIOS-5955 [v116] Fix wrong selected passwords after filtering

### PR DESCRIPTION
**Pull request by FilippoZazzeroni**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-5955)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/13530)

### Description

Fixed the selection of passwords in the LoginListViewController, now the selection is based on the LoginRecord and not on the IndexPath.

### Pull requests checks where applicable
- [x] Fill in the three TODOs above (tickets number and description of your work)
- [x] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [x] Unit tests written and passing
- [x] Documentation / comments for complex code and public methods

### CODE REVIEW

**Review by yoanarios — COMMENTED** [review]
@FilippoZazzeroni thank you for the contribution, I tested the code and the bug is fix 🚀 but the build is failing because the test on `LoginsListSelectionHelperTests` needs to be updated to reflect the changes. Plus one nit comment

**Comment by FilippoZazzeroni** [comment]
Hi @yoanarios thank you. I'll update the unit tests and the comment you suggest.

**Comment by FilippoZazzeroni** [comment]
@yoanarios i saw the smoke ui test 3 failed, is it something related to my work ?

**Comment by yoanarios** [comment]
> @yoanarios i saw the smoke ui test 3 failed, is it something related to my work ?

I don't see any error related to the code, I'm running the failing workflow one more time 🤞

**Comment by FilippoZazzeroni** [comment]
@yoanarios thank you.

**Review by yoanarios — APPROVED** [review]

**Comment by FilippoZazzeroni** [comment]
I saw it. Perfect i'm happy that it succeeded.

**Pull request merged**
