### PR TITLE
Add FXIOS-21837 [Onboarding] Add opening iOS FX settings option in main onboarding flow

### PR DESCRIPTION
**Pull request by lmegviar**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/OMC-965)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/21837)

## :bulb: Description
- Add open-ios-fx-settings to the list of variants for the onboarding welcome card's primary button.
- Update the switch case in IntroViewController to handle the open-ios-fx-settings action.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [x] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
  _- No UI changes_
- [x] If needed, I updated documentation / comments for complex code and public methods
- [x] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by adudenamedruby** [comment]
Heya. Thanks so much for your contribution.

At the moment, we're of the stance that we want to limit what users can do on onboarding, and don't want actions without copy approved by product or design for onboarding there either. For this reason, I'm going to close the PR.

However, if you think there's a good reason to open the settings from the onboarding, I strongly encourage you to open a feature request so we can get it added with copy and appropriate images.

**Comment by adudenamedruby** [comment]
I saw the work brief. Nvm. lol. Not having context is sometimes confusing.

**Comment by afurlan-firefox** [comment]
@adudenamedruby is it possible to backport to 131? Do you see risk?

**Comment by adudenamedruby** [comment]
@Mergify backport release/v131

**Pull request merged**
