### PR TITLE
Localize FXIOS-11639 [v106] Remove obsolete strings

### PR DESCRIPTION
**Pull request by flodolo**
See #11639 for more details.

### CODE REVIEW

**Comment by lmarceau** [comment]
It looks like those strings could be removed for other locales as well (not just `en` and `en-US`). It's interesting since I've seen in the past strings that aren't anymore in the `Strings.swift` filed gets automatically removed from `.lproj` files by running the script. Or so would I think. I wonder why they didn't get removed.

**Comment by flodolo** [comment]
I didn't touch other locales because I would expect them to be cleaned up the first time we import strings after this merges.

These strings were in .strings files, not .swift, maybe that's part of the problem?

**Comment by flodolo** [comment]
Looking into adding more strings from the existing issue.

**Comment by flodolo** [comment]
This was quite a nightmare to clean up, please let's figure out a way to avoid leaving unused strings around in the future :-( 

Still no idea why some strings are in the .lproj folders for en/en-US, and others aren't.

Based on this list: https://gist.github.com/dnarcese/68503a0102192694e821c5fedbb95536
It would be useful to understand how that was created, since I've found at least one more string unused (SettingsTopSitesCustomizeTitle), so it's likely that there are more.

Removed (extra):
- SettingsTopSitesCustomizeTitle

These seem in use:
- TabTrayPrivateBrowsingTitle (Client/Frontend/Browser/Tabs/TabTrayViewModel.swift)
- PinTopsiteActionTitle2 (Client/Frontend/Home/HomepageContextMenuHelper.swift)
- UnpinTopsiteActionTitle2 (Client/Frontend/Home/HomepageContextMenuHelper.swift)

Already removed:
- LibraryPanel.History.SearchHistory
- LibraryPanel.History.SyncedHistory

**Review by yoanarios — APPROVED** [review]

**Comment by flodolo** [comment]
Thanks for the review, I'll need someone to merge it for me (double checked if this needs a rebase, but it should be clean).

**Pull request merged**
