### PR TITLE
Refactor FXIOS-9165 - Updated Fonts On SettingsViewController to FXFontStyles

### PR DESCRIPTION
**Pull request by tisumi99**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-9165)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/20308)

## :bulb: Description
Updated the settings views to use FXFontsStyle instead of DefaultDynamicFontHelper or UIFont. This eliminates the need to specify font sizes in the view controllers.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by tisumi99** [comment]
No change.
Screenshot 2024-05-17 at 10 56 11 AM

Originally set to font size 12 and styled as footnote, but FXFontStyles has footnote set to font size 13.
Screenshot 2024-05-17 at 10 56 59 AM

Originally set to font size 12 and styled as subheadline, but FXFontStyles has subheadline set to font size 15.
Screenshot 2024-05-17 at 10 59 30 AM

**Comment by tisumi99** [comment]
I updated the PR so that there are no changes to the UI now.  Was previously matching the orginal font style and `FXFontStyles` had a different size in some cases.  Now matching to font size instead.

**Comment by cyndichin** [comment]
> I updated the PR so that there are no changes to the UI now. Was previously matching the orginal font style and `FXFontStyles` had a different size in some cases. Now matching to font size instead.

thanks for the details @tisumi99, will let you know if any issues in matching the font size.

**Review by cyndichin — APPROVED** [review]
thank you for picking up the standardize font tickets and providing screenshots @tisumi99! this helps greatly, appreciate it :)

**Pull request merged**
