### PR TITLE
RELENG-814 - Pull taskgraph from pypi

### PR DESCRIPTION
**Pull request by hneiva**
Update to .taskcluster.yml
Makes it so it pulls taskgraph from pypi instead of HG repo, with versioning via `taskcluster/requirements.txt`

### CODE REVIEW

**Review by Stanislav1975 — APPROVED** [review]

**Comment by isabelrios** [comment]
@hneiva, doble checking..we already use taskcluster for this project as a task orchestator and a place to store artifacts working together with our CI system, Bitrise. Just a heads up and to be sure that the changes in this PR are not going to break anything within that environment.

**Comment by hneiva** [comment]
> @hneiva, doble checking..we already use taskcluster for this project as a task orchestator and a place to store artifacts working together with our CI system, Bitrise. Just a heads up and to be sure that the changes in this PR are not going to break anything within that environment.

@isabelrios Releng is working on improving the delivery of taskgraph to all projects, this update shouldn't change any task behavior as far as the application is concerned.
All it's doing is moving the source of taskgraph code from [hg](https://hg.mozilla.org/ci/taskgraph) to [pypi](https://pypi.org/project/taskcluster-taskgraph/) + some minor refactoring on .taskcluster.yml

**Review by ahal — APPROVED** [review]
Thanks!

**Comment by ahal** [comment]
Hello @isabelrios or @Stanislav1975, could one of you merge this on our behalf? Looks like we don't have permission.

**Pull request merged**
