### PR TITLE
FXIOS-1258 ⁃ Add 83.0 tracking protection list

### PR DESCRIPTION
**Pull request by say-yawn**
# About this PR
Update the Tracking Protection lists

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1258)

### CODE REVIEW

**Review by dnarcese — APPROVED** [review]

**Comment by dnarcese** [comment]
Getting the error `Could not cast value of type '__NSDictionaryI' (0x7fff91249168) to 'NSArray'`.
@say-yawn any idea what changed that would cause this?

**Comment by say-yawn** [comment]
If I understood the error message properly, it seems to me the iOS parsing script is trying to set the values of some data as dictionary when it is an array. I wonder if this has anything to do with the entity-list parsing? Since the last time the Shavar lists were updated (the change is referencing that you all were pulling from this commit https://github.com/mozilla-services/shavar-prod-lists/commit/1f282be9bc7bf86cf4d695e2a63dbcdf2eecfb89) the entity list's structure changed as mentioned in this PR https://github.com/mozilla-services/shavar-prod-lists/pull/235

**Comment by dnarcese** [comment]
Yup, that structure change is probably the problem. I'll take a look at updating our parsing scripts.

**Comment by nbhasin2** [comment]
I have made a follow-up PR which has some changes that addresses build failure and also updates to latest prod list

https://github.com/mozilla-mobile/firefox-ios/pull/7710

Cc @dnarcese @say-yawn

**Pull request closed without merging**
