### PR TITLE
Bugfix FXIOS-4447 [v108] Homepage is no longer displayed in the same tab after +4 hours

### PR DESCRIPTION
**Pull request by nbhasin2**
[Jira](https://mozilla-hub.atlassian.net/browse/FXIOS-4447)
[Github](https://github.com/mozilla-mobile/firefox-ios/issues/11095)

### CODE REVIEW

**Comment by nbhasin2** [comment]
@thatswinnie can you try this and let me know if you are still seeing the bug, this is a bit tricky to test but you have had the most success with it

**Review by thatswinnie — APPROVED** [review]

**Comment by thatswinnie** [comment]
@nbhasin2 it works!

**Comment by nbhasin2** [comment]
cc @dnarcese want this in v107?

**Comment by dnarcese** [comment]
Lets leave it for 108

**Comment by nbhasin2** [comment]
image

**Pull request merged**
