### PR TITLE
Bugfix FXIOS-10696 Dismiss search bar when tap on the outside view in HistoryPanel

### PR DESCRIPTION
**Pull request by gokulvenkat243**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-10696)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/23379)

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by ih-codes** [comment]
Hi @gokulvenkat243! Thank you for your contribution. 🙏 

I took a quick look at your PR. Your code does helpfully close the HistoryPanel's search bar, but I think we should also account for closing the keyboard with this solution (see video below for the problem).

You can try calling `searchbar.resignFirstResponder()` instead of calling it on the `bottomStackView`. You can test in the simulator by making sure you have the software keyboard enabled.

https://github.com/user-attachments/assets/3d46d8fe-61d9-4f79-bba0-ebaac498fb3d

**Review by ih-codes — APPROVED** [review]
Thanks @gokulvenkat243 ! Looks good.

I will get this merged in on Monday. 👍

**Comment by ih-codes** [comment]
Just closing briefly to get Bitrise to update.

**Comment by ih-codes** [comment]
Some unrelated CI tests are failing in the pipeline. @gokulvenkat243 Can you please rebase on the latest main for Bitrise? 🙏  Thanks!

**Comment by ih-codes** [comment]
Thanks for that change! You can also safely remove your tab gesture code now, I believe the cancel button will accomplish the same need. 🙏

**Comment by ih-codes** [comment]
Thanks @gokulvenkat243 for your changes, this has been merged! 🥳

**Comment by gokulvenkat243** [comment]
Thanks for your help @ih-codes ❤️

**Pull request merged**
