### PR TITLE
Bug 1228087 - Build a custom UIView to use as a notification when the user enters the app with a url on their clipboard 

### PR DESCRIPTION
**Pull request by Bunn**
Bugzilla URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1228087
This PR adds a custom view that allows users to go to a URL that's saved on the user's clipboard.

### CODE REVIEW

**Comment by farhanpatel** [comment]
Hey @Bunn Thanks for the PR. This is very useful feature! And one thats been lacking for a while. Do you think it would be simplier to use the existing Toast UI we already have. Similar to what is done in this PR? https://github.com/mozilla-mobile/firefox-ios/pull/2358

**Comment by Bunn** [comment]
@farhanpatel good question, I wasn't aware of this component, I'll take a look to see if it's easier to use "ButtonToast" since it's already there, thanks for the feedback 👍

**Comment by Bunn** [comment]
@farhanpatel Using the "ButtonToast" will require some changes on this component, so I'd like your opinion before doing anything:

- ButtonToast does not accept a subtitle, this will need to be added.
- ButtonToast always handles the tap gesture and removes itself from the hierarchy with an animation, which might lead to some situations like this:
(There are 2 videos here, toastAnimation is the situation using the ButtonToast, barAnimation is the current state of this PR)
[Archive.zip](https://github.com/mozilla-mobile/firefox-ios/files/740873/Archive.zip)

I'm not sure how to solve this using ButtonToast without changing it a considerable amount. Maybe it could have a protocol that could override the animations and the parent view could do whatever is best for this scenario. But since ButtonToast tries to handle itself automatically, it could conflict with some other situations, like the attached video.

Thanks.

**Comment by farhanpatel** [comment]
I think it makes sense to extend the existing ButtonToast. As long as the API for the simple use cases doesn't get complicated (use default values, multiple init methods etc) It would be great to have an extensible Toast class inside the browser which we could use where ever we need it.

**Comment by farhanpatel** [comment]
Also on the team we use Snapkit. To make things consistent can you please use Snapkit for the constraints.  

To avoid the animation issue. You can hide the toast before you animate away from the tab. That way avoiding the issue. Or you can create a parameter (that defaults to the window) to specify which view to show the Toast on.

**Comment by Bunn** [comment]
@farhanpatel I removed the ClipboardBar in favor of the ButtonToast and removed it from the superview in special cases to avoid animation conflicts like you suggested.

**Comment by farhanpatel** [comment]
Thanks for this PR! We just finished a major migration to swift 3.0 making merging in most patches pretty difficult. If you feel like this patch is still important please feel free to update your PR to swift 3 and reopen this PR 😄

**Pull request closed without merging**
