### PR TITLE
Refactor FXIOS-7478 [v120] Allow Xcode to use native M1 simulators

### PR DESCRIPTION
**Pull request by skhamis**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7478)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/16601)

## :pencil: Checklist
You have to check all boxes before merging
- [ ] Filled in the above information (tickets numbers and description of your work)
- [ ] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by skhamis** [comment]
@clarmso This is what will enable us to fix the issues outlined in https://docs.google.com/document/d/1VTm58d8vCj7_HaybrbwIJBuPPgRUrfdRBKKvEbWPYpE/edit#heading=h.u9tqjn7fjge0

**Review by yoanarios — APPROVED** [review]
LGTM, tagging @nbhasin2 for a second pair of 👀

**Review by isabelrios — APPROVED** [review]
🚀

**Comment by clarmso** [comment]
🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀

**Review by clarmso — APPROVED** [review]

**Comment by clarmso** [comment]
> LGTM, tagging @nbhasin2 for a second pair of 👀

@yoanarios Agree. I'd have another iOS developer to take a look before I merge this PR.

**Comment by clarmso** [comment]
@isabelrios The command `processIsTranslatedStr()` now returns `native` instead of `m1Rosetta`. Let me check the tests that have been disabled for M1. Please don't merge this PR yet.

**Comment by skhamis** [comment]
Feel free to commandeer this PR if it makes things easier! This was mainly me tying up the final end of the M1 saga but if there needs to be more discussion on the FxiOS side of things or if there needs more work i'm happy to hand this off.

**Comment by clarmso** [comment]
@isabelrios I suggest that we remove the "Intel vs Rosetta" code. In addition, some steps needs some more waiting (example: `testDeleteLogin()`).

Should I apply this patch in a separate PR? I afraid that this PR becomes too large.

[no_rosetta.patch](https://github.com/mozilla-mobile/firefox-ios/files/12745458/no_rosetta.patch)

**Comment by nbhasin2** [comment]
This is great as I recall we did this for maximum compatibility however removing excluded architectures means we can support both M1 (arm64) and no change for Intel.

**Review by nbhasin2 — APPROVED** [review]

**Comment by isabelrios** [comment]
> @isabelrios I suggest that we remove the "Intel vs Rosetta" code. In addition, some steps needs some more waiting (example: `testDeleteLogin()`).
> 
> Should I apply this patch in a separate PR? I afraid that this PR becomes too large.
> 
> [no_rosetta.patch](https://github.com/mozilla-mobile/firefox-ios/files/12745458/no_rosetta.patch)

Since we are running all our tests now on M1 on CI, I would say to address those test issues related to Intel in a different PR. Only people running certain tests on their Intel machines will be affected while we update them. Tests are green here, we can unblock this and work on a follow up to fix / update what's needed from our side @clarmso

**Comment by isabelrios** [comment]
Since this is approved by everyone here, I'm merging this... I would like to monitor this and so plan the work that we may need to do as a follow up. Hope this is fine! Thank you all for your work on this!! 🙏

**Pull request merged**
