### PR TITLE
FxIOS-8147 - Add telemetry to app and page menus

### PR DESCRIPTION
**Pull request by electricRGB**
This adds telemetry events to the page and the app menus.

Telemetry is a complex subject. I've put a plan in place to overhaul how we record telemetry. However, after talking to Data Engineering, Product, Jeremy, etc., I've decided that to properly execute that plan, we'd need more time. This will be done in [this ticket](https://jira.mozilla.com/browse/FXIOS-1748) at some point later in time.

For now, we're gonna go with the standard way we've normally gone with.

A note on some of the events: after speaking with Ashley and what she'd prefer, we went with separate counters for togglable events, rather than value events.

### CODE REVIEW

**Comment by electricRGB** [comment]
# Request for data collection review form 
1. What questions will you answer with this data?
	* How many users access different the different items in the Page and App menus

2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:
	* It will provide information essential for understanding importance of the various items, what's important to users, and prioritize future work based on it

3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
	* No other way to collect this data

4. Can current instrumentation answer these questions?
	* No, we didn't have events for many of these new items 

5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki.

Measurement Description | Data Collection Category | Tracking Bug # |
| --- | ----- | ----- |
Counts the number of times a specific item in the Page Menu is interacted with | 2 | https://github.com/mozilla-mobile/firefox-ios/pull/8394
Counts the number of times a specific item in the App Menu is interacted with | 2 | https://github.com/mozilla-mobile/firefox-ios/pull/8394

6. How long will this data be collected? Choose one of the following:
	* I want this data to be collected for 6 months initially (potentially renewable).

7. What populations will you measure?
All countries and channels that have data collection on.

8. If this data collection is default on, what is the opt-out mechanism for users?
	* Toggle switch for 'Send Usage Data' in the app settings.

9. Please provide a general description of how you will analyze this data.
	* By monitoring the count of how often users are performing these actions.

10. Where do you intend to share the results of your analysis?
	* With the mobile team.

11. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so:
	* No.
	
Documentation has been updated in this PR and will be reflected in our [metrics.md](https://github.com/mozilla-mobile/firefox-ios/blob/main/Docs/metrics.md) file

**Comment by dnarcese** [comment]
r+
# Data Review Form

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Yes, telemetry is documented in `docs/metrics.md`

2) Is there a control mechanism that allows the user to turn the data collection on and off? 

Yes, Firefox iOS provides data controls in the app settings

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

This should be re-reviewed w/ Ashley Thomas every 6mo

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Type 2

5) Is the data collection request for default-on or default-off?

Default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

No

7) Is the data collection covered by the existing Firefox privacy notice? 

Yes

8) Does there need to be a check-in in the future to determine whether to renew the data? (Yes/No) (If yes, set a todo reminder or file a bug if appropriate)**

Should review all probes for necessity every 6mo

9) Does the data collection use a third-party collection tool? 

No

**Review by dnarcese — APPROVED** [review]
Just need to change the pull request links!

**Comment by dnarcese** [comment]
Oh also if you pulled in the menus, the Library is now split into each of the panels. Should a add telemetry for those buttons

**Comment by electricRGB** [comment]
@dnarcese I added back the Telemetry events that we had in the previous build, so they'll be the same. I did not add new stuff because I don't know if we want to/we should not keep increasing scope/we should do that when we properly do a telemetry overhaul so we don't have even more things we have to remap.

**Pull request merged**
