### PR TITLE
#FX-9003 Landscape full width library panel

### PR DESCRIPTION
**Pull request by junbio**
This PR makes the library panel full width in landscape on iOS devices with a screen cutout. (#9003)

Before: 
Simulator Screen Shot - iPhone 13 Pro - 2022-01-25 at 08 51 09

After:
simulator_screenshot_1306FFBD-1E66-47AB-8C14-80DAF3A2C23A

### CODE REVIEW

**Comment by lmarceau** [comment]
Build passed but didn't update here: https://app.bitrise.io/build/1aa1ab3d-d119-4992-a29c-d92ce0492fe3#?tab=log

Screen Shot 2022-01-25 at 3 33 23 PM

**Comment by junbio** [comment]
Thanks for the feedback as always @lmarceau! What are your thoughts about the separator size changing between the two?

**Comment by nishant2718** [comment]
hey @junbio! The PR looks good. Just checking on iPad to make sure everything's fine there as well. Just wondering, how does that change in SiteTableVC help here?

**Comment by junbio** [comment]
> hey @junbio! The PR looks good. Just checking on iPad to make sure everything's fine there as well. Just wondering, how does that change in SiteTableVC help here?

Thanks! As for SiteTableVC, if you're talking about the header, it's because the contentView gets cut off by the safe area and backgroundView would fit the entire width. If you're talking about the reverted commit, I wanted to restore the original separator inset as before, but since the table view inserts an additional inset, it becomes different. For what it's worth, the separator inset is the same as the autocomplete suggestion in landscape.

**Comment by nishant2718** [comment]
Cool! Thanks for explaining it. I'll do a couple sanity checks and then move forward with this PR. Thanks again for the contribution! 👏

**Review by nishant2718 — APPROVED** [review]

**Pull request merged**
