### PR TITLE
Bugfix FXIOS-5934 [v112] ETP options are grayed out if they are disabled

### PR DESCRIPTION
**Pull request by whitelips**
https://mozilla-hub.atlassian.net/browse/FXIOS-5934
#13485

### CODE REVIEW

**Comment by mte-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Project coverage: 30.22%</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Edited 1 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 0 files</td>
    </tr>
  </tbody>
</table>

## Client.app: Coverage: 27.12
| File | Coverage ||
| --- | --- | --- |
ContentBlockerSettingViewController.swift | 0.0% | ⚠️

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 71905ff458ff990b524a0373f4f80e606976e984
</p>

**Comment by thatswinnie** [comment]
Thanks so much for fixing this bug @whitelips !

**Review by thatswinnie — APPROVED** [review]

**Comment by thatswinnie** [comment]
Build passed
Screenshot 2023-03-10 at 14 23 11

**Comment by thatswinnie** [comment]
@Mergifyio backport release/v111.0

**Pull request merged**
