### PR TITLE
Remove FXIOS-6738 [v122] Remove search highlights feature flag

### PR DESCRIPTION
**Pull request by lmarceau**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-6738)
No Github issue

## :bulb: Description
Remove search highlights feature flag, enabling them by default.

## :pencil: Checklist
You have to check all boxes before merging
- [X] Filled in the above information (tickets numbers and description of your work)
- [X] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [X] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by dnarcese** [comment]
Hm this was default off before right? I will need to do more investigation before turning this on.

**Comment by lmarceau** [comment]
@dnarcese Oups, yes you're right. Ok I'll mark this as do not merge for now!

**Review by adudenamedruby — APPROVED** [review]

**Comment by lmarceau** [comment]
@dnarcese Maybe we'll need then to turn the search highlights feature ON and keep this flag still for a couple of releases? Let me know what is best.

**Comment by dnarcese** [comment]
Can we just leave it as it was before until a decision is made?

**Pull request closed without merging**
