### PR TITLE
Refactor FXIOS-9265 - Decreased Spacing Between Site Title & URL on TwoLineImageOverlayCell

### PR DESCRIPTION
**Pull request by tisumi99**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-9265)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/20512)

## :bulb: Description
Decreased spacing between `titleLabel` and `descriptionLabel` on `TwoLineImageOverlayCell` from 8 to 4.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by tisumi99** [comment]
Screenshot 2024-06-03 at 11 31 40 AM

**Comment by OrlaM** [comment]
cc @cwzilla for design review.

**Comment by cwzilla** [comment]
@tisumi99 Thanks so much for the screenshot. Is it possible to see what it would look like with 2 spacing?

**Comment by tisumi99** [comment]
@cwzilla Screenshots at 8, 4, and 2 spacing.  Please let me know if I should change the code to 2 spacing.

Screenshot 2024-06-07 at 9 41 05 AM

**Comment by cwzilla** [comment]
Thank you for the screenshots @tisumi99. Can we go with 2 spacing? Also, just curious what is the font styles used for the site name and URL?

**Comment by tisumi99** [comment]
> Thank you for the screenshots @tisumi99. Can we go with 2 spacing? Also, just curious what is the font styles used for the site name and URL?

Code updated to 2 spacing.

Site name is callout regular at 16.
URL is subheadline regular at 15.

**Comment by cwzilla** [comment]
> > Thank you for the screenshots @tisumi99. Can we go with 2 spacing? Also, just curious what is the font styles used for the site name and URL?
> 
> Code updated to 2 spacing.
> 
> Site name is callout regular at 16. URL is subheadline regular at 15.

Thanks! Can we update the site name to body?

**Comment by tisumi99** [comment]
Sure, site name is now set to body.
Screenshot 2024-06-13 at 2 21 18 PM

**Comment by cwzilla** [comment]
@tisumi99 Thanks so much for the quick changes!!

**Review by cwzilla — APPROVED** [review]

**Review by OrlaM — APPROVED** [review]
Thanks for the contribution! 🙏

**Pull request merged**
