### PR TITLE
Bugfix FXIOS-6451 [v115] ZoomPageBar shadow's overlays UrlBar

### PR DESCRIPTION
**Pull request by FilippoZazzeroni**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-6451)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/14506)

### Description
Fixed ZoomPageBar shadow's overlays UrlBarView when the position of the UrlBar is set to bottom

### Pull requests checks where applicable
- [x] Fill in the three TODOs above (tickets number and description of your work)
- [x] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [ ] Unit tests written and passing
- [x] Documentation / comments for complex code and public methods

### UrlBar position bottom

Simulator Screenshot - iPhone 14 Pro - 2023-05-30 at 10 27 59

### UrlBar position top

Simulator Screenshot - iPhone 14 Pro - 2023-05-30 at 10 27 29

### CODE REVIEW

**Comment by PARAIPAN9** [comment]
Hi @FilippoZazzeroni, thank you for your PR. After I tested your changes, I encountered a strange behavior while scrolling. There is a gap between the gradient shadow and the urlBar, because of that constant so a better approach would be to make the constraint dynamic. Here's the video:

https://github.com/mozilla-mobile/firefox-ios/assets/51127880/d02bb888-5158-4258-8735-aaeffd86ad12

**Comment by FilippoZazzeroni** [comment]
Hi @PARAIPAN9 thank you, i will fix it with a dynamic constraint.

**Comment by FilippoZazzeroni** [comment]
Hi @PARAIPAN9 I've fixed the error during the scroll of the ZoomPageBar, now it should work correctly. 
Let me know. Thank you.

**Comment by PARAIPAN9** [comment]
Hi @FilippoZazzeroni, thank you again for your effort. For the moment, we'll keep this PR pending because today we will have a UX meeting, and I think they will want to present the zoom bar on top of the URL bar. We'll see. Thank you again.

**Comment by FilippoZazzeroni** [comment]
Ok @PARAIPAN9 no problem at all, let me know what they decide, thank you.

**Comment by lmarceau** [comment]
Hey @FilippoZazzeroni, it was decided to move the zoom page bar on top of the URL bar (with https://github.com/mozilla-mobile/firefox-ios/issues/14717). This means this bug and ticket will be closed because of that reason. Thanks a lot for your work!

**Pull request closed without merging**
