### PR TITLE
Bugfix 1819036 [v112] Get mergify config on par with firefox-android

### PR DESCRIPTION
**Pull request by JohanLorenzo**
[1819036](https://bugzilla.mozilla.org/show_bug.cgi?id=1819036)
This PR makes the current `.mergify.yml` file similar to https://github.com/mozilla-mobile/firefox-android/blob/457d88002e0dd413725fb1f99033c6ccc3a65e58/.mergify.yml

I changed the Github labels to match this repo. I also checked the `regex` for the `.strings` files. I see Mergify is already active (e.g. https://github.com/mozilla-mobile/firefox-ios/pull/10998) so we don't need to do anything but making changes to `.mergify.yml`.

### CODE REVIEW

**Comment by rvandermeulen** [comment]
@jevans-mozilla Do you want someone from your team to look this over also?

**Review by OrlaM — APPROVED** [review]
LGTM 👍

**Comment by lmarceau** [comment]
[Build is green](https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/b0390e0f-5708-48de-816c-fde96a72366d)

**Comment by isabelrios** [comment]
@JohanLorenzo @lmarceau Please let me share this [doc](https://docs.google.com/document/d/1vv5NdMulVM1RfaYZsmHqSXpRRtdbGRV1na5RJfGJQjU/edit#) with the exploration I did to add mergify as it is on andorid or focus-iOS... 
Due to the way firefox-iOS works on Bitrise as a public app, there is no way we can automatically approve PRs. Unfortunatelly we can not benefit completely from using mergify :(

**Comment by JohanLorenzo** [comment]
Thanks for calling this out, @isabelrios! I read the doc. I'm not sure what's preventing Bitrise from rebuilding a PR after rebase. Is it its default behavior or is it the way we configured it?

**Comment by isabelrios** [comment]
> Thanks for calling this out, @isabelrios! I read the doc. I'm not sure what's preventing Bitrise from rebuilding a PR after rebase. Is it its default behavior or is it the way we configured it?

It is how firefox-ios is configured on Bitrise. On public apps PRs can not start without approval. So we would need to manually trigger them to run via the Bitrise UI. That's something we may be able to change if we use taskcluster to start the builds... ;)

**Pull request merged**
