### PR TITLE
Bugfix #9837 [v98] Fix minor warnings and update count

### PR DESCRIPTION
**Pull request by lmarceau**
# Issue #9837
- Fix minor warnings
- Update bug count

I'll adjust to the new count once BR passes

### CODE REVIEW

**Comment by isabelrios** [comment]
Oh Bitrise failed for 1 extra warning:
```
[[ Number of warnings is:      424. This is greater than build threshold: 423 == *\g\r\e\a\t\e\r* ]]
echo 'Failure, the number of warnings increased'
Failure, the number of warnings increased
 exit 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Detect number of warnings (exit code: 1)                      | 3.07 sec |
```

Once that is adjusted, this is ready to land! thanks!

**Comment by lmarceau** [comment]
@isabelrios This just failed 🤔https://mozilla.slack.com/archives/CAFC45W5A/p1643042848025100

Screen Shot 2022-01-24 at 11 51 38 AM
 
It should pass while being equal no?

**Comment by isabelrios** [comment]
> @isabelrios This just failed 🤔https://mozilla.slack.com/archives/CAFC45W5A/p1643042848025100
> 
> Screen Shot 2022-01-24 at 11 51 38 AM
> 
> It should pass while being equal no?

Oh I said greater or equal would fail... https://github.com/mozilla-mobile/firefox-ios/blob/d73a1479558cf7f6d838957861c633243dc2952a/test-fixtures/generate-metrics.sh#L14
But feel free to modify that as just greater than..

**Comment by lmarceau** [comment]
@isabelrios Ahh I see! Let's keep it that way, I just had a different understanding - but one way or the other is fine by me. I'll adjust my count :) Thanks!

**Review by isabelrios — APPROVED** [review]
LGTM!

**Pull request merged**
