### PR TITLE
Bump FXIOS [Dependencies] Glean v63.0.0 & AppServices v135.0.20241212150752

### PR DESCRIPTION
**Pull request by travis79**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-TODO)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/TODO)

## :pencil: Checklist
You have to check all boxes before merging
- [ ] Filled in the above information (tickets numbers and description of your work)
- [ ] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Review by adudenamedruby — APPROVED** [review]

**Comment by adudenamedruby** [comment]
BR failure with the following error:

Screenshot 2024-12-05 at 9 11 17 AM

**Comment by travis79** [comment]
> BR failure with the following error:
> Screenshot 2024-12-05 at 9 11 17 AM

The looks like a transient error, all of the other tasks were able to install and run the glean_parser without issue.

**Comment by adudenamedruby** [comment]
hmmmm. Let's rerun it. It's likely BR being.. well, you know, BR. lolololo

**Comment by travis79** [comment]
Something must be borked with this...  let me take another look at this and push up a fix

**Comment by adudenamedruby** [comment]
Lemme know if you need any halps :)

**Pull request merged**
