### PR TITLE
Bugfix FXIOS-5764 [v112] The first tab in private mode is wrong

### PR DESCRIPTION
**Pull request by CatalinNeculaide**
[Jira ticket for reference](https://mozilla-hub.atlassian.net/browse/FXIOS-5764)
https://github.com/mozilla-mobile/firefox-ios/issues/13233

https://user-images.githubusercontent.com/16647663/224014352-ef717d22-f1cb-4c74-a982-fb2a11a89981.mp4

### CODE REVIEW

**Comment by mte-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Project coverage: 30.2%</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Edited 1 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 0 files</td>
    </tr>
  </tbody>
</table>

## Client.app: Coverage: 27.12
| File | Coverage ||
| --- | --- | --- |
TopTabsViewController.swift | 0.0% | ⚠️

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against b9d2c67518f260e6f667d4fb067a721d0f0d485d
</p>

**Comment by nbhasin2** [comment]
I am not fully convinced with using `delay` as adding delays without reason is not the best idea 😞
wondering if there is a better way. Let's sync offline and see if we can come up with a better solution 😄 🤞🏼

**Review by OrlaM — APPROVED** [review]
LGTM

**Review by nbhasin2 — APPROVED** [review]

**Comment by thatswinnie** [comment]
@Mergifyio backport release/v111.0

**Comment by DonalMe** [comment]
@thatswinnie @yoanarios sorry for the double tag not sure the process who does it when you backport to release but it's also needed in beta. 
This PR was backported to 111, but not in 112

**Comment by yoanarios** [comment]
thank you @DonalMe I will backport to v112

**Pull request merged**
