### PR TITLE
Focus ios prep 124 manual

### PR DESCRIPTION
**Pull request by isabelrios**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-TODO)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/TODO)

## :bulb: Description

PR to add the monorepo changes to release branch v124

## :pencil: Checklist
You have to check all boxes before merging
- [ ] Filled in the above information (tickets numbers and description of your work)
- [ ] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by lmarceau** [comment]
> Not sure why swiftlint is failing in firefox-ios folders and files 🤔

I'm not sure, but I saw this on other PRs as well. There's a Swiftlint issue in our CI, trying to determine what's the cause. See thread [here](https://mozilla.slack.com/archives/C05C9RET70F/p1709680041367889)

**Comment by isabelrios** [comment]
> > Not sure why swiftlint is failing in firefox-ios folders and files 🤔
> 
> I'm not sure, but I saw this on other PRs as well. There's a Swiftlint issue in our CI, trying to determine what's the cause. See thread [here](https://mozilla.slack.com/archives/C05C9RET70F/p1709680041367889)

In this case the PR did not run on CI, it is the firefox swiftlint we had in place not the new one in focus, which fails in github but not the build... investigating...

**Comment by isabelrios** [comment]
@adudenamedruby ping you as the swiftlint expert... any idea about changes in 124 that we may be missing in swiftlint file or why would we have these errors? Thanks!

**Comment by lmarceau** [comment]
@isabelrios I think I know for the Swiftlint failure! The focus folder is not excluded folder as it is on `main` in the `.swiftlint.yml`

**Comment by isabelrios** [comment]
> @isabelrios I think I know for the Swiftlint failure! The focus folder is not excluded folder as it is on `main` in the `.swiftlint.yml`

I thought that, but the failures are in firefox path.. 🤔

**Comment by lmarceau** [comment]
That's not what I see when I click on the BR, seems to be under focus folder

Screenshot 2024-03-06 at 10 37 28 AM

**Comment by isabelrios** [comment]
> That's not what I see when I click on the BR, seems to be under focus folder. At least it won't hurt for sure to ignore it in this branch as well, since we know the Focus app isn't ready to have Swiftlint enabled
> 
> Screenshot 2024-03-06 at 10 37 28 AM

oh that would make sense for sure.. I was clicking in the swiftlin link here in github, there are a few for firefox, not not all

**Pull request merged**
