### PR TITLE
Refactor FXIOS-8012 [V123] Fix closeButton warnings in TabCell and in LegacyTabCell.

### PR DESCRIPTION
**Pull request by Prathameshchakote**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-8012)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/17883)

## :bulb: Description

issue-17883 Removed imageEdgeInsets deprecated Code and added imagepadding and contentInsets of same size as previous.  LegacyTabCell has same warning hence make the same code update in LegacyTabCell as well. 

## :pencil: Checklist
You have to check all boxes before merging
- [X] Filled in the above information (tickets numbers and description of your work)
- [X] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

**Before Changes:**

Screenshot 2024-01-05 at 10 21 37
Screenshot 2024-01-05 at 10 22 19

**After Changes:**

Screenshot 2024-01-05 at 10 49 53
Screenshot 2024-01-05 at 10 50 04

### CODE REVIEW

**Review by adudenamedruby — APPROVED** [review]

**Comment by adudenamedruby** [comment]
Heya. Thanks so much for your work. Before I can merge this, would you kindly add before/after screenshots of the appropriate UI for this? Generally, we want to see screenshots of the UI, and not the code changes, so that we can see how the UI is affected by the code changes. The code changes will be in the PR anyway, so there's no need to screenshot those. :)

**Comment by Prathameshchakote** [comment]
Hi @adudenamedruby ,
Thanks for letting me know. Right now I am facing issues while building the Project. I have chosen **"Fennec"** target to build. Should I select a different target?
Thanks

**Comment by adudenamedruby** [comment]
wow, I didn't get a notification you said this. My apologies.

Yeah, "Fennec" should be the scheme you'd be building.

**Comment by adudenamedruby** [comment]
No updates on this. Integrated changes in [this PR](https://github.com/mozilla-mobile/firefox-ios/pull/18576)

**Pull request closed without merging**
