### PR TITLE
Bug 1305895 - Include sender client GUID in sent displayURI commands.

### PR DESCRIPTION
**Pull request by rnewman**
This passes the test, but I haven't manually tested. Figured it was worth throwing up the PR anyway… @sleroux, take a look?

### CODE REVIEW

**Comment by sleroux** [comment]
@rnewman I was trying to test this but ran into https://bugzilla.mozilla.org/show_bug.cgi?id=1309581 😢 Assuming that will work, what's the best way to verify this? Should I see a native notification on desktop about the tab being sent + which device it came from?

**Comment by rnewman** [comment]
STR:

- Send two tabs from iOS to desktop.

Current:

- "2 tabs received from ." is displayed.

Expected:

- The iOS device name is shown instead of the empty string.

**Comment by rnewman** [comment]
Wanna try to get this in for 6.0, @sleroux?

**Comment by sleroux** [comment]
Yup. I'll update the bug to be in 6.0+.

**Comment by ryanfeeley** [comment]
@rnewman I still don't get iOS device names on tabs received on desktop. Is this the issue?

**Comment by rnewman** [comment]
@ryanfeeley This fixed an issue just like that, yes. If you're _still_ seeing that issue, and you're using a recent Firefox for iOS, it's probably something else — for example, if desktop is using the FxA device record instead of the Sync client record, and the sender doesn't have an FxA device registration, then the lookup will fail.

Worth filing a bug and CCing @eoger and the usual folks. It should be very easy to figure out what's going wrong simply by looking at desktop.

**Comment by ryanfeeley** [comment]
@rnewman Probably one of the things I should be doing is improving my dogfooding experience by deleting my FxA once is a while and recreating the set-up with a different email.

**Pull request merged**
