### PR TITLE
Refactor FXIOS-9382 - Update Fonts related to Wallpaper to use FXFontStyles

### PR DESCRIPTION
**Pull request by kuzeng**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-9382)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/20770)

## :bulb: Description
This PR replaces the usage of DefaultDynamicFontHelper with FXFontStyles for `WallpaperSelectorViewController`.

Before:

After:

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by ih-codes** [comment]
Thank you for your PR @kuzeng ! Looking good. Right now we are trying to preserve the current UI appearance while standardizing fonts. Could you please change the `instructionLabel` to use the `caption1` (size 12) font instead of the `body` (size 17) font?

(I have made a [separate task](https://github.com/mozilla-mobile/firefox-ios/issues/21269) for one of our designers to take a second look this once they're back in the office, as `body` does, however, seems to make more semantic sense.)

**Comment by kuzeng** [comment]
> Thank you for your PR @kuzeng ! Looking good. Right now we are trying to preserve the current UI appearance while standardizing fonts. Could you please change the `instructionLabel` to use the `caption1` (size 12) font instead of the `body` (size 17) font?
> 
> (I have made a [separate task](https://github.com/mozilla-mobile/firefox-ios/issues/21269) for one of our designers to take a second look this once they're back in the office, as `body` does, however, seems to make more semantic sense.)

Hi @ih-codes , thanks for the quick feedback! I have made the new change

**Review by ih-codes — APPROVED** [review]
Great, thank you @kuzeng for the contribution! 🙏  I'll try to get this merged today once our Bitrise tests are passing.

**Comment by kuzeng** [comment]
> Great, thank you @kuzeng for the contribution! 🙏 I'll try to get this merged today once our Bitrise tests are passing.

I appreciate it @ih-codes. Happy to make my first contribution to this community!

**Pull request merged**
