### PR TITLE
Bump Glean v51.0.1 [v105]

### PR DESCRIPTION
**Pull request by badboy**
third time's the charm.

#11392 and #11393 wrapped up together + Glean v51.0.1 with an important bugfix.

cc @tarikeshaq

### CODE REVIEW

**Comment by badboy** [comment]
I can't see the bitrise failure I think. At least clicking on the "Details" link here doesn't get me there.

**Comment by lmarceau** [comment]
> I can't see the bitrise failure I think. At least clicking on the "Details" link here doesn't get me there.

The build wasn't started yet (they don't start automatically unless approved). I just started it, let's see if it's green ✅

**Comment by lmarceau** [comment]
Build is green [here](https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/055df2ab-110b-470c-93af-46a60fb2d6ca)

Screen Shot 2022-07-26 at 10 43 15 AM

**Comment by badboy** [comment]
Can we land this?

**Comment by lmarceau** [comment]
I could build this locally, all looks good IMO

**Pull request merged**
