### PR TITLE
Fix #5315 - XCUITests fix intermittent failures Smoketest Parallel iPad

### LINKED ISSUE #5315: FXIOS-122 ⁃ [XCUITests] Fix intermittent failures on iPad - parallel testing
As a follow up of issue #5260 we have to fix similar problems when tests run on iPad.

The tests that are failing very often are mainly these:
-testAddTabFromTabTray()
-testCloseAllTabsPrivateModeUndo()
-testSearchTabs()

There may be more tests added to the list as we identify them as frequent failures

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2151)

### PR DESCRIPTION
**Pull request by isabelrios**
This PR tries to fix #5315 so that there are not false failures

### CODE REVIEW

**Comment by isabelrios** [comment]
@kglazko this is similar to what you did to fix the issues on iPhone sim. If you think there could be another thing to fix, please let me know, still difficult to get a 100% green build on iPad sim... 

I'm using this PR to disable some TP tests that should not have been added to smoketest suite (my bad!)

**Comment by isabelrios** [comment]
@kglazko could you please take a look at this? even though there are still some test(s) that fail, I think we can try to add these changes and start monitoring the failures again...

**Comment by npark-mozilla** [comment]
@isabelrios is this blocked on our CI provider?

**Comment by isabelrios** [comment]
> @isabelrios is this blocked on our CI provider?

Since we have disabled Parallel testing temporarily until environment and tests are more stable this PR does not make sense now. I will close it and open a new one to work on this if we see false failures when running the tests back in parallel at some point

**Pull request closed without merging**
