### PR TITLE
Add FXIOS-8029 [v124]  Firefox Suggest settings

### PR DESCRIPTION
**Pull request by PARAIPAN9**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-8029)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/17912)

## :bulb: Description

This PR contains the implementation of the logic and behavior of `Search Engine Suggestions` & `Firefox Suggestions (Sponsored / Not Sponsored)` in `Private & Normal Browsing`.

These are the suggestions types that we care in this PR and based on the toggle switches in the `Search Settings` these should appear, or not:
| Search Engine Suggestions  | Firefox Non Sponsored Suggestions  | Firefox Sponsored Suggestions |
| ------------- | ------------- | ------------- |
|SearchEngineSearch | FirefoxNonSponsoredSearch |SponsoredSearch|

- Other suggestions that will also appear on the screen  when `Show Search Suggestions` switch is on, include : `History, Tabs  etc. suggestions`, but they are taken into consideration as individual options  for future implementation.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [x] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by adudenamedruby** [comment]
@Mergifyio backport release/v124

**Comment by adudenamedruby** [comment]
Screenshot 2024-02-21 at 9 41 40 AM

These seem related to your code changes.

**Comment by PARAIPAN9** [comment]
I'm investigating it.

**Review by adudenamedruby — APPROVED** [review]

**Review by dragosb01 — APPROVED** [review]

**Comment by linabutler** [comment]
Hi @PARAIPAN9! I'm so sorry I didn't see your PR go by, but we actually don't want to show sponsored or non-sponsored Firefox Suggest suggestions in private browsing—even if the user turned on "Show in Private Sessions".

This was an intentional product decision on [Desktop](https://bugzilla.mozilla.org/show_bug.cgi?id=1717719), and we did the same on [Android](https://bugzilla.mozilla.org/show_bug.cgi?id=1861416)—and in iOS previously in #18403. It looks like the user story is, "I am in private browsing mode and do not want to feel tracked"—even though we match the user's query on-device, it can still feel like they're being tracked, so that's why we don't show them.

**Comment by PARAIPAN9** [comment]
Hi @linabutler, for me is not a problem, I can change it back to the previous behavior. I followed the specs in https://mozilla-hub.atlassian.net/browse/FXIOS-8029 and in the Figma design: https://www.figma.com/file/Ha2T4I0nX0h7B95GYxH6wV/Simplified-UI-for-Private-Mode?type=design&node-id=3333-22585&mode=design&t=VZVdvJMixQFEwQtp-0. Let's see what @afurlan-firefox has to say.

**Comment by PARAIPAN9** [comment]
By default, the switch for `Show in Private Browsing` for non sponsored/sponsored is set to `false`, so it is up to the user if wants to see these type of suggestions or not.

**Comment by afurlan-firefox** [comment]
@linabutler I have discussed this with josh and the team before, but maybe we missed this one. Just to confirm what you are proposing.

It will be off by default, but when we turn it on, we won't show sponsored and non sponsored. We will only show suggestions for Browsing history, Bookmarks and Synced Tabs. Do you agree?

**Pull request merged**
