### PR TITLE
Bugfix MTE-1440 [v118] Use regular executable for Fennec

### PR DESCRIPTION
**Pull request by clarmso**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/MTe-1440)

## :bulb: Description

Let's experiment with regular executable for running our smoke tests and full functional tests. We may see less tests timing out in the test environment. 🤞🏼 

Screenshot 2023-08-16 at 3 47 48 PM

## :pencil: Checklist
You have to check all boxes before merging
- [ ] Filled in the above information (tickets numbers and description of your work)
- [ ] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by clarmso** [comment]
Darn..I still can't get all smoke tests to pass on the first attempt. 😢

**Comment by OrlaM** [comment]
This only impacts running the test command within XCode, if running from the command line there is no debugger so this setting should have no impact if I'm understanding the setting correctly.

**Comment by clarmso** [comment]
> This only impacts running the test command within XCode, if running from the command line there is no debugger so this setting should have no impact if I'm understanding the setting correctly.

We have had firefox freezing or black screen when launching a test from XCode. @jjSDET Could you please confirm if such a setting works better for you?

**Review by isabelrios — APPROVED** [review]

**Comment by isabelrios** [comment]
@clarmso double checking with you before merging that we want this change

**Pull request merged**
