### PR TITLE
FXIOS-1047 ⁃ [UI Test] Remove data url test

### PR DESCRIPTION
**Pull request by kathishivaramreddy**
Removing data url test, 

According to issue #7393 there are some types of data url not supported anymore by WKWebView. So, we would need to remove this test.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1047)

### CODE REVIEW

**Comment by kathishivaramreddy** [comment]
@isabelrios Please take a look.

**Comment by isabelrios** [comment]
@kathishivaramreddy thanks for your PR! it looks good but it has to be created to be merged into `main` not `master`. Please fix that and I will review and merge when ready :)

**Comment by kathishivaramreddy** [comment]
@isabelrios Done

**Review by isabelrios — APPROVED** [review]
LGTM! thanks for the PR!

**Pull request merged**
