### PR TITLE
Refactor FXIOS-0000 Remove unneeded Array extension

### PR DESCRIPTION
**Pull request by mattreaganmozilla**
## :scroll: Tickets

n/a; Miscellaneous clean-up.

## :bulb: Description

Minor code clean-up.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by mattreaganmozilla** [comment]
@OrlaM Do you know any reason we need this Array extension? AFAICT it's equivalent in performance & function to built-in `first(where:)`

**Review by PARAIPAN9 — APPROVED** [review]

**Review by OrlaM — APPROVED** [review]

**Comment by OrlaM** [comment]
Can't think of any reason for it. The history is hard to dig into from before it was moved to browser kit. Likely something that has been in the project for years, might even predate the `first(where` api.

**Comment by mattreaganmozilla** [comment]
Taking a look at the build/compiler error...

**Comment by mattreaganmozilla** [comment]
Update: there is a compiler error in some of the Deferred code but I can't immediately see how it's related to this refactor, will take a closer look as soon as I can.

**Pull request merged**
