### PR TITLE
Add MTE-564 Bitrise trigger via TC

### PR DESCRIPTION
**Pull request by isabelrios**
This PR is related to #13337

### CODE REVIEW

**Comment by isabelrios** [comment]
@JohanLorenzo I'm afraid the fake token is still detected here... any other ideas :) ?

**Comment by JohanLorenzo** [comment]
Oh, I see! I had a closer look at `.taskcluster.yml`. The easiest way to test this out is to just push changes on a random branch of the main repo, but not create a PR from it. Sorry, I should have thought of that. Let me know how this goes!

**Comment by isabelrios** [comment]
> Oh, I see! I had a closer look at `.taskcluster.yml`. The easiest way to test this out is to just push changes on a random branch of the main repo, but not create a PR from it. Sorry, I should have thought of that. Let me know how this goes!

mmm 🤔 but I need the changes in this branch for the taskcluster tasks to work... the only option would be to push to this branch without creating a PR or is there any other way I'm missing?

**Comment by isabelrios** [comment]
> > the only option would be to push to this branch without creating a PR
> 
> That's right! Then you can go to `https://github.com/mozilla-mobile/firefox-ios/commits/$YOUR_BRANCH` and look at the the github checks attached to your commits. Taskcluster should be in there.

@JohanLorenzo I can see the tasks started, they look fine! they are scheduled depending on the file changes successfully. What I can't see is the workflow starting on Bitrise. Even by pushing to this branch direclty the token detected is not the correct one but the fake token. That should be the reason for which nothing starts on Bitrise. That is the only part to test, that the builds are triggered on Bitrise when github events (pr, push) happen.

**Pull request closed without merging**
