### PR TITLE
Bugfix FXIOS-8287 [v124] Settings page cannot be opened again

### PR DESCRIPTION
**Pull request by WJustin**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-8287)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/18380)

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [x] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [x] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Review by lmarceau — COMMENTED** [review]
Heya! This seems like a good change, I would just like to understand why I can't replicate the issue you experienced in production locally before approving. Any ideas?

**Comment by lmarceau** [comment]
There's a failing unit tests on the PR `testPresentedCompletion_callsDidFinishSettings_removesChild()` could you have a look into it @WJustin ?

**Comment by lmarceau** [comment]
@WJustin the test `testPresentedCompletion_callsDidFinishSettings_removesChild` still needs to be updated. The test was checking that `dismiss` was called on the router. Out of simplicity, we can remove the following lines to fix the test:
```
        XCTAssertEqual(mockRouter.dismissCalled, 1)
        XCTAssertTrue(subject.childCoordinators.isEmpty)
```

**Comment by WJustin** [comment]
@lmarceau I've removed

**Comment by lmarceau** [comment]
Thanks @WJustin 🙏 Great work!

**Pull request merged**
