### PR TITLE
Add FXIOS-5736 [v115] credit card autofill epic branch

### PR DESCRIPTION
**Pull request by nbhasin2**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-5736)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/TODO)

### Description
EPIC branch 

### Pull requests checks where applicable
- [ ] Fill in the three TODOs above (tickets number and description of your work)
- [ ] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [ ] Unit tests written and passing
- [ ] Documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by mte-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Pull Request size seems relatively large. If this Pull Request contains multiple changes, please split each into separate PR will helps faster, easier review. Consider using epic branches for work that would affect main.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Project coverage: 29.64%</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Edited 18 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 43 files</td>
    </tr>
  </tbody>
</table>

## Client.app: Coverage: 26.41
| File | Coverage ||
| --- | --- | --- |
CreditCardEditView.swift | 0.0% | ⚠️
CreditCardEditViewModel.swift | 52.38% | ✅
SensitiveViewController.swift | 0.0% | ⚠️
Style.swift | 0.0% | ⚠️
CreditCardSettingsViewController.swift | 0.0% | ⚠️
CreditCardItemRow.swift | 0.0% | ⚠️
CreditCardSettingsViewModel.swift | 0.0% | ⚠️
MainMenuActionHelper.swift | 34.74% | ⚠️
CreditCardSettingsEmptyView.swift | 0.0% | ⚠️
AdaptiveStack.swift | 0.0% | ⚠️
RemoveCardButton.swift | 0.0% | ⚠️
SensitiveHostingController.swift | 31.96% | ⚠️
LoginListViewController.swift | 0.97% | ⚠️
ToastView.swift | 0.0% | ⚠️
CreditCardSectionHeader.swift | 0.0% | ⚠️
FloatingTextField.swift | 0.0% | ⚠️
PreferredFont.swift | 0.0% | ⚠️
CreditCardValidator.swift | 42.62% | ⚠️
CreditCardTableViewController.swift | 0.0% | ⚠️
AppSettingsOptions.swift | 0.0% | ⚠️
Profile.swift | 22.3% | ⚠️
CreditCardAutofillToggle.swift | 0.0% | ⚠️
AppAuthenticator.swift | 5.77% | ⚠️
InstructionsView.swift | 0.0% | ⚠️
TelemetryWrapper.swift | 66.88% | ✅
CreditCardTableViewModel.swift | 0.0% | ⚠️
HostingTableViewSectionHeader.swift | 0.0% | ⚠️


## CredentialProvider.appex: Coverage: 18.7
| File | Coverage ||
| --- | --- | --- |
Profile.swift | 22.3% | ⚠️
AppAuthenticator.swift | 5.77% | ⚠️
CredentialProviderPresenter.swift | 0.0% | ⚠️
CredentialProviderViewController.swift | 0.0% | ⚠️


## NotificationService.appex: Coverage: 20.19
| File | Coverage ||
| --- | --- | --- |
Profile.swift | 22.3% | ⚠️


## ShareTo.appex: Coverage: 30.88
| File | Coverage ||
| --- | --- | --- |
Profile.swift | 22.3% | ⚠️
InstructionsView.swift | 0.0% | ⚠️


## WidgetKitExtension.appex: Coverage: 23.02
| File | Coverage ||
| --- | --- | --- |
TopSitesWidget.swift | 0.0% | ⚠️


## libStorage.a: Coverage: 55.94
| File | Coverage ||
| --- | --- | --- |
RustAutofill.swift | 46.53% | ⚠️

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against fa2db989d1bdbb4834c6e168cbafefb31f7a070c
</p>

**Comment by adudenamedruby** [comment]
@nbhasin2 should I be reviewing this or holding off on it, as it's still in draft?

**Review by adudenamedruby — APPROVED** [review]
Epic branch, not much to review. I see a green build though. :)

**Comment by nbhasin2** [comment]
Yayy, @adudenamedruby I am going to revert last two commits as those were added to disable codeCheck() in Danger. So, this will get force pushed but don't be alarmed if the build is `X`

**Pull request merged**
