### PR TITLE
Add FXIOS-7420 [v119] #16457 Show all purpose generic error message (eg. api is down)

### PR DESCRIPTION
**Pull request by razvanlitianu**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-TODO)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/TODO)

## :bulb: Description

| Default | A11y |
|--------|--------|
| image | image | 
## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Review by PARAIPAN9 — APPROVED** [review]

**Review by thatswinnie — APPROVED** [review]

**Comment by lmarceau** [comment]
Just a question - the PR is marked as v120. Is the intent is to avoid merging until `main` is v120?

**Comment by razvanlitianu** [comment]
> Just a question - the PR is marked as v120. Is the intent is to avoid merging until `main` is v120?

Good question, since fakespot is behind a feature flag and will not be enabled I don't expect this to impact v119. But this will probably be enabled in v120.
@thatswinnie what do you think?

**Comment by lmarceau** [comment]
> Good question, since fakespot is behind a feature flag and will not be enabled I don't expect this to impact v119. But this will probably be enabled in v120. @thatswinnie what do you think?

We normally mark the PR as the version it was merged in, which doesn't necessarily reflect when that code was made available

**Comment by thatswinnie** [comment]
@razvanlitianu it should go in v119. We will enable the feature for beta today or tomorrow which however shouldn't matter.

**Comment by razvanlitianu** [comment]
Okay in this case I will update the name to reflect it was merged in 119

**Pull request merged**
