### PR TITLE
Add FXIOS-7443 [v120] QRCodeCoordinatorRefactor feature flag

### PR DESCRIPTION
**Pull request by FilippoZazzeroni**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7443)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/16487)

## :bulb: Description
Add `QRCodeCoordinatorRefactor` feature flag.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [x] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Review by yoanarios — APPROVED** [review]
thanks for the contribution @FilippoZazzeroni

**Comment by FilippoZazzeroni** [comment]
You're welcome @yoanarios

**Comment by yoanarios** [comment]
@FilippoZazzeroni can you rebase against main for Bitrise to run successfully, we have updated to Xcode 15 and is not backwards compatible

**Comment by FilippoZazzeroni** [comment]
@yoanarios yes, i've pushed now the changes with the rebase.

**Pull request merged**
