### PR TITLE
Bugfix FXIOS-6815 [v122] Add link to home screen option not available

### PR DESCRIPTION
**Pull request by razvanlitianu**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-6815)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/15172)

## :bulb: Description

Notes:
Running this in Fennec won't work due to the lack of com.apple.developer.web-browser entitlement, but in Firefox it does.
Due to missing certificates, use the simulator for testing this PR.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Review by lmarceau — APPROVED** [review]

**Comment by razvanlitianu** [comment]
Thanks for the review @lmarceau 🙏 can I also get a merge?

**Comment by lmarceau** [comment]
Just want to confirm this is for v122?

**Comment by razvanlitianu** [comment]
> Just want to confirm this is for v122?

yes

**Comment by razvanlitianu** [comment]
Opened he new pr here https://github.com/mozilla-mobile/firefox-ios/pull/17836

**Pull request closed without merging**
