### PR TITLE
Update search to use list.json. Does NOT include new file in xcodeproj

### PR DESCRIPTION
**Pull request by mkaply**
This patch moves us to list.json for all files and default engine and moves all engines to one directory.

Due to conflicts in the xcodeproj, I couldn't add the new file (SearchEnginesJSON.swift) so that will have to be manually added in order to build this.

### CODE REVIEW

**Comment by mkaply** [comment]
Oh and you might wonder why I didn't move the engines instead of deleting and readding. That seemed like a lot of work with no really gain, since history doesn't need to be maintained.

**Comment by farhanpatel** [comment]
### SwiftLint found issues

#### Warnings

File | Line | Reason |
| --- | ----- | ----- |
SearchEngines.swift | 265 | if,for,while,do statements shouldn't wrap their conditionals in parentheses. 
#### Errors

File | Line | Reason |
| --- | ----- | ----- |
SearchEngines.swift | 193 | Lines should not have trailing semicolons. 
SearchEngines.swift | 275 | Lines should not have trailing semicolons. 
SearchEnginesJSON.swift | 29 | Lines should not have trailing semicolons. 
SearchEnginesJSON.swift | 57 | Lines should not have trailing semicolons. 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by farhanpatel** [comment]
### SwiftLint found issues

#### Warnings

File | Line | Reason |
| --- | ----- | ----- |
SearchEnginesTests.swift | 76 | `where` clauses are preferred over a single `if` inside a `for`. 
SearchEnginesJSON.swift | 39 | `where` clauses are preferred over a single `if` inside a `for`. 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by garvankeeley** [comment]
This PR has been sitting we should take some action on it. I don't know enough about our search engine loader to understand the context of the first comment. I would need a description like 'the current code does XXX and is suboptimal because of YYY, and the patch is better because ZZZ'. Or if someone on the team who knows this area of the code could move this forward that would be even better.

**Comment by mkaply** [comment]
It's not really about the code being better it's that we moved Fennec and Desktop to use list.json (as well as Focus). Firefox iOS needs to move to using list.json or it won't be able to get search engine updates from Fennec.

I'll see if I can unbitrot things.

**Pull request closed without merging**
