### PR TITLE
Run taskgraph generation with Python 3

### PR DESCRIPTION
**Pull request by ahal**
Currently we run taskgraph generation with Python 2 which has been unsupported for a year and a half now. This updates firefox-ios to the latest taskgraph revision + decision image, and updates it to run with Python 3.

### CODE REVIEW

**Review by bhearsum — APPROVED** [review]
@isabelrios - is it possible to trigger screenshots on this PR to help verify it?

**Comment by isabelrios** [comment]
These changes look good to me. Update on Slack, leaving the comment here too.Since we can not directly tests these changes and we have to deliver a new set of screenshots by 23rd, we have two options here:
We have to deliver updated screenshots this Friday 23rd, so I can think of two options:
1- Land and try it and in case something is not working fix it by Friday
2- Wait until Friday to land it and then try if it keeps working as usual and if not, there is more time until the next required screenshots to fix any issues

I would go for 2, but let me know your thoughts. Thank you!

**Comment by isabelrios** [comment]
> @isabelrios - is it possible to trigger screenshots on this PR to help verify it?

I'm afraid I don't know how to do it, I know it should be possible to change the default branch, main, to the branch in this PR temporarly and trigger the hook, but it is done in taskgraph and don't know exactly where/how

**Comment by ahal** [comment]
2 is fine by me

**Comment by isabelrios** [comment]
The new set of screenshots was successfully taken, it is safe to land these changes now :)

**Comment by isabelrios** [comment]
Hi @ahal, just to confirm that everything looks fine regarding this PR and the environment.
I triggered manually latest main to check that the patch was fine and everything was working as expected and yeah, https://firefox-ci-tc.services.mozilla.com/tasks/groups/Sr_8ojJNR3WbJVYbDv9ukA tasks were completed :white_check_mark: , then I cancelled the pending tasks as they are all the same.

**Pull request merged**
