### PR TITLE
Refactor FXIOS-7301 - Help to remove 1 closure_body_length violation from UITestAppDelegate.swift (1/3)

### PR DESCRIPTION
**Pull request by ionixjunior**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7301)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/16442)

## :bulb: Description
This PR help to remove 1 `closure_body_length` violation from the `UITestAppDelegate.swift` file. It is the first of three parts, and in this one I've extracted the web server port config into a new function.

This PR is part of a series of PRs described here https://github.com/mozilla-mobile/firefox-ios/issues/16442#issuecomment-2197676804.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by ionixjunior** [comment]
Hi @matthewpurcell! Could you assist with reviewing this PR? I'd like to continue working on this issue.

**Review by mattreaganmozilla — APPROVED** [review]
@ionixjunior Thanks for this PR and my apologies for the delayed review. LGTM

**Comment by mattreaganmozilla** [comment]
Closing and re-opening to trigger Bitrise

**Comment by mattreaganmozilla** [comment]
Failed tests look unrelated, going to go ahead and merge

**Pull request merged**
