### PR TITLE
[Localization] String import 2020-11-29

### PR DESCRIPTION
**Pull request by electricRGB**
Latest string translations as of 2020-11-29

### CODE REVIEW

**Review by nishant2718 — APPROVED** [review]
Looks good!

**Comment by electricRGB** [comment]
Test are passing locally, but not on BR for some reason.
Screen Shot 2021-11-29 at 12 45 39 PM
Screen Shot 2021-11-29 at 12 46 48 PM
Screen Shot 2021-11-29 at 12 47 57 PM
Screen Shot 2021-11-29 at 12 49 18 PM
Screen Shot 2021-11-29 at 12 50 57 PM
Screen Shot 2021-11-29 at 12 52 21 PM

**Comment by gutley** [comment]
Why bother with Pull requests if nobody is actually going to review the changes. Even a cursory glance would have spotted that the licensing comment was screwed up in **every** .strings file.

**Comment by electricRGB** [comment]
@gutley This is a known issue that I'm looking into. The MPL shouldn't actually even be present in that file and that line should have a different description based on the Info.plist. Hence why this change was ignored.

**Pull request merged**
