### PR TITLE
Bugfix MTE-1223 [v117] Disable testShowingNotification

### PR DESCRIPTION
**Pull request by clarmso**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/MTE-1223)

## :bulb: Description
FXIOS-6208 introduced the engagement tests that passes only when the test is run right after the simulator has been reset. The test fails when it is run as a part of the full functional test suite. We need to disable this test until it can be run among other tests.

## :pencil: Checklist
You have to check all boxes before merging
- [ ] Filled in the above information (tickets numbers and description of your work)
- [X] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and ensured the tests suite is passing
- [ ] Implemented accessibility and tested on UI related work (minimum Dynamic Text and VoiceOver)
- [ ] Updated documentation / comments for complex code and public methods if needed

### CODE REVIEW

**Review by dragosb01 — APPROVED** [review]
Looks good to me

**Comment by isabelrios** [comment]
From what I have seen ([test report](https://mozilla.slack.com/archives/CAFC45W5A/p1688561183817139)) the problem with this test is the expected url: 
`XCTAssertEqual failed: ("www.mozilla.org/en-US/firefox/") is not equal to ("mozilla.com") `

Can we just change that instead of disabling the complete test?

**Comment by thatswinnie** [comment]
If we decide to disable the test, could you please create a Jira for it to get fixed in the FXIOS backlog?

**Comment by isabelrios** [comment]
> If we decide to disable the test, could you please create a Jira for it to get fixed in the FXIOS backlog?

Is it fine that the test shows ("mozilla.com") instead of ("www.mozilla.org/en-US/firefox/")? since they run on CI on Jenkins I was assuming that could be correct but I may be wrong...

**Comment by clarmso** [comment]
> From what I have seen ([test report](https://mozilla.slack.com/archives/CAFC45W5A/p1688561183817139)) the problem with this test is the expected url: `XCTAssertEqual failed: ("www.mozilla.org/en-US/firefox/") is not equal to ("mozilla.com") `
> 
> Can we just change that instead of disabling the complete test?

Our CI/CD's locale should be `en-US`. The browser redirects to the locale of the machine. I am ok with hardcoding the locale.

**Comment by clarmso** [comment]
> If we decide to disable the test, could you please create a Jira for it to get fixed in the FXIOS backlog?

Yes, I can create a FXIOS ticket for you. The notification may not be shown when the test is not the first one being run. 😞

**Review by adudenamedruby — APPROVED** [review]

**Comment by clarmso** [comment]
> If we decide to disable the test, could you please create a Jira for it to get fixed in the FXIOS backlog?

@thatswinnie Done: https://github.com/mozilla-mobile/firefox-ios/issues/15378

**Review by isabelrios — APPROVED** [review]

**Comment by isabelrios** [comment]
@clarmso do we have a test case in TestRail for this? If not can you talk to @abodea and create one, updating the status accordingly please

**Pull request merged**
