### PR TITLE
Add FXIOS-10866, FXIOS-10882 [Sent from Firefox] Add Glean metrics for shared_to

### PR DESCRIPTION
**Pull request by ih-codes**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-10866)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/23704)

Also a small test-related ticket was fixed in this PR as well: FXIOS-10882

## :bulb: Description

This PR adds telemetry around sharing content via the `ShareManager` and the share sheet. 

### Telemetry

We record:

- the activity identifier (app to which content is shared), 
- whether there was an additional explicit share message (so far these only come from share-related experiments), and 
- the share type (either site, file, or tab).

### Method

We add a new `ShareTelemetryActivityItemProvider` to the array of activity items when sharing content. This `ShareTelemetryActivityItemProvider` never returns an actual share item, but instead records the activity the user selects for sharing.

### Testing

Unit tests added for the new `ShareTelemetry` and `ShareTelemetryActivityItemProvider` types. 

`ShareManager` tests had to be updated as we now have an additional activity item returned in the activity items array. So I also did FXIOS-10882 while I was at it (was requested in a previous PR to move asserts to the end of the tests).

**Note**: I also grouped share-related test files into a new Share group (hence the file renames).

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [x] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by ih-codes** [comment]
I am currently preparing the Request Data Review form... 🕐

**Comment by ih-codes** [comment]
# This is still in progress. 
---
# Request for data collection review form

1) What questions will you answer with this data?

We want to better understand how users share URLs from the app (and to which apps) generally, as well as specifically in order to track the success of two experiments: Sent From Firefox (https://mozilla-hub.atlassian.net/browse/FXIOS-9879) and Info Card Referral (https://mozilla-hub.atlassian.net/browse/FXIOS-10375).

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?

The Mobile Growth Team hopes to determine whether appending additional links to download Firefox (or other such messaging) will increase our number of monthly installs. 

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

Currently this telemetry is collected on Android, but not on iOS due to limitations in the initial sharing implementation. As a result, we had less data to determine the viability of the Sent from Firefox experiment, which was niched down to target just shares to WhatsApp.

Having a better understanding of how users are sharing content in the app, and to which apps, will give us better context for the two aforementioned experiments, as well as future growth and retention initiatives.

4) Can current instrumentation answer these questions?

Currently we cannot gather any specific information about where users are sharing content. All we are currently tracking is when a user shares content to Pocket specifically. Other than that, we record currently when users tap the share button from the toolbar or new menu, etc. and nothing beyond the share sheet opening.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>share_sheet.shared_to</td>
    <td>2</td>
    <td>FXIOS-10866</td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.

This collection is documented in the Glean Dictionary at https://dictionary.telemetry.mozilla.org/

7) How long will this data be collected?  Choose one of the following:

I want to permanently monitor this data: @afurlan-firefox 

8) What populations will you measure?

TODO

* Which release channels?

* Which countries?

* Which locales?

* Any other filters?  Please describe in detail below.

9) If this data collection is default on, what is the opt-out mechanism for users?

TODO

10) Please provide a general description of how you will analyze this data.

TODO

11) Where do you intend to share the results of your analysis?

TODO

12) Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection?

No.

**Comment by adudenamedruby** [comment]
@ih-codes is this still in progress or ready for review? I'm confused. lolololool

**Comment by ih-codes** [comment]
> @ih-codes is this still in progress or ready for review? I'm confused. lolololool

Sorry, waiting on Andy for the data review, but the code is ready to review. 🙂

**Comment by Gouri-Firefox** [comment]
Remaining Questions: 

8. What populations will you measure?


   Which release channels?
Release; next available version on train. 

    Which countries?
* Global but Germany is excluded

    Which locales?
* Every locale available with prioritizing EN, ES, FR, pt-BR

    Any other filters? Please describe in detail below.

    If this data collection is default on, what is the opt-out mechanism for users?

Users can turn of the toggle, to turn of the feature. However, clicks to the settings will be measured. 

    Please provide a general description of how you will analyze this data.

* We will be analyzing no. of shares per user, and if those shares lead to installations. 

    Where do you intend to share the results of your analysis?

* Experimenter, Growth team results.

**Comment by adudenamedruby** [comment]
r+
# Data Review Form

_1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?_ 

Yes, telemetry is documented at https://dictionary.telemetry.mozilla.org/apps/firefox_ios

_2) Is there a control mechanism that allows the user to turn the data collection on and off?_ 

Yes, Firefox iOS provides data controls in the app settings

_3) If the request is for permanent data collection, is there someone who will monitor the data over time?_

This will be reviewed by a data-steward on the Firefox iOS team (@adudenamedruby) every 6 months

_4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?_

Type 2

_5) Is the data collection request for default-on or default-off?_

Default on

_6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?_

No

_7) Is the data collection covered by the existing Firefox privacy notice?_ 

Yes

_8) Does the data collection use a third-party collection tool?_ 

No

**Review by adudenamedruby — APPROVED** [review]

**Pull request merged**
