### PR TITLE
Renew telemetry

### PR DESCRIPTION
**Pull request by dnarcese**

### CODE REVIEW

**Comment by dnarcese** [comment]
# Request for Data Collection Renewal

** This form is for the renewal of an existing, reviewed data collection.**

** All questions are mandatory. You must receive Data Review from a Data Steward on a filled-out Request before shipping your renewed data collection.**

1. Provide a link to the initial Data Collection Review Request for this collection.
2. When will this collection now expire?
2022-07-01
3. Why was the initial period of collection insufficient?
Expiring soon

**Comment by travis79** [comment]
> # Request for Data Collection Renewal
> 
> ** This form is for the renewal of an existing, reviewed data collection.**
> 
> ** All questions are mandatory. You must receive Data Review from a Data Steward on a filled-out Request before shipping your renewed data collection.**
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        There are a lot of renewals here, the list of links will be long, but let me know if I should dig them up.
> 
>     2. When will this collection now expire?
>        2022-07-01
> 
>     3. Why was the initial period of collection insufficient?
>        Expiring soon

For the purpose of documentation, we need to add this PR to the `- data_reviews` section in the metrics.yaml, that will help to tie this renewal to the original reviews. Since this is all done in Glean, I am reasonable certain that all the metrics that are being renewed have an initial review that was good, but it might be nice to have them listed in the renewal request, but due to the time sensitivity of this, I'm not going to block on it.

The one thing I would like from you is a better answer to is question 3, even if it is "We are still learning things from these metrics and want to collect them for another six months". 🙏 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

**Review by travis79 — APPROVED** [review]
data-review+

**Comment by dnarcese** [comment]
@travis79 fyi i updated some more that were expiring between 01-01 and 07-01 so that they all have a consistent expiry

**Comment by travis79** [comment]
@dnarcese just one last nit to make future data-reviews and renewals easier, you can leave the original data reviews and just add the new one to the list to preserve the original reviews, like this:

```yaml
 data_reviews:
      - https://github.com/mozilla-mobile/firefox-ios/pull/8167
      - https://github.com/mozilla-mobile/firefox-ios/pull/9673
 ```

**Pull request merged**
