### PR TITLE
Refactor FXIOS-5858 [v121] Remove SwiftyJSON from KeychainCache.swift

### PR DESCRIPTION
**Pull request by imsanchit**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-5858)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/13376)

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Review by adudenamedruby — CHANGES_REQUESTED** [review]
Heya. We're trying to move away from using extensions, especially if they're being used in only one place. If we could bring the unwrap into the file, that'd be awesome. Then we can split that if let on multiple lines to clarify what's happening for all the unwraps.

Also, we're trying to move away from single character variables. I know you didn't write it, but if you could replace that with `string` or something actually descriptive lol

**Comment by imsanchit** [comment]
Hey @adudenamedruby, refactored it a bit, please have a look.

**Review by adudenamedruby — CHANGES_REQUESTED** [review]
This looks good. One more change is needed though. Reading this is a bit weird because the fail case is so removed from the if statement and this ends up in a pyramid of doom. However, it looks pretty easy to fix: all the `if let`s get converted to `guard let`s, where the else clause is the logger statements bringing everything together neatly making it much easier to read.

Then the missing case
```swift
// Fall through to missing.
        logger.log("Failed to read \(branch) from Keychain.",
                   level: .warning,
                   category: .storage)
        let label = label ?? Bytes.generateGUID()
        return KeychainCache(branch: branch, label: label, value: defaultValue)
```
gets put into its own function and called in the guard's `else` block after the logger.

This keeps the end of the function as the happy return path, and the beginning of the function as the preconditional setup for getting the right information with easy to follow error handling.

**Comment by imsanchit** [comment]
Please have a look if this is what we're looking for.

**Review by adudenamedruby — APPROVED** [review]
🙌 

amaze! ty so much for your contribution!

**Pull request merged**
