### PR TITLE
Bug 1376132 - The sameElements function in the Array extension file is highly innefficient-O(n^2)

### PR DESCRIPTION
**Pull request by bereket6725**
Let me know what you think! :)

### CODE REVIEW

**Comment by farhanpatel** [comment]
### SwiftLint found issues

#### Warnings

File | Line | Reason |
| --- | ----- | ----- |
ArrayExtensions.swift | 13 | `where` clauses are preferred over a single `if` inside a `for`. 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by farhanpatel** [comment]
Sorry for the long delay. This is wonderfully succinct. If you could write a few tests for this that would make it even better. There should be an `ArrayExtensionsTests.swift` where you can write a few tests.
Thank you 😄

**Comment by bereket6725** [comment]
No Worries! And yeah, that sounds great, happy to help any way I can  👍  😃

**Comment by farhanpatel** [comment]
### SwiftLint found issues

#### Warnings

File | Line | Reason |
| --- | ----- | ----- |
ArrayExtensionTests.swift | 62 | Limit vertical whitespace to a single empty line. Currently 2. 
#### Errors

File | Line | Reason |
| --- | ----- | ----- |
ArrayExtensionTests.swift | 52 | There should be no space before and one after any comma. 
ArrayExtensionTests.swift | 52 | There should be no space before and one after any comma. 
ArrayExtensionTests.swift | 52 | There should be no space before and one after any comma. 
ArrayExtensionTests.swift | 52 | There should be no space before and one after any comma. 
ArrayExtensionTests.swift | 53 | There should be no space before and one after any comma. 
ArrayExtensionTests.swift | 53 | There should be no space before and one after any comma. 
ArrayExtensionTests.swift | 53 | There should be no space before and one after any comma. 
ArrayExtensionTests.swift | 53 | There should be no space before and one after any comma. 
ArrayExtensionTests.swift | 54 | There should be no space before and one after any comma. 
ArrayExtensionTests.swift | 54 | There should be no space before and one after any comma. 
ArrayExtensionTests.swift | 54 | There should be no space before and one after any comma. 
ArrayExtensionTests.swift | 54 | There should be no space before and one after any comma. 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by bereket6725** [comment]
sorry for the styling issue, let met know I missed anything this time. Thanks!!! :)

**Comment by garvankeeley** [comment]
Nice! I think this is ready to land

**Comment by bereket6725** [comment]
Awesome! There is something else thats a bit more far-reaching I'd like to get cracking on the firefox iOS app that I think needs some serious attention. I'd like to share it with you guys first and put it on Bugzilla too. Any feedback would be great :)

**Comment by farhanpatel** [comment]
Awesome @bereket6725 , I look forward to the bug on Bugzilla 😄  - If you think it might be a security issue you can check the security flag when creating the bug.

**Comment by bereket6725** [comment]
Thanks @farhanpatel,  Will do! Actually, Its about how NotifcationCenter is handled in the app (I think its a bit problematic) and wanted to overhaul it. Hopefully you guys like the read  :)

**Pull request merged**
