### PR TITLE
Bugfix FXIOS-5958 [v113] Search name in settings is misaligned when it's very long

### PR DESCRIPTION
**Pull request by aalaaeid**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-5958)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/13538)

### Description
Search name in settings is misaligned when it's very long is fixed by override systemLayoutSizeFitting for handling cells of non default or subtitle CellStyle

### CODE REVIEW

**Review by lmarceau — CHANGES_REQUESTED** [review]
Hey this seems great @aalaaeid 🙏 The only thing else than my other comments is that it seems the spacing changed on some of the cells. Not sure if this is good or bad, we'll need a UX designer review on this. You can make the other changes and I'll ensure we get the answer on the rest. Thank you!

**Comment by lmarceau** [comment]
One thing I just noted, if we rotate from portrait > landscape then back to portrait, the cell layout is squished. If we scroll down and back up it fixes it, but we should make sure this work before merging to main (so no layout issues on rotation).
Screen Shot 2023-03-27 at 1 23 02 PM

**Comment by lmarceau** [comment]
Ok so I got the answer: We're supposed to have the same top/bottom space on all cells. If we inspect the view hierarchy, we can see there's more space at the top/bottom of the "Send usage data" cell for example, than the "Send feedback" cell. The blue boxes should be the same height as the yellow boxes.
After

In other words, the changes work for some cell type but not all of our settings cell. The "Send usage data" cell is a `BoolSetting` with a `statusText`. There's also the case of enhanced tracking protection settings cells (of type `CheckmarkSetting`) that seems to be off (see image). 

Screen Shot 2023-03-27 at 7 17 10 PM

**Comment by mte-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Project coverage: 29.03%</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Edited 2 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 0 files</td>
    </tr>
  </tbody>
</table>

## Client.app: Coverage: 26.63
| File | Coverage ||
| --- | --- | --- |
ThemedWidgets.swift | 3.85% | ⚠️
SettingsTableViewController.swift | 3.89% | ⚠️

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 635dc3fe0704d727dba33cdd03c47cc490630505
</p>

**Review by lmarceau — APPROVED** [review]
Great work @aalaaeid ! I'll just wait for Bitrise to be green to merge.

**Comment by lmarceau** [comment]
Build is green [here](https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/15ae24ec-e0d6-40e9-9067-913738101d2b)
Screen Shot 2023-03-29 at 1 23 34 PM

**Comment by iMostfa** [comment]
great work, thanks

**Comment by aalaaeid** [comment]
> great work, thanks

Thank you a lot for your support, Tlmezaa 🫡 ❤️

**Pull request merged**
