### PR TITLE
Bugfix FXIOS-5832 [v112] Add delegate handling for Adjust

### PR DESCRIPTION
**Pull request by fbertsch**
[FXIOS-5832](https://mozilla-hub.atlassian.net/browse/FXIOS-5832) https://github.com/mozilla-mobile/firefox-ios/issues/13334

### CODE REVIEW

**Comment by fbertsch** [comment]
I'm about 90% sure this is a bug, not 100%. We're also working with Adjust to get Firefox iOS on the allowlist for attribution without ATT.

**Comment by fbertsch** [comment]
Build is failing - I'll debug before you have to review @adudenamedruby

**Review by adudenamedruby — APPROVED** [review]

**Comment by thatswinnie** [comment]
@Mergifyio backport release/v120.0

**Comment by thatswinnie** [comment]
@Mergifyio backport release/v111.0

**Pull request merged**
