### PR TITLE
Upgrade Glean to v51

### PR DESCRIPTION
**Pull request by tarikeshaq**
This is exactly https://github.com/mozilla-mobile/firefox-ios/pull/11392 but fixing the Logins breaking changes and upgrading the FML version

cc @mhammond, @jhugman

### CODE REVIEW

**Comment by tarikeshaq** [comment]
Not sure what the build failure here is, I can't seem to see the Bitrise logs, I think I used to have permission but now I'm seeing 404s - @lmarceau (tagging you because you commented on that other repo 🙏) this builds OK locally

**Comment by lmarceau** [comment]
@tarikeshaq The build failed due to increased warnings count.
It seems to relate to this:
Screen Shot 2022-07-25 at 1 35 22 PM
 
I tried building locally but got stuck in dependencies errors with SPM while trying it 😞. It was building on which Xcode version for you?

**Comment by tarikeshaq** [comment]
> I tried building locally but got stuck in dependencies errors with SPM while trying it 😞. It was building on which Xcode version for you?

I'm using Xcode 13.4.1! Although the dependency issues you might get around by clearing your Package cache (File->Packages->Reset Packages Cache)

Thanks @lmarceau!! I'll gave it a go locally and pushed a commit to remove the `try`s from those tests!

**Comment by lmarceau** [comment]
> > I tried building locally but got stuck in dependencies errors with SPM while trying it 😞. It was building on which Xcode version for you?
> 
> I'm using Xcode 13.4.1! Although the dependency issues you might get around by clearing your Package cache (File->Packages->Reset Packages Cache)
> 
> Thanks @lmarceau!! I gave it a go locally and pushed a commit to remove the `try`s from those tests!

Ok great I restarted the BR. I had tried Reset Packages Cache and there was still warnings/errors. Some were located in the Metrics.swift file. I deleted that file so it's generated again but the errors persisted. I'll try again later to build it locally.

**Comment by badboy** [comment]
Please wait with a merge here.
[We found a bug in Glean v50+](https://bugzilla.mozilla.org/show_bug.cgi?id=1781085) where it is missing some data. We will have that fixed tomorrow and then can jump to that version directly.

**Comment by lmarceau** [comment]
Closing in favor of https://github.com/mozilla-mobile/firefox-ios/pull/11407

**Pull request closed without merging**
