### PR TITLE
Refactor FXIOS-7399 [v120] Replace goToSettingsButton in DefaultBrowserOnboardingViewController

### PR DESCRIPTION
**Pull request by pelumy**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-TODO)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/TODO)

## :bulb: Description

Changed existing `goToSettingsButton` on `DefaultBrowserOnboardingViewController` from `ResizableButton` type to `PrimaryRoundedButton` type

Screenshot:

Screenshot 2023-10-10 at 11 34 39 pm

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by pelumy** [comment]
I just realised I didn't link the issue in the branch name. Do I need to delete this PR and create aa new branch correctly?

**Comment by thatswinnie** [comment]
> I just realised I didn't link the issue in the branch name. Do I need to delete this PR and create aa new branch correctly?

No, it's ok like this for now. If you have another PR upcoming you can name it correctly then.

**Comment by pelumy** [comment]
> > I just realised I didn't link the issue in the branch name. Do I need to delete this PR and create aa new branch correctly?
> 
> No, it's ok like this for now. If you have another PR upcoming you can name it correctly then.

Alright, thanks.

**Review by thatswinnie — APPROVED** [review]

**Comment by thatswinnie** [comment]
Thanks so much @pelumy for making this change! 🙏

**Comment by pelumy** [comment]
Thanks @thatswinnie for the support :smiley:

**Pull request merged**
