### PR TITLE
Bugfix MTE-2330 [v125] Do the variables get set?

### PR DESCRIPTION
**Pull request by clarmso**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-TODO)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/TODO)

## :pencil: Checklist
You have to check all boxes before merging
- [ ] Filled in the above information (tickets numbers and description of your work)
- [ ] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by clarmso** [comment]
I updated the `bitrise.yml` file and the `build_applications` stage is running.

https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/559b9697-e274-44b7-b08e-9199ea149c4e

**Comment by clarmso** [comment]
Close and reopen the PR to trigger Bitrise.

**Comment by clarmso** [comment]
Open and close PR triggers a pipeline on Bitrise: https://app.bitrise.io/build/7a49f3bc-8888-4879-b591-eb20149fc609

(Don't worry about the failing smoke test 3 for now.)

**Review by dragosb01 — APPROVED** [review]

**Comment by isabelrios** [comment]
We are still working on the decision making and the files detection to run the workflows. There are different things to consider when bitrise is triggered from PR or push in main, from fork or branch from main, we are looking at all the variables and working on it.

**Comment by isabelrios** [comment]
Closing this PR

**Pull request closed without merging**
