### PR TITLE
Fix #4764 - XCUITest testSavedLoginAutofilled

### LINKED ISSUE #4764: [XCUITests] Fix testSavedLoginAutofilled
This test is part of the Smoketest and is failing looks like due to a change in the LinkedIn page used. See failure[ here](https://dashboard.buddybuild.com/apps/57bf25c0f096bc01001e21e0/build/5cad401225a6a2000170a6e1/test/627e6a5b-e71a-48ca-9dab-8709a0015f8a/0bc762a6-03b8-49a1-9377-8a3b273dc070)

### PR DESCRIPTION
**Pull request by isabelrios**
PR to fix this test failing on the Smoketest schema due to changes in the website

### CODE REVIEW

**Comment by garvankeeley** [comment]
Can it use a local fixture instead of loading a remote page?

**Comment by isabelrios** [comment]
> Can it use a local fixture instead of loading a remote page?

When I created the test I did not found the way with the local fixtures we had I will check with the current ones or if we can create a new one easily.

**Comment by wasim1772** [comment]
1E2F00F5-287B-4D3C-A1EC-0AFCE796059B

**Comment by isabelrios** [comment]
Closing this PR since this work is being done in PR #4857

**Pull request closed without merging**
