### PR TITLE
Refactor - implement encapsulation bvc

### PR DESCRIPTION
**Pull request by muhasturk**

### CODE REVIEW

**Comment by lmarceau** [comment]
Hi @muhasturk! Any update on this?

**Comment by muhasturk** [comment]
sorry guys I have no free time nowadays.

**Comment by lmarceau** [comment]
No worries @muhasturk ! I'll try to make time to merge your contribution when I have some time. Thanks!

**Comment by lmarceau** [comment]
Closing this in favor of https://github.com/mozilla-mobile/firefox-ios/pull/10340

**Pull request closed without merging**
