### PR TITLE
Bugfix FXIOS-5660 [v110] Continuation crash

### PR DESCRIPTION
**Pull request by lmarceau**
## [FXIOS-5660](https://mozilla-hub.atlassian.net/browse/FXIOS-5660) https://github.com/mozilla-mobile/firefox-ios/issues/13067
Add a timeout with task group when downloading an image with Kingfisher due to [Sentry crash reports](https://sentry.io/share/issue/951b878416374dd98eccb6fd88fd8427).

### CODE REVIEW

**Comment by isabelrios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Edited 3 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 1 files</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 380b995ff0148601ddc76801c1ba23b4bc11f33a
</p>

**Review by OrlaM — APPROVED** [review]

**Comment by lmarceau** [comment]
Build is green [here](https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/3f4231d0-7bc9-4cbe-9ba7-4e0fb8807196)
Screen Shot 2023-02-02 at 9 26 50 AM

**Comment by lmarceau** [comment]
@Mergifyio backport release/v110

**Comment by lmarceau** [comment]
https://github.com/Mergifyio backport release/v110.0

**Pull request merged**
