### PR TITLE
Add FXIOS-7320 [v119] Send telemetry when user expands settings

### PR DESCRIPTION
**Pull request by PARAIPAN9**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7320)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/16247)

## :bulb: Description

- Send telemetry when user expands settings card view
## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by nbhasin2** [comment]
@PARAIPAN9 you will need to fill out telemetry form as you adding new events

Something similar to this: https://github.com/mozilla-mobile/firefox-ios/pull/15833#issuecomment-1659032618

**Comment by PARAIPAN9** [comment]
# Request for data collection review form

1) What questions will you answer with this data?
- This will help us understand if users use our settings option from shoppig experience

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:
- By knowing if the feature is used, we could make improvements.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?
- There are no other methods

4) Can current instrumentation answer these questions?
- No

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>Records when the Settings Card's header or chevron button is tapped and the card expands</td>
    <td>Category 2</td>
    <td>#16247</td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
 * Often the Privacy Notice for your product will link to where the documentation is expected to be.
 * Common examples for Mozilla products/services:
    * If this collection is Telemetry you can state "This collection is documented in its definitions files Histograms.json, Scalars.yaml, and/or Events.yaml and in the Probe Dictionary at https://probes.telemetry.mozilla.org."
    * If this data is collected using the Glean SDK you can state “This collection is documented in the Glean Dictionary at https://dictionary.telemetry.mozilla.org/"
 * In some cases, documentation is included in the project’s repository.

7) How long will this data be collected?  Choose one of the following:
- Currently set to expire 2024-09-12 (~12 Months)

8) What populations will you measure?
- All channels, all locales, all countries

9) If this data collection is default on, what is the opt-out mechanism for users?
- The user can opt out

10) Please provide a general description of how you will analyze this data.
- Glean

11) Where do you intend to share the results of your analysis?
- Glean and ad partners

12) Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection? If so:
- No third party tools

**Comment by PARAIPAN9** [comment]
@dnarcese for Data Review

**Comment by thatswinnie** [comment]
@perrymcmanis144 another Telemetry for Fakespot

**Review by thatswinnie — APPROVED** [review]

**Pull request merged**
