### PR TITLE
Bugfix FXIOS-5619 [v113] Reader mode saves user set theme

### PR DESCRIPTION
**Pull request by CatalinNeculaide**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-5619)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/12981)

### CODE REVIEW

**Comment by mte-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Project coverage: 30.35%</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Edited 2 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 0 files</td>
    </tr>
  </tbody>
</table>

## Client.app: Coverage: 27.2
| File | Coverage ||
| --- | --- | --- |
ReaderModeHandlers.swift | 0.0% | ⚠️
ReaderModeStyleViewController.swift | 2.83% | ⚠️

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against eab7557c376ebcb33670f9da183daed39f8be21f
</p>

**Review by thatswinnie — APPROVED** [review]

**Comment by lmarceau** [comment]
@CatalinNeculaide do you mind merging main into your branch, or rebasing with main? The Bitrise had failed due to some reasons and updating with main should fix that.

**Comment by thatswinnie** [comment]
Build passed: 
Screenshot 2023-03-24 at 10 20 55

**Comment by thatswinnie** [comment]
Build passed: 
Screenshot 2023-03-24 at 10 20 55

**Pull request merged**
