### PR TITLE
Bugfix FXIOS-5711 [v112] Open-Tabs-view-does-not-focus-a-current-tab

### PR DESCRIPTION
**Pull request by PARAIPAN9**
## Video

https://user-images.githubusercontent.com/51127880/222137721-98ac35c1-e3f1-42bc-808e-4da6503454bd.mp4

### CODE REVIEW

**Comment by mte-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Project coverage: 30.18%</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Edited 1 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 0 files</td>
    </tr>
  </tbody>
</table>

## Client.app: Coverage: 27.09
| File | Coverage ||
| --- | --- | --- |
GridTabViewController.swift | 38.8% | ⚠️

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against b8faf2bf35e938f75a1bc57549887e1c99ecf108
</p>

**Review by yoanarios — APPROVED** [review]
LGTM

**Comment by adudenamedruby** [comment]
Just a reminder, titles on PRs/merges shouldn't be kebab case. No worries, and we don't need to change it, but just mentioning for future reference. :)

**Comment by PARAIPAN9** [comment]
Sorry, my bad.

**Pull request merged**
