### PR TITLE
Bump FXIOS-5818 [v112] Update Glean to 52.2.0

### PR DESCRIPTION
**Pull request by lmarceau**
## [FXIOS-5818](https://mozilla-hub.atlassian.net/browse/FXIOS-5818) https://github.com/mozilla-mobile/firefox-ios/issues/13302
Update Glean to 52.2.0
[Glean changelog](https://mozilla.github.io/glean/book/appendix/changelog/sdk.html)

### CODE REVIEW

**Comment by lmarceau** [comment]
Can't build with latest Glean version due to warning inside Generated code from A-S. 

Screen Shot 2023-02-22 at 11 52 11 AM
Screen Shot 2023-02-22 at 11 50 31 AM

**Comment by nbhasin2** [comment]
Time to ask badboy aka Jan Eric for support

**Comment by lmarceau** [comment]
Thanks to @tarikeshaq this PR is now ready for review 🙏

**Comment by lmarceau** [comment]
I'm getting some tests failures with the following trace:
```
2023-02-22 15:49:09.396363-0500 Client[91860:558780] [glean_core::dispatcher::global] Failed to launch a task on the queue. Discarding task.
2023-02-22 15:49:09.397620-0500 Client[91860:558780] [glean_core::metrics::counter] Couldn't get storage. Can't record counter 'glean.upload.pending_pings'.
thread '<unnamed>' panicked at 'No database found', glean-core/src/core/mod.rs:531:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-02-22 15:49:09.397877-0500 Client[91860:558780] [uniffi_core::ffi::rustcalls] Caught a panic calling rust code: "No database found"
2023-02-22 15:49:09.397967-0500 Client[91860:558795] [glean_core::core] Creating new Glean v52.2.0
2023-02-22 15:49:09.398393-0500 Client[91860:558795] [glean_core::database] Database initialized
Glean/glean.swift:4858: Fatal error: 'try!' expression unexpectedly raised an error: Glean.(unknown context at $10c453aa4).UniffiInternalError.rustPanic("No database found")
2023-02-22 15:49:09.400177-0500 Client[91860:558780] Glean/glean.swift:4858: Fatal error: 'try!' expression unexpectedly raised an error: Glean.(unknown context at $10c453aa4).UniffiInternalError.rustPanic("No database found")
(lldb) 
```

In short, tests fails with `UniffiInternalError.rustPanic("No database found")`

**Comment by lmarceau** [comment]
@tarikeshaq I think this is exactly it. Making that change fixes the issue. I'll open a bug ticket on Glean side for this. Thank you!

**Comment by lmarceau** [comment]
Here's the [Glean bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1818361) created

**Comment by mte-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Edited 15 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 0 files</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 52719fb3515c830a191e4e86967e706c73c7b304
</p>

**Comment by lmarceau** [comment]
This PR keeps on giving. Turns out there's a fix for the `Glean.shared.resetGlean(clearStores: true)` that should be part of the next Glean release `52.3.0` later this week. Looks like it will be better to wait for that particular release.

**Review by nbhasin2 — APPROVED** [review]
🙌

**Pull request merged**
