### PR TITLE
Fix ETP UITest, img.src is not triggering js->native callback

### PR DESCRIPTION
**Pull request by garvankeeley**
This should fix the UITest, and improves the in-content script to catch the case of an IMG being added to the DOM.

### CODE REVIEW

**Comment by garvankeeley** [comment]
@isabelrios

**Comment by isabelrios** [comment]
@garvankeeley, I launched the tests on BB and there is one test `testWhitelist()`still failing with errror: `failed: caught "NSInternalInconsistencyException", "API violation - multiple calls made to -[XCTestExpectation fulfill] for stats zero."`

Also, in order to have the build running I changed xcode to xcode 10, otherwise KIF framework was [failing](https://dashboard.buddybuild.com/apps/57bf25c0f096bc01001e21e0/build/5d8ba4778430f20001d3da36#logs) to build (looks like we have to update its version so that it works with xcode 11 according to [latest release](https://github.com/kif-framework/KIF/releases/tag/v3.7.8))

**Comment by garvankeeley** [comment]
@isabelrios I updated the tests, they are green for me now

**Comment by garvankeeley** [comment]
r+'d in channel, landing

**Pull request merged**
