### PR TITLE
Add FXIOS-9138 ⁃ Add onboarding CFR for menu

### PR DESCRIPTION
**Pull request by dicarobinho**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-9138)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/20246)

## :bulb: Description
Added onboarding CFR for menu

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by dicarobinho** [comment]
Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2024-10-10 at 15 00 51
Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2024-10-10 at 14 56 09
Simulator Screenshot - iPhone 15 Pro Max - 2024-10-09 at 16 47 39
Simulator Screenshot - iPhone 15 Pro Max - 2024-10-10 at 12 16 57

**Review by adudenamedruby — CHANGES_REQUESTED** [review]
So, on first look, we need to remove the arrow CFR. We only want it to pop up when the menu is opened, not on the toolbar. I should have communicated that more clearly, but I thought it was clear from the design, that Option 2 had a checkmark on it. :( My bad on that.

**Comment by dicarobinho** [comment]
That is sad. :( Going to remove the code for arrow CFR...

**Review by adudenamedruby — COMMENTED** [review]
Are contextual hints not supposed to go through the `ContextualHintProvider` It's been a while since I've worked with CFRs, but last I remember, there was some sort of hint eligibility utility, and a provider to make things for CFR live in there. Has that changed?

**Review by adudenamedruby — APPROVED** [review]

**Pull request merged**
