### PR TITLE
Add FXIOS-7269 [v117] Add illustration for search widget experiment

### PR DESCRIPTION
**Pull request by nbhasin2**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7269)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/16121)

## :bulb: Description
Add illustration for search widget experiment

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by dnarcese** [comment]
🙌

**Review by lmarceau — APPROVED** [review]

**Comment by nbhasin2** [comment]
@clarmso this PR needs to run BR but can no longer tap on the button, when you reach out to their team you can mention this PR as reference if needed

**Review by yoanarios — APPROVED** [review]

**Comment by lmarceau** [comment]
@nbhasin2 I started the build throught the link Clare sent [here](https://mozilla.slack.com/archives/C05C9RET70F/p1692631548017529?thread_ts=1692628219.186519&cid=C05C9RET70F).

**Comment by nbhasin2** [comment]
@mergify backport release/v117

**Pull request merged**
