### PR TITLE
Refactor FXIOS-4884 [v107] Implement settings theming, first pass

### PR DESCRIPTION
**Pull request by lmarceau**
# [FXIOS-4884](https://mozilla-hub.atlassian.net/browse/FXIOS-4884) https://github.com/mozilla-mobile/firefox-ios/issues/11825
- First step towards implementing settings pages with the new theming system, before the PR gets any bigger.
- Wrote a bunch of ToDos in there for me as the PR was getting big (example: `// TODO: Next task for FXIOS-4884 - apply ThemedTableViewCell theme`). Those needs to be fixed as my next steps, and will absolutely need to be done before v107 is soft frozen as theme change in settings will be a bit broken for now.
- Design review still needs to happen for those colors, but want to finish a first pass and fix any theme change hickups before showing this to design peeps.
- Mainly the changes in this PR is to add a bunch of VC to be `Themable`, then pass down the theme in the different cells whenever they are configured.
- Removed listening to theme change for example in WallpaperSettingsHeaderViewModel, since the VC is the one listening to theme changes
- Next PRs: Still need to make sure on theme changes the cells will adapt properly (currently they are set and unless the view is killed, the theme is not changed again)

### CODE REVIEW

**Comment by lmarceau** [comment]
Build is green [here](https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/29b17f7a-8c70-46ce-89ad-1da4312e1b1f)
Just pushed to fix the swiftlint warning, wont rerun to build for this only

**Review by OrlaM — APPROVED** [review]
Code looks good to me. Have you run the designs by Crystal? The contrast between the primary text and the secondary text is quite different than what it was before so just wanna make sure design are ok with it. 
Since this leaves main in a slightly broken state anyway feel free to merge it and if design have follow up requests they can go in the next PR.

**Review by thatswinnie — APPROVED** [review]

**Comment by lmarceau** [comment]
@OrlaM Not yet, I was planning on finishing up the other todos beforehand so I can show the changes to design with a working state (and not half working, i.e. when we change theme half of the stuff doesn't update - not a regression though as it was mostly like this before). If it takes too much time to fix all the little quirks and v107 is getting closed, I'll make sure we're in a working state for v107

**Comment by electricRGB** [comment]
> I'll make sure we're in a working state for v107

Famous last words. :P

**Comment by lmarceau** [comment]
Build is green [here](https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/074d9ad9-ad23-4f19-bef1-6002309362c0)

**Pull request merged**
