### PR TITLE
FXIOS-790 ⁃ Fix #7044 - Search Button Test

### LINKED ISSUE #7044: FXIOS-672 ⁃ [XCUITest] New test for the search button
There is a new search button added to the bottom bar. It would be nice to have a test to check its functionality.

New UI:
IMG_7703

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-672)

### PR DESCRIPTION
**Pull request by rpappalax**
*Thank you for submitting a pull request, your contributions are greatly appreciated!*

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Please make sure you've run the test scheme and all the tests pass. If your changes affect existing tests please make sure to update the tests as well.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-790)

### CODE REVIEW

**Review by SimonBasca — APPROVED** [review]
This looks good codewise, we should re-run BB before merging.

**Comment by garvankeeley** [comment]
PRs should have descriptive titles, I'll update this.

**Comment by rpappalax** [comment]
@isabelrios I've rebased and re-verified test.  Since it's been weeks, would you be willing to give it a final review and merge if it's ready to go?  thanks!

**Comment by isabelrios** [comment]
@rpappalax this is looking good, just please verify that the test is only enabled in one schema, you can see that by changing between Fennec_Enterprise_SmokeXCUITest and Fennec_Enterprise_XCUITests, if it is enabled in both, please disable it from the smoketest. Apart from that, the test is ready to go!! thanks for implementing it!

**Pull request merged**
