### PR TITLE
#9526 Two selected tab in tab tray

### PR DESCRIPTION
**Pull request by lmarceau**
Contains PR https://github.com/mozilla-mobile/firefox-ios/pull/9528 since there was a dependency on it for the unit tests. Please review this one first. Still opened this one in the meantime so it can be pre-looked at. 

This PR is a bug fix for #9526 - Two selected tabs in tab tray
- The issue was that we were sending the notification that the tab tray was removed before adjusting the selectedIndex
- Renamed `removeTabAndUpdateSelectedIndex` to `removeTab` for API consistency
- Added unit tests to make sure the tab cell is selected, and only one is selected

### CODE REVIEW

**Comment by isabelrios** [comment]
Hi @lmarceau , was checking build failures and for this one looks like there are a few unit tests failing. You may be aware of that, but just in case..

> 	ClientTests:
>                TabManagerTests.testDeleteFirstTab()
>                TabManagerTests.testDeleteFirstTab()
> 		TabManagerTests.testDeleteFirstTab()
> 		TabManagerTests.testDeleteLastTab()
> 		TabManagerTests.testDeleteLastTab()
> 		TabManagerTests.testDidDeleteLastPrivateTab()
> 		TabManagerTests.testDidDeleteLastPrivateTab()
> 		TabManagerTests.testDidDeleteLastTab()
> 		TabManagerTests.testDidDeleteLastTab()
> 		TabManagerTests.testDidDeleteLastTab()
> 		TabManagerTests.testDidDeleteLastTab()
> 		TabManagerTests.testTabsIndex()
> 		TabManagerTests.testTabsIndex()
> 		TabManagerTests.testTabsIndex()
> 		TabManagerTests.testTabsIndexClosingFirst()
> 		TabManagerTests.testTabsIndexClosingFirst()

**Comment by lmarceau** [comment]
@isabelrios yes I saw it! I have to go back to the drawing board hehe. Thanks!

**Comment by lmarceau** [comment]
Just to sum up the changes - Lots of small commits.
- I reverted my first changes for the fix and went with another solution, using indexOfCellDrawnAsPreviouslySelectedTab instead
- Added some tests in TabManagerTests and some checks in existing unit tests, to make things more explicit

**Comment by lmarceau** [comment]
### Notes on the bug
We fall in this case when we're removing a tab and the deletedIndex is smaller than the selectedIndex `deletedIndex < _selectedIndex`. 

### Example
We have four tabs in the tab tray with the selected tab index at 2 (index starting at 0). The user clicks to remove the first tab, so the tab at index 0. The removeTab function in the TabManager is called. This function removes the tab from the tab array and store, and sends a delegate call `didRemoveTab` so the UI can update and actually remove the tab. The _selectedIndex isn't updated at that point, BUT the tab count is now at 3.

The tab display manager receives the delegate call to update the UI. The selectedTab is now the **fourth tab** (index 3), since _selectedIndex is still at 2 but the first tab was removed. The fourth tab appears selected, the first tab is removed, so the fourth tab goes to the third place. In other words, when `let selected = tab == tabManager.selectedTab` is called in the `GridTabViewController`, the selectedTab is not the proper tab yet, but our UI is still adjusted with it nonetheless.

Then the index is updated from the updateIndexAfterRemovalOf function to complete the tab removal. The index of the selected tab is now 1, as it should. But the fourth now third tab is still selected, and isn’t refreshed. 

### Solution proposal
I tried changing the _selectedIndex so we update it before adapting the UI on a tab removal, and avoid putting a tab as selected when it isn't, but this is messing with other parts of the code. Easiest way at the moment is to refresh a + 1 index if it's needed, as done in the tab display manager in this PR. We'll need to untangle the tab manager at some point to streamline how we handle tab management.

**Review by nbhasin2 — APPROVED** [review]

**Comment by nbhasin2** [comment]
Thanks @lmarceau, like we discussed earlier we will revisit this as there might be some underlying issue but for now this works well :)

**Pull request merged**
