### PR TITLE
Add FXIOS-6000 [v113] Add surface to messaging telemetry extras

### PR DESCRIPTION
**Pull request by adudenamedruby**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-6000)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/TODO)

### Description
Added the surface key in messaging, as well as messaging option

### Pull requests checks where applicable
- [x] Fill in the three TODOs above (tickets number and description of your work)
- [x] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [x] Unit tests written and passing
- [x] Documentation / comments for complex code and public methods

### CODE REVIEW

**Review by yoanarios — APPROVED** [review]
LGTM 🚀

**Comment by yoanarios** [comment]
@adudenamedruby do we need to backport this to v112?

**Review by thatswinnie — APPROVED** [review]

**Comment by adudenamedruby** [comment]
@yoanarios Yeah, it will need to be backported. :)

**Comment by mte-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Project coverage: 30.38%</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Edited 6 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 0 files</td>
    </tr>
  </tbody>
</table>

## Client.app: Coverage: 27.24
| File | Coverage ||
| --- | --- | --- |
SurveySurfaceViewModel.swift | 16.0% | ⚠️
GleanPlumbMessageStore.swift | 91.07% | ✅
SurveySurfaceManager.swift | 87.93% | ✅
GleanPlumbMessageManager.swift | 73.33% | ✅
TelemetryWrapper.swift | 66.51% | ✅

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against a9a5d115b793eb9f1a7c6526ad49e2dc21585d7e
</p>

**Comment by adudenamedruby** [comment]
@Mergifyio backport release/v112.0

**Comment by adudenamedruby** [comment]
https://github.com/Mergifyio backport release/v112

**Pull request merged**
