### PR TITLE
Fixes #9242 - Created/modified label off-center in landscape orientation on devices with a notch

### LINKED ISSUE #9242: Created/last modified label for saved login off center in landscape orientation on devices with notch
## Steps to reproduce
* Requires iPhone with notch
1. Tap the menu button
2. Tap Passwords
3. Tap a saved login
4. Rotate device into landscape orientation

### Expected behavior
- Created/modified date label should remain centered horizontally in table view cell

### Actual behavior
- Created/modified date label shift to the right and appear off-center

### Device & build information
* Device: iPhone 12 Pro Max
* Simulators: iPhone 13 Pro, iPhone 13 Pro Max
* Build version: [85d8ceb](https://github.com/mozilla-mobile/firefox-ios/commit/85d8ceb33321b0697157357706eecbd4f66812fa)

### Notes
Attachments: 

Centered in portrait:
portrait

Off-center in landscape:
landscape

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3245)

### PR DESCRIPTION
**Pull request by michaelbiv**
Fixes: #9242 

Updates horizontal center to account for possible safeAreaInsets

Portrait:
portrait

Landscape:
landscape

### CODE REVIEW

**Comment by nishant2718** [comment]
Noting that this PR + https://github.com/mozilla-mobile/firefox-ios/pull/9239 fixes the issue we see here after rotation. Tested both together and looks good - will wait for smoke test results. 

@michaelbiv Same as the other PR, I will close this and reopen to trigger our pipeline.

**Comment by nishant2718** [comment]
@michaelbiv It looks like this PR fails parts of the build pipeline tests. Test results don't indicate anything having to do with your change, but can you try rebasing against `main`? Maybe that can solve it.

**Comment by michaelbiv** [comment]
> @michaelbiv It looks like this PR fails parts of the build pipeline tests. Test results don't indicate anything having to do with your change, but can you try rebasing against `main`? Maybe that can solve it.

Yep, no problem

**Comment by michaelbiv** [comment]
@nishant2718 I just merged main and updated.  Thanks!

**Review by nishant2718 — APPROVED** [review]

**Pull request merged**
