### PR TITLE
Bugfix FXIOS-8558 [v125] Deeplink white screen, page won't load - Part 2

### PR DESCRIPTION
**Pull request by nbhasin2**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-8558)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/19024)

## :bulb: Description

This is more of a refactor to ensure the constraints for WebViewViewController and webview are aligned.

## :pencil: Checklist
You have to check all boxes before merging
- [ ] Filled in the above information (tickets numbers and description of your work)
- [ ] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Review by lmarceau — APPROVED** [review]

**Comment by lmarceau** [comment]
For posterity, this PR relates to [this PR](https://github.com/mozilla-mobile/firefox-ios/pull/18802/files) (history of `.frame` the changes is noted in there)

**Comment by nbhasin2** [comment]
This can be added to v124 (weekly) cc @afurlan-firefox

**Comment by nbhasin2** [comment]
@mergify backport release/v123

**Comment by nbhasin2** [comment]
@mergify backport release/v124

**Pull request merged**
