### PR TITLE
Bugfix FXIOS-3653 [v123] Adjust row count for Top Site section on home page depending on font sizes

### PR DESCRIPTION
**Pull request by imsanchit**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-3653)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/9826)

### Before PR
Screenshot 2024-01-04 at 7 01 03 PM

### After PR
Screenshot 2024-01-04 at 7 09 45 PM

Note, here only 4 cells are visible since from settings the number of rows on the homepage was set as 2.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by adudenamedruby** [comment]
Heya. Please remember to add screenshots of UI fixes. :)

**Comment by imsanchit** [comment]
sure, thanks for the suggestion!!, I have updated the PR description with the screenshots, please have a look.

**Comment by adudenamedruby** [comment]
Asked for feedback from PM/design.

**Comment by adudenamedruby** [comment]
Heya. Looks like design weighed in that there's work to be done to fix this from a UX perspective. Gonna close this PR for now.

Thanks so much for your work on this, and apologies for it not going in. Your other PRs are doing great though. :)

**Comment by imsanchit** [comment]
No worries @adudenamedruby, thanks for the review. :)

**Pull request closed without merging**
