### PR TITLE
Bug #5021 - desktop UA test not working on ipad

### PR DESCRIPTION
**Pull request by garvankeeley**

### CODE REVIEW

**Comment by isabelrios** [comment]
@garvankeeley there are still [two tests failing](https://dashboard.buddybuild.com/apps/57bf25c0f096bc01001e21e0/build/5cebf50df264d300014603ae#tests) with `OpenNewTabLongPressTabsButton is not an action`but I don't see that being removed here... and that's part of the code... did you remove that?

**Comment by garvankeeley** [comment]
I didn't make any changes to OpenNewTabLongPressTabsButton, odd that is failing suddenly

**Comment by isabelrios** [comment]
> I didn't make any changes to OpenNewTabLongPressTabsButton, odd that is failing suddenly

I think I know what's happening...[that action is only available for iPhone sim not iPad]([url](https://github.com/mozilla-mobile/firefox-ios/blob/master/XCUITests/FxScreenGraph.swift#L837)), long pressing on the tabs button does not give an option to open new tab on iPad sim...we would need to open the new tab using a different option so that those tests work...

**Comment by garvankeeley** [comment]
I think one platform is enough for these tests, I just set them to iPhone only.

**Pull request merged**
