### PR TITLE
Remove FXIOS Unused code

### PR DESCRIPTION
**Pull request by lmarceau**
## :scroll: Tickets
No tickets

## :bulb: Description
 I tried using a tool called [Periphery](https://github.com/peripheryapp/periphery) to locate some unused classes in the project. This is a follow up on https://github.com/mozilla-mobile/firefox-ios/pull/23380

## :pencil: Checklist
You have to check all boxes before merging
- [X] Filled in the above information (tickets numbers and description of your work)
- [X] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Review by FilippoZazzeroni — APPROVED** [review]
LGTM 🎉  so nice when there is dead code removed

**Review by issammani — APPROVED** [review]
LGTM ! Not sure how useful it would be, but I think it would be nice to have this run on our CI and warn that we are pushing some unused code ?

**Comment by FilippoZazzeroni** [comment]
Yes @issammani that would be really nice to have on our CI, or to have a Github action who runs this every fixed amount of time.

**Comment by lmarceau** [comment]
Periphery can have false positives, so I wouldn't trust entirely what it detects as unused code.

**Comment by lmarceau** [comment]
Tagging newly created issue to track those Periphery clean up PRs https://github.com/mozilla-mobile/firefox-ios/issues/23702

**Pull request merged**
