### PR TITLE
Add FXIOS-6089 [v114] fathom.js for initial testing with ruleset

### PR DESCRIPTION
**Pull request by issammani**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-6089)

Inject fathom.js to Firefox iOS for initial testing with ruleset

### Description
Create an area in the app where engineers can easily add and test new JS components
- This is for both retrieval and injection
- Add an area to directly inject raw JS files and add it to Firefox i.e. similar to SwiftFox JS injection and evaluation

### Pull requests checks where applicable
- [x] Fill in the three TODOs above (tickets number and description of your work)
- [ ] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
~- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)~
~- [ ] Unit tests written and passing~
- [ ] Documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by nbhasin2** [comment]
Made a epic branch for this to be merged into.

a) There are todos in the js code, I am wondering what is the best way for us to track these .js component areas to be updated. 

```
Client/Assets/CC_Script/CreditCardAutofill.js
Client/Assets/CC_Script/CreditCardRuleset.mjs
Client/Assets/CC_Script/FieldScanner.mjs
Client/Assets/CC_Script/FormAutofillHeuristics.shared.mjs
Client/Assets/CC_Script/fathom.mjs
Client/Assets/CC_Script/shims.js
```

b) Do you have any way in which we can document the changes here?

@issammani

**Review by nbhasin2 — APPROVED** [review]
This is required for the following tickets

a) [FXIOS-6124](https://mozilla-hub.atlassian.net/browse/FXIOS-6124) - Cleanup of the Todos
b) [FXIOS-6089](https://mozilla-hub.atlassian.net/browse/FXIOS-6089) - Add fathom so it is testable

**Comment by issammani** [comment]
> Made a epic branch for this to be merged into.
> 
> a) There are todos in the js code, I am wondering what is the best way for us to track these .js component areas to be updated.
> 
> ```
> Client/Assets/CC_Script/CreditCardAutofill.js
> Client/Assets/CC_Script/CreditCardRuleset.mjs
> Client/Assets/CC_Script/FieldScanner.mjs
> Client/Assets/CC_Script/FormAutofillHeuristics.shared.mjs
> Client/Assets/CC_Script/fathom.mjs
> Client/Assets/CC_Script/shims.js
> ```
> 
> b) Do you have any way in which we can document the changes here?
> 
> @issammani

Since this code was intended to explore and make sure that our code can be shared with iOS there were a lot of shortcuts taken in order to confirm this. I am working on a series of patches on our side that have these removed and fixed properly. I am keeping track of that in those patches. I will share a link with you once it's upstream 😄

**Comment by nbhasin2** [comment]
@issammani Perfect!! I will merge this in and start doing some integration testing 
Next step will wait for your patches to land and will update.

**Comment by nbhasin2** [comment]
Something is up with BR as I am seeing the following

image

**Comment by nbhasin2** [comment]
Had to abort build, and last commit I pushed is for lint fixes

**Pull request merged**
