### PR TITLE
Bug 1393307 - Add SimpleToast confirm messages for actions

### PR DESCRIPTION
**Pull request by joeyg**
This PR introduces confirm messages for: Add to reading list, copy url, add bookmark, and remove bookmark. I am not sure about the copy, the strings could probably be better.

Screencast: http://recordit.co/WDBUH5INK2

### CODE REVIEW

**Comment by farhanpatel** [comment]
@joeyg There a few things we need to fix looking at the UI a bit more closely. 
- The color of the bar should be #0a84ff (should apply to all toasts)
- The height of the bar should be the same as the bottom bar (should apply to all toasts)
- The toast shouldnt cover the bottom toolbar. It should appear above the toolbar.

**Comment by joeyg** [comment]
@farhanpatel Updated PR based on the UI instructions above. Let me know if I didn't interpret them correctly. Here is an updated screencast: http://recordit.co/WDBUH5INK2

**Comment by joeyg** [comment]
Thanks @farhantatel!

**Comment by farhanpatel** [comment]
Looks like there might have been a regression from your patch. Do you have a chance to look at them @joeyg 
https://bugzilla.mozilla.org/show_bug.cgi?id=1406894
https://bugzilla.mozilla.org/show_bug.cgi?id=1406916

**Comment by joeyg** [comment]
Ah i'll fix that.

**Comment by joeyg** [comment]
@farhanpatel pull request for the display fixes is #3276. Is there a daily or beta build distribution list I could be added to or is all testing done off local builds?

**Comment by farhanpatel** [comment]
Yea there sure is. What is your email?

**Comment by joeyg** [comment]
joe.gasiorek@gmail.com

**Pull request merged**
