### PR TITLE
fix "Deprecated usage init(forReadingWith:)"

### PR DESCRIPTION
**Pull request by muhasturk**
Doc
https://developer.apple.com/documentation/foundation/nskeyedunarchiver/2962883-init

Deprecated iOS 12
https://developer.apple.com/documentation/foundation/nskeyedunarchiver/1410862-init

### CODE REVIEW

**Comment by muhasturk** [comment]
Hey, it will be merged or not? :)

**Comment by electricRGB** [comment]
@muhasturk Heya. Thanks so much for your contribution. Due to our current priorities, we're rather behind or reviewing, and merging contributor PRs. The team is hoping to get some breathing room by the end of the year, however, and go through a large portion of PRs.

**Comment by lmarceau** [comment]
Closed and reopened PR to trigger bitrise build

**Comment by lmarceau** [comment]
BR was failing, merged main in branch

**Comment by lmarceau** [comment]
Hi @muhasturk. BR indicates that the test `testPrivateTabsAreArchived` is failing. I investigated a bit, and here's what I noted:

First thing is, [Apple says](https://developer.apple.com/documentation/foundation/nskeyedunarchiver/2962883-init) that by adapting existing code to this new initalizer, we should make sure we conform to [NSSecureCoding](https://developer.apple.com/documentation/foundation/nssecurecoding). In our case that means the `SavedTab` class should conform to this protocol.

I also found that decoding the object will probably need to be using `func decodeObject(of classes: [AnyClass]?, forKey key: String)` instead of `decodeObject(forKey key: String)`. So in other words, the line 
`guard let tabs = unarchiver.decodeObject(forKey: SiteArchiver.tabsKey) as? [SavedTab] else {` would become `guard let tabs = unarchiver.decodeObject(of: [NSArray.self, SavedTab.self], forKey: SiteArchiver.tabsKey) as? [SavedTab] else {`. The array of SavedTabs isn't decoded for me otherwise. 

Let me know if you need any help or other indications about this! Thanks a lot !

**Comment by lmarceau** [comment]
Hello! I took the liberty of making my requested changes for this PR so we can move forward with this improvement. Your contribution will be in there of course! I'm closing this PR to reopen a new one. I'll link it as soon as it's opened.

**Comment by lmarceau** [comment]
Here is the PR: https://github.com/mozilla-mobile/firefox-ios/pull/9699

**Pull request closed without merging**
