### PR TITLE
Fix #7953 - Update test for Googla as default Top Site

### LINKED ISSUE #7953: [XCUITest] Modify tests accordingly once Google is added as a top site by default
There are several tests that may be affected by this change. Mainly in ActivityStream Test suite.

Depens on PR that has to be open but WIP

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2723)

### PR DESCRIPTION
**Pull request by SimonBasca**
Updated Activity stream test for #7953

### CODE REVIEW

**Comment by isabelrios** [comment]
@SimonBasca Can you also try running the tests for the whole scheme, you should be able to do that by changing this line: https://github.com/mozilla-mobile/firefox-ios/blob/main/bitrise.yml#L2261 with `RunAllXCUITests`

**Comment by SimonBasca** [comment]
> @SimonBasca Can you also try running the tests for the whole scheme, you should be able to do that by changing this line: https://github.com/mozilla-mobile/firefox-ios/blob/main/bitrise.yml#L2261 with `RunAllXCUITests`

@isabelrios I've re-run the Fennec_Enterprise_XCUITests test plan locally from the terminal. I didn't had any failures related to the Activity Stream tests. 
What should be the next step with this PR?

**Comment by isabelrios** [comment]
I think it is fine to land it, let's monitor the results 👁️  Thanks!

**Review by isabelrios — APPROVED** [review]

**Comment by isabelrios** [comment]
If you agree @SimonBasca, let's fix the conflict, rebase and if tests still green, I'm fine with merging this. Sorry this was implemented while ActivityStream tests were really flaky and now that they are stable enough we can revisit this.

**Comment by SimonBasca** [comment]
Closing and doing a new PR

**Pull request closed without merging**
