### PR TITLE
#9308 Counts on home sections

### PR DESCRIPTION
**Pull request by lmarceau**
### Overview
PR in reference to [Jira](https://mozilla-hub.atlassian.net/browse/FXIOS-3284) and Github issue https://github.com/mozilla-mobile/firefox-ios/issues/9308

Counts on home sections.

### CODE REVIEW

**Comment by lmarceau** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

_1) What questions will you answer with this data?_

It will answer how many users use the zero search page sections.

_2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?_

This will help us review the usefulness of the zero-search page, and determine which section are most important to keep.

_3) What alternative methods did you consider to answer these questions? Why were they not sufficient?_

There’s no other alternative in place to answer this question. There is already some telemetry in place to measure if sections are used on the home page, but there was nothing to know what was the origin of the home page creation (so whether it’s a zero-search origin or other).

_4) Can current instrumentation answer these questions?_

No.

_5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki._

_**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**_

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>User interacted with a zero-search page section</td>
    <td>Category 2</td>
    <td>#9308</td>
  </tr>
  <tr>
    <td>User opened a zero-search page</td>
    <td>Category 2</td>
    <td>#9308</td>
  </tr>
</table>

_6) How long will this data be collected?  Choose one of the following:_

Until 2022-05-01.

_7) What populations will you measure?_

All release channels and locales.

_8) If this data collection is default on, what is the opt-out mechanism for users?_

Users can opt of of data collection by disabling Usage and technical data from _Settings → Send Usage Data_.

_9) Please provide a general description of how you will analyze this data._

Glean 

_10) Where do you intend to share the results of your analysis?_

Only on Glean, mobile teams and BD have internal access.

_12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?_

No.

**Comment by electricRGB** [comment]
Looks good to me from my end, but I helped on this, so cannot review.

**Comment by lmarceau** [comment]
@dnarcese Could you have a look at the data collection review?

**Comment by dnarcese** [comment]
oops I had the review in the comment but I didn't submit it

r+
# Data Review Form

_1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?_ 

Yes, telemetry is documented at https://dictionary.telemetry.mozilla.org/apps/firefox_ios

_2) Is there a control mechanism that allows the user to turn the data collection on and off?_ 

Yes, Firefox iOS provides data controls in the app settings

_3) If the request is for permanent data collection, is there someone who will monitor the data over time?_

This should be re-reviewed w/ Ashley Thomas every 6mo

_4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?_

Type 2

_5) Is the data collection request for default-on or default-off?_

Default on

_6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?_

No

_7) Is the data collection covered by the existing Firefox privacy notice?_ 

Yes

_8) Does the data collection use a third-party collection tool?_ 

No

**Review by nishant2718 — CHANGES_REQUESTED** [review]
I missed this earlier - I think the bug field in`metrics.yaml` needs to point to the Github issue instead of the JIRA link.

**Review by nishant2718 — APPROVED** [review]
Looks good!

**Pull request merged**
