### PR TITLE
Bugfix #9546 [v97]: Handle JS inside URLBar

### PR DESCRIPTION
**Pull request by nishant2718**
# Overview

This PR addresses [this JIRA ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-3450) and #9546. 

## Testing
Follow the steps in #9546. But instead of an error page, it should execute a search (checked with product). 

## Note
This brings to attention the `permanentURISchemes` property - it looks like we'll have to update this based on the latest revision (done 3 Jan 2022). That can be done in a separate ticket.

### CODE REVIEW

**Comment by nishant2718** [comment]
Looks like one failing test that passes locally, `testPrivateTabsAreArchived`. Rerunning the build pipeline to double check.

**Comment by nishant2718** [comment]
Tests pass, but don't reflect here. 

image

**Review by lmarceau — APPROVED** [review]
LGTM, but can you open a separate ticket for the permanentURISchemes review if that wasn't already done?

**Comment by nishant2718** [comment]
> LGTM, but can you open a separate ticket for the permanentURISchemes review if that wasn't already done?

Done! https://github.com/mozilla-mobile/firefox-ios/issues/9750

**Pull request merged**
