### PR TITLE
Bug 1492496 - XCUITests: Re-enable Drag&Drop tests

### PR DESCRIPTION
**Pull request by SimonBasca**
*Thank you for submitting a pull request, your contributions are greatly appreciated!*

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [ ] My patch has a standard commit message that looks like `Bug 12345678 - This fixes something something`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

**Comment by garvankeeley** [comment]
Note that tab reordering is being disabled for 14: https://github.com/mozilla-mobile/firefox-ios/pull/4273

**Comment by isabelrios** [comment]
And also in master, so @SimonBasca let's disable the tests affected so that they don't false fail before merging. Thanks!

**Comment by isabelrios** [comment]
Oh sorry, I was confused by the title of the PR, is not about all the DragAndDrop but the Tabs re-arrange in TabTray...if that is still off in master and v14.x, then I guess we can close this PR without merging because we can't enable any test....@SimonBasca I'm really sorry about this, my mistake :(

**Comment by isabelrios** [comment]
Or well @SimonBasca, we can use this PR to just fix the Drag&Drop test: testTryDragAndDropBookmarkToURLBar

**Comment by SimonBasca** [comment]
Closing this pull request without merging as reordering tabs is being disabled for 14.x .

**Comment by isabelrios** [comment]
Closing this PR, work done in: https://github.com/mozilla-mobile/firefox-ios/pull/4285

**Pull request closed without merging**
