### PR TITLE
Refactor FXIOS-5904 [v112] made GroupedTabContainerCell delegate weak

### PR DESCRIPTION
**Pull request by TwizzyIndy**
References Issues: #13442 

I tried to make `GroupedTabContainerCell`'s delegate `weak` for avoiding reference cycles. Please review and let me know if I'm wrong.

### CODE REVIEW

**Comment by adudenamedruby** [comment]
Heya. This is good work. Would be great work if we could add a unit test for memory leaks. :)

**Comment by TwizzyIndy** [comment]
Thanks, @adudenamedruby. Could you please suggest some ideas for writing unit tests? I've no idea where to add them.

**Comment by adudenamedruby** [comment]
Happy to! In the `Tests/ClientTests` folder, you'll probably want to create a new file called GroupedTabContainerCellTests. Then write a test where you assign it to a variable, and then test that, when deinitialized, that variable is nil.

[Here's an article](https://levelup.gitconnected.com/detecting-memory-leaks-using-unit-tests-in-swift-c37533e8ee4a) that might help you understand the general process. I'd also recommend searching the project for `trackForMemoryLeaks` and seeing how it's been implemented in other places. :)

**Comment by adudenamedruby** [comment]
@lmarceau comment on adding the delegate to the test in the other PR also applies here :)

Thanks. :)

**Pull request closed without merging**
