### PR TITLE
FXIOS-840 ⁃ Remove Earl Grey, use KIF instead

### PR DESCRIPTION
**Pull request by isabelrios**
PR to try to fix the issues with Earl Grey and Xcode 12 by chaning it for KIF

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-840)

### CODE REVIEW

**Comment by isabelrios** [comment]
This is the first approach to remove all references to EarlGrey from our UI tests. 
There are some workarouds I had to use in order to get similar gestures to get the tests working. I know that can be improved, but was going to take longer, so we can add follow ups for that. 
I have some in mind:

- Set correctly the dismissFirstRun. These UI tests are not reset from one test to the next one. Currently the first run is dismissed in the first test, this work for the CI but in case anyone wants to launch the tests locally, we need a way to dismiss it or not depending on its existence. I'm working on that already.
- Improve gesture to close library panel
- ...

**Comment by isabelrios** [comment]
@nbhasin2 how can I try this on xcode 12/ ios 14 branch? I tried to set xcode 12 on BB directly on that PR but if fails to build Glean (I think there are some workaround needed for that?) not sure what would be the best way to continue from here to test on the correct environment...

**Comment by nbhasin2** [comment]
@isabelrios for iOS14 you can point it to main branch. There is an XCode 12 B5 version of cartfile and carthage resolved. If you push that temporary commit to your repo it should build with B5

- Carfile and Carthage.resolved can give issues so rename those to Carfile.old and Carthage.resolved.old
- Then remove the .b5 from Cartfile.b5 and Carfile.resolved.b5

**Comment by isabelrios** [comment]
I have to close this PR in favor of https://github.com/mozilla-mobile/firefox-ios/pull/7281 since I was not able to change the PR on BB to run on main instead of on main-dev and was failing to build...sorry about that

**Comment by isabelrios** [comment]
Removing reviewers from this PR to not to cause confusion, the other one is the good one to review. Thanks and sorry for the changes!

**Pull request closed without merging**
