### PR TITLE
Bugfix MTE-669 [v112] Specify the last visited sites are under topSitesCells

### PR DESCRIPTION
**Pull request by clarmso**
The bookmark label appears in more than one place now. The test does not know which label to long press.

Now we specify the bookmark label under `topSitesCells` is the one desired.

https://mozilla-hub.atlassian.net/browse/MTE-669

### CODE REVIEW

**Review by isabelrios — APPROVED** [review]
LGTM
Let's run the changes on Bitrise to be sure the tests are green there

**Comment by mte-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Edited 1 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 0 files</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 97a600cb2c98feac5d2aa13546b0304ee442ce4a
</p>

**Comment by clarmso** [comment]
👀 Looking...there are too many warnings.

```
+ [[ Number of warnings is:       27. This is greater than build threshold: 27 == *\g\r\e\a\t\e\r* ]]
+ echo 'Failure, the number of warnings increased'
Failure, the number of warnings increased
```

**Comment by clarmso** [comment]
> 👀 Looking...there are too many warnings.
> 
> ```
> + [[ Number of warnings is:       27. This is greater than build threshold: 27 == *\g\r\e\a\t\e\r* ]]
> + echo 'Failure, the number of warnings increased'
> Failure, the number of warnings increased
> ```

Merging the changes in the unit test from main. :)

**Pull request merged**
