### PR TITLE
Refactor MTE-572 Ignore files changed in branches

### PR DESCRIPTION
**Pull request by isabelrios**
With this PR we will ignore this step for branches different than main for now, we will always run the UI tests there

### CODE REVIEW

**Comment by isabelrios** [comment]
Please see this PR where I was using a base branch different than main: https://github.com/mozilla-mobile/firefox-ios/pull/13160#issuecomment-1422256252 to verify that the step did not fail

**Comment by mte-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Edited 1 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 0 files</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 72516fefb34e728dc20b63922bf1e7dc8a21dab1
</p>

**Review by yoanarios — APPROVED** [review]
LGTM 🚀

**Comment by isabelrios** [comment]
@yoanarios all tests passed on Bitrise in that workflow when re-trying it. Could you land this PR as it is? or should I re-trigger the full pipeline?

**Comment by yoanarios** [comment]
> @yoanarios all tests passed on Bitrise in that workflow when re-trying it. Could you land this PR as it is? or should I re-trigger the full pipeline?

If all test pass I think we could landed

**Comment by yoanarios** [comment]
Landing this PR after discussion

**Pull request merged**
