### PR TITLE
Added FXIOS-5674 [v111] Enable tests for the logger framework

### PR DESCRIPTION
**Pull request by OrlaM**
[FXIOS-5679](https://mozilla-hub.atlassian.net/browse/FXIOS-5679)
#13090

### CODE REVIEW

**Comment by isabelrios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Edited 2 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 0 files</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 131c332c7a994dab3106742acf8c82e83ebd98d4
</p>

**Review by lmarceau — APPROVED** [review]

**Review by isabelrios — APPROVED** [review]
LGTM, although in this build these tests did not run ([tests result](https://app.bitrise.io/build/cdcceef3-d39d-49c6-a9b8-a8a4babf5a91)). 
Let's land this as this is the proper change to add them and monitor from main.

**Comment by OrlaM** [comment]
I think there is something funny going on with how the test results are being reported for the libraries in BrowserKit. If I download the test results artifact I can see the tests did run.

image

There is a similar issue with Common and SiteImageView too, the tests run but they don't seem to show up in BR or the code coverage report. 

image

**Comment by OrlaM** [comment]
This is green on BR 
image

I'll merge this since tests are at least running for now.

**Pull request merged**
