### PR TITLE
Add FXIOS-9129 - Add entry point files for address edit UI

### PR DESCRIPTION
**Pull request by issammani**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-9129)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/20237)

## :bulb: Description
This PR:
- Adds three entry point files for the address edit UI.
- Adds `AddressFormManager` to webpack bundle.
- Adds necessary files to package resources.
- Adds initial styling.
- Adds generated files to `.gitignore`.

⚠️ Let's wait for this PR https://github.com/mozilla-mobile/firefox-ios/pull/20249 to merge first before merging this one. Merging this one first will cause errors.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by issammani** [comment]
Added the do not merge label, since this PR needs  https://github.com/mozilla-mobile/firefox-ios/pull/20249 to be merged first.

**Comment by isabelrios** [comment]
Should we add the path to those files to trigger the github action to run the tests?

**Review by nbhasin2 — APPROVED** [review]
Approving but yes lets wait for https://github.com/mozilla-mobile/firefox-ios/pull/20249 to be merged

**Comment by issammani** [comment]
> Should we add the path to those files to trigger the github action to run the tests?

No no need. These files will not be covered by the tests for now.

**Comment by issammani** [comment]
https://github.com/mozilla-mobile/firefox-ios/pull/20249https://github.com/mozilla-mobile/firefox-ios/pull/20249https://github.com/mozilla-mobile/firefox-ios/pull/20249 is now merged. @nbhasin2 can you please trigger a bitrise run in this ?

**Pull request merged**
