### PR TITLE
FXIOS-1828, FXIOS-1811 - Added top site probes and tracking to measure Pocket impressions and key metrics

### PR DESCRIPTION
**Pull request by nbhasin2**
Tracking to help understand how users use top site, pocket tiles and Firefox home page

### CODE REVIEW

**Comment by nbhasin2** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?

    - How many users interact with top sites
    - Which top sites are most valuable
    - What is the click-through rate for top sites (total impressions vs total clicks)

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:
    - These events will help us understand the usage of top sites, so we can confirm it's valuable enough to users to keep front & centre on the home page.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

   None

4) Can current instrumentation answer these questions?

   No

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.   

Category 2

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>Top site tile pressed with extras as Tile Type (google, suggested, user-added or history-based) and position of tile.</td>
    <td>Category 2</td>
    <td>https://jira.mozilla.com/browse/FXIOS-1828</td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
Available in metrics.yaml and https://dictionary.telemetry.mozilla.org/apps/firefox_ios

7) How long will this data be collected?  Choose one of the following:

    Until 2021-12-02 (approximately 6 months) so we can gather enough data

8) What populations will you measure?
All

9) If this data collection is default on, what is the opt-out mechanism for users?
Default on, users can opt out in settings

10) Please provide a general description of how you will analyze this data.
Using Glean / Amplitude

11) Where do you intend to share the results of your analysis?
Only on Glean, Amplitude and with mobile teams.

12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so:
None

**Comment by nbhasin2** [comment]
image

The test that failed on BR is passing locally. I am going to run it again

**Comment by nbhasin2** [comment]
@boek its ready for both data review + regular review 

This time another unrelated test failed on BR 🤷🏼‍♂️

**Review by dnarcese — APPROVED** [review]

**Comment by dnarcese** [comment]
r+
# Data Review Form

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Yes, telemetry is documented in `docs/metrics.md`

2) Is there a control mechanism that allows the user to turn the data collection on and off? 

Yes, Firefox iOS provides data controls in the app settings

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

This should be re-reviewed w/ Ashley Thomas every 6mo

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Type 2

5) Is the data collection request for default-on or default-off?

Default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

No

7) Is the data collection covered by the existing Firefox privacy notice? 

Yes

8) Does the data collection use a third-party collection tool? 

No

**Pull request merged**
