### PR TITLE
Fix #6846 - Added event to track start search button press

### LINKED ISSUE #6846: Search icon on new tab toolbar
### Vision

As a user, I want a button on the bottom toolbar to start a search so that I can access the search bar without stretching my thumb across to the top of the screen

### Acceptance Criteria

* Search icon added to the bottom toolbar in portrait ([mock](https://app.abstract.com/share/32f6c003-3908-4ca5-81e7-37137c04eee3?collectionLayerId=f5518f50-f1e3-4e72-92ac-bd51a887eaca&mode=design))
* Tracking adding for number of clicks on the search icon and the searchbar from the homescreen to compare usage
  * Tracking must follow privacy policy
  * Should confirm with data science if this should go to Amplitude or just internal telemetry

### Not included

* The icon should only be included on the toolbar in the new tab screen. It should not appear in the toolbar when scrolling a webpage
* A/B test not needed as success will be measured based on clicks of new button
* This does not include iPad, as there is no bottom toolbar

**Not Included**

* This is not needed in landscape mode, so changes are only needed for portrait

### PR DESCRIPTION
**Pull request by nbhasin2**

### CODE REVIEW

**Comment by nbhasin2** [comment]
Tagging @chutten for data review

**Comment by travis79** [comment]
> Tagging @chutten for data review

Please fill out the required form from [here](https://github.com/mozilla/data-review/blob/master/request.md) before requesting review from a data steward.  For an example of what a data review should look like, see here: https://bugzilla.mozilla.org/show_bug.cgi?id=1635427 or here: https://github.com/mozilla-lockwise/lockwise-android/pull/1196#issuecomment-634214031

**Comment by nbhasin2** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?
Number of times user taps on the newly added search button (magnifying glass) at the bottom of the view.

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

This in turn should increase the searches performed by the user as tapping the button takes user to the addressbar which is where user starts a search or goes to another website.  

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

This is a new button and we don't have any metrics for it to measure.

4) Can current instrumentation answer these questions?

Not really as this button is just added so current instrumentation cannot determine the number of times user taps on the button. One could say we can tap into search analytics but then again it doesn't tie with the new button thats added right now.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>Legacy telemetry start search button tap</td>
    <td>Category 2</td>
    <td>https://github.com/mozilla-mobile/firefox-ios/issues/6846</td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
N/A

7) How long will this data be collected?  Choose one of the following:
For the lifetime of the Firefox iOS application or until we have the new start search button in the app.

8) What populations will you measure?

All users

9) If this data collection is default on, what is the opt-out mechanism for users?

In Firefox iOS there is a preference for telemetry labeled "Send Usage Data" that will be used as the opt-out mechanism.

10) Please provide a general description of how you will analyze this data.

We will look at how many times user taps on the new start search button and b/w v27 to upcoming v28 if we see increase in search traffic. 

11) Where do you intend to share the results of your analysis?

Mozilla internal channels with our PM

**Comment by nbhasin2** [comment]
@travis79 Could I request review on the above form and see if I am missing anything

**Comment by travis79** [comment]
@nbhasin2 Looks good on everything but two items:
- Item 6, can you add a line to /docs/telemetry.md and link to that doc here?  That should satisfy this requirement
- Item 7, permanent collections require an individual contributor email as a metric owner so could you provide that info for whoever will take responsibility for this metric. For time limited collections, a team email is sufficient, you could say this will be collected for 6 months if that is appropriate.

**Comment by nbhasin2** [comment]
Hi @chutten @travis79 - I have added the data request form. Let me know if I missed anything and if I can get a review on it. 

Thanks

**Comment by chutten** [comment]
PRELIMINARY NOTES

There is no individual listed as responsible for this collection. Collections that do not automatically expire require an individual responsible for them. I will assume @nbhasin2 is responsible.

DATA COLLECTION REVIEW RESPONSE:

    Is there or will there be documentation that describes the schema for the ultimate data set available publicly, complete and accurate?

Yes. https://github.com/mozilla-mobile/firefox-ios/blob/bb38e861f68978e463176f6390ba26c30d825173/Docs/telemetry.md

    Is there a control mechanism that allows the user to turn the data collection on and off?

Yes. This collection is can be controlled through Firefox's Preferences.

    If the request is for permanent data collection, is there someone who will monitor the data over time?

Yes, @nbhasin2 is responsible.

    Using the category system of data types on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 2, Interaction.

    Is the data collection request for default-on or default-off?

Default on for all channels.

    Does the instrumentation include the addition of any new identifiers?

No.

    Is the data collection covered by the existing Firefox privacy notice?

Yes.

    Does there need to be a check-in in the future to determine whether to renew the data?

No. This collection is permanent.

---
Result: datareview+

**Comment by nbhasin2** [comment]
Will take responsibility for this @chutten, thank you :)

**Comment by nbhasin2** [comment]
Tagging @garvankeeley for final code review

**Pull request merged**
