### PR TITLE
Revert "Refactor [v116] auto update credential provider script (#15526)"

### PR DESCRIPTION
**Pull request by nbhasin2**
This reverts commit 5d2e46452b22c83a0ce7f24bd009f28c7e30aa97 as this is broken on main due to refactoring but we will be removing this commit from v116 until a fix lands on main. To avoid any confusion we are reverting it on main as well

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-6679)
[Github PR](https://github.com/mozilla-mobile/firefox-ios/pull/15526)

## :pencil: Checklist
You have to check all boxes before merging
- [ ] Filled in the above information (tickets numbers and description of your work)
- [ ] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by nbhasin2** [comment]
cc @petruSt24

**Comment by nbhasin2** [comment]
This should also be backported to v116

**Review by lmarceau — APPROVED** [review]

**Comment by nbhasin2** [comment]
@mergify backport release/v116

**Comment by nbhasin2** [comment]
cc @galich

**Pull request merged**
