### PR TITLE
Bugfix FXIOS-6096 [v114] The 'Not now' button overlaps the 3 dots

### PR DESCRIPTION
**Pull request by PARAIPAN9**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-6096)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/13796)

### Description
Remove the pageControlBottomPadding constant so that the 'Not now' button remains above the 3 dots.

| iPhone  | iPad | 
| ------------- | ------------- |
| iPhoneOnboarding | OnboardingiPad |

### Pull requests checks where applicable
- [x] Fill in the three TODOs above (tickets number and description of your work)
- [x] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [ ] Unit tests written and passing
- [ ] Documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by PARAIPAN9** [comment]
Tagging @Kate-Galetski for UX verification

**Review by yoanarios — APPROVED** [review]

**Comment by lmarceau** [comment]
Build is green [here](https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/03964d96-cdad-4b19-a9ad-703766827fdc)

**Comment by lmarceau** [comment]
Seems we're missing UX approval to be able to merge this. @PARAIPAN9 let us know when that's done.

**Comment by Piratesarereal** [comment]
There is still a padding issue for this. But here is a [design](https://www.figma.com/file/7J6gh5D8DbGTExxskKdn3T/Mobile-Onboarding?node-id=6908%3A71902&t=17xYGWLFxI2OK30i-1) for the iPad implementation.

**Comment by Piratesarereal** [comment]
Looks good to me and solves the initial bug. 
I am approving under the understanding that @CatalinNeculaide will be working on a new design for Ipad based on the designs provided in [Figma](https://www.figma.com/file/7J6gh5D8DbGTExxskKdn3T/Mobile-Onboarding?node-id=6908%3A71902&t=6e5UYolWrPoPkaik-1).

**Pull request merged**
