### PR TITLE
Bugfix FXIOS-6575 [v114.1] Shadow gradient gets stuck at the bottom of the screen

### PR DESCRIPTION
**Pull request by PARAIPAN9**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-6575)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/14720)

### Description
This PR fixes the problem when the shadow gradient gets stuck to the bottom of the screen if you scroll slowly

### Pull requests checks where applicable
- [x] Fill in the three TODOs above (tickets number and description of your work)
- [x] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [ ] Unit tests written and passing
- [ ] Documentation / comments for complex code and public methods

### CODE REVIEW

**Review by adudenamedruby — APPROVED** [review]
@PARAIPAN9 have you gotten on a call with @piratesarereal to walk through the updates? If not, let's do that, and then, we can have another PR to re-remove the feature flag for page zoom.

**Comment by PARAIPAN9** [comment]
Yes, sounds good, we will!!

**Comment by Piratesarereal** [comment]
Looks good to me. Thank you for sharing the video with me.

**Comment by adudenamedruby** [comment]
@Mergifyio backport release/v114

**Comment by adudenamedruby** [comment]
@mergifyio backport release/v115

**Pull request merged**
