### PR TITLE
Bugfix FXIOS-4520 [v105] Jump back in crash

### PR DESCRIPTION
**Pull request by lmarceau**
# [FXIOS-4520](https://mozilla-hub.atlassian.net/browse/FXIOS-4520) https://github.com/mozilla-mobile/firefox-ios/issues/11227
This PR fixes two possible reasons for crash on the homepage jump back in. Problem 1 is related to problem 2, but was causing it to happen more frequently

### Problem 1
Jump back in section relies on `recentlyAccessedNormalTabs` from tabManager. When we update the tab data, it fetches the `normalTabs` and check their `lastKnownUrl`. If the `lastKnownUrl` is nil, then the tab isn't part of the jump back in data. The thing is, when we delete tabs (which trigger a selection of a new tab if the deleted tab was the selected one) the `lastKnownUrl` can be nil since the session data is being recreated. This means the tab is now not part of the jump back in data anymore. In other words, when we delete tabs rapidly on iPad, we can't update our data rapidly since the tab session data can be nil. One way of solving this is to update the data later when the homepage is asked to be shown. This means we might see some tabs being added into the section once the data is updated, but I'm good with that if it means we're not crashing.

### Problem 2 
Sometimes the section count or number of items in a section was out of sync with the actual data. I.e. the layout was expecting a certain number of sections/cells and the data wasn't corresponding. This inconsistent state was caused by a refresh from the adaptor in the middle of a reload of the collection view. Here was the flow with an example:
- I have 2 jump back in tabs with a homepage
- I delete rapidly all the tabs from the top tabs on iPad
- This triggers a reload of the homepage
- Section layout is called and jump back in still has data at that point (with 1 or 2 tabs depending on the speed we deleted things). The collection view believes it has a jump back in section.
- Number of items from the collection view is called, triggering a refresh of the data with the `traitCollection`. 
- Turns out there was no jump back in tabs anymore after that refresh
- Crash since the collection view expected 1 or 2 tabs within a section that it turns out no longer exists.

The fix for this that I propose is that we call refreshData before calling reloadData. Any reload will have a fixed state throughout it's update.

### CODE REVIEW

**Comment by lmarceau** [comment]
Opening as draft, still want to test this more tomorrow to make sure this is a proper solution

**Comment by davidldennison** [comment]
I'm actually experiencing the same thing, but on Windows 10.

**Comment by OrlaM** [comment]
I've tried a bunch of times and I cannot repo the crash on this branch. Great work! 👏

**Comment by lmarceau** [comment]
@davidldennison Hi, thanks for your input. Firefox on Windows 10 is another project that doesn't share code with Firefox for iOS. I would suggest that you write on the [support forum](https://support.mozilla.org/en-US/products/firefox) or [Bugzilla](https://bugzilla.mozilla.org/home) for any bugs/issues/questions you have on this platform.

**Review by OrlaM — APPROVED** [review]
LGTM

**Comment by lmarceau** [comment]
Build is green [here](https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/06c6eb00-02e6-4fb0-9eae-7120775f600a)
Screen Shot 2022-08-16 at 2 13 39 PM

**Review by thatswinnie — APPROVED** [review]

**Pull request merged**
