### PR TITLE
Bug 1355525 - Drop title when marking a history item as deleted

### PR DESCRIPTION
**Pull request by Colemalban**

### CODE REVIEW

**Comment by farhanpatel** [comment]
### SwiftLint found issues

#### Warnings

File | Line | Reason |
| --- | ----- | ----- |
SQLiteHistory.swift | 838 | Force casts should be avoided. 
SQLiteHistory.swift | 881 | Force casts should be avoided. 
SQLiteHistory.swift | 886 | Force casts should be avoided. 
SQLiteHistory.swift | 984 | Force casts should be avoided. 
SQLiteHistory.swift | 1004 | Force casts should be avoided. 
SQLiteHistory.swift | 1005 | Force casts should be avoided. 
SQLiteHistory.swift | 1006 | Force casts should be avoided. 
SQLiteHistory.swift | 1007 | Force casts should be avoided. 
SQLiteHistory.swift | 1047 | Force casts should be avoided. 
SQLiteHistory.swift | 1049 | Force casts should be avoided. 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Colemalban** [comment]
Thanks for the feedback! When those changes are made, should I resubmit the pull request on Bugzilla for review?

**Comment by rnewman** [comment]
Yes please, @Colemalban. Just flip the flag back to `r?`.

**Comment by rnewman** [comment]
Hey @Colemalban, any news on this?

**Comment by Colemalban** [comment]
Hi @rnewman . Work/other things ramped up quite a bit over the summer and this slipped from my mind. Does this still need finishing/ has someone else taken care of it? Things have slowed down so I was hoping to make time to contribute to projects again and would be happy to finish up anything. Thanks!

**Comment by rnewman** [comment]
@Colemalban as far as I can tell, this is still valid; please do wrap it up and we can get it landed! Thanks!

**Comment by farhanpatel** [comment]
Closing stale PR.

**Pull request closed without merging**
