### PR TITLE
Bugfix #9361 Firefox share extension top toolbar is transparent

### PR DESCRIPTION
**Pull request by yusadogru**
Bugfix #9361

### CODE REVIEW

**Comment by electricRGB** [comment]
Looks good to me. I can approve, run BR, and can be merged after a rebase to fix conflicts. :)

**Comment by yusadogru** [comment]
I fixed conflict, is it conflict again?

**Comment by electricRGB** [comment]
Heya. Yeah, you might have to rebase again. We changed some theme stuff around to accomodate the new theming system we're adding. Looking like BR is failing here:
Screen Shot 2021-11-08 at 10 16 52 AM

I believe you'll have to update that `Theme` to `ShareTheme`

**Comment by lmarceau** [comment]
@yusadogru Could you rebase to main? I would like to retrigger Bitrise to be able to move this forward :)

**Comment by yusadogru** [comment]
fixed @lmarceau

**Comment by lmarceau** [comment]
@yusadogru There's still the issue that electricRGB mentionned up here about `Theme` usage instead of `ShareTheme`. Could you fix it?

**Comment by yusadogru** [comment]
I did not realise that, fixed now @lmarceau

**Review by lmarceau — APPROVED** [review]
Thanks a lot @yusadogru for the contribution 😄 !

**Pull request merged**
