### PR TITLE
Bufix FXIOS-5068 [v108] Fix wallpaper size issues

### PR DESCRIPTION
**Pull request by polymathruby**
[JIRA Reference](https://mozilla-hub.atlassian.net/browse/FXIOS-5068)
#12124

Seems like everything is working with just these changes. 🤣

### CODE REVIEW

**Review by thatswinnie — APPROVED** [review]
Perfect 😆

**Comment by polymathruby** [comment]
Will wait to run BR until Thursday till we have credits in BR. :)

**Comment by OrlaM** [comment]
Will both the png and jpg resources continue to be hosted for a while after this change goes live? There could be weird bugs for older clients if they aren't, at least until 108 is rolled out to the majority of users.

**Comment by polymathruby** [comment]
yep. Leaving both online to make sure things work as intended for clients for a bit. :)

**Pull request merged**
