### PR TITLE
Test PR to check swiftlint

### PR DESCRIPTION
**Pull request by isabelrios**
Testing to check how to enable back swiftlint checks on CI

### CODE REVIEW

**Comment by lmarceau** [comment]
👋 About what we discussed earlier, I just wanted to post here what I used in the past. There's certainly a better way than mine in BR but here were the steps that I was doing in a previous project:
- The following step was used in Bitrise to get the JSON swiftlint report
Screen Shot 2022-03-31 at 3 30 50 PM

This translates to the following in the .yml:
```
    - swiftlint-extended@1:
        inputs:
        - reporter: json
        - linting_path: .
```

Then in a script step after the swiftlint step we were looking at this JSON report. If the JSON report was empty `[]` we would do nothing and the build could be green. If it wasn't empty then we were sending a message to Github (throught a webhook if I remember correctly) on the PR so the person can know which Swiftlint failure happened, and they can know what they need to fix to merge the PR 😄

**Comment by isabelrios** [comment]
Cool @lmarceau thanks for sharing! You know after our meeting I just realized that there could be a built-in step already in bitrise and was the first thing I was going to try this morning :) 
What I see more difficult is the integration with github to get the report, but if you got it previously there has to be a way and hopefully we will find the way to have it working here too 🤞

**Comment by isabelrios** [comment]
We can have a swiftlint check on github if we use the swiflint step..
Captura de pantalla 2022-04-01 a las 10 10 10

This may be helpful to have...

**Comment by isabelrios** [comment]
Closing as this is a test PR, the one is: https://github.com/mozilla-mobile/firefox-ios/pull/10371

**Pull request closed without merging**
