### PR TITLE
Fix for handling no network

### PR DESCRIPTION
**Pull request by LamourBt**
This pull request is addressing this issue #5798. 

## Issue 
We weren't able to see the error prompt for the `what's new` page because of the `webview.url` within `ErrorPageHelpher.loadPage` method had a nil value which caused an early exist. 

## Solution
Since the `loadPage` method also carries an URL argument (which represents whatever destination that the user wants to go to), thus in case of that `webview.url` is nil we can just point to url instead.

### CODE REVIEW

**Comment by nbhasin2** [comment]
Hi @LamourBt, 

Thanks for submitting the pull request. I was reviewing the code found a flow where we shouldn't present the no internet alert. 

Flow: 
- Enable airplane mode (make sure there is no network)
- Try to add a new tab

Result:
- Unable to add a new tab and am presented with no internet alert

Expected Result:
- Users should still be able to add a new tab even though there is no network

See below: 
image

**Comment by LamourBt** [comment]
@nbhasin2 Yesterday a decision was made #5798 tomorrow I will be working on the requested changes.

**Comment by nbhasin2** [comment]
> @nbhasin2 Yesterday a decision was made #5798 tomorrow I will be working on the requested changes.

Thanks @LamourBt 😊

**Comment by LamourBt** [comment]
@nbhasin2 The Issue is now fixed, you can try it now and also I have undone my previous changes.

**Comment by nbhasin2** [comment]
Tried on real devices (iPad and iPhone 11) with airplane mode and whats new page shows.

image

image

**Pull request merged**
