### PR TITLE
[Do Not Merge] Remove FXIOS-10813 [Nimbus] Close Remote Tabs Feature Flag

### PR DESCRIPTION
**Pull request by lougeniaC64**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-10813)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/23598)

## :bulb: Description
**NOTE:** This PR will need to be uplifted to v134 in order for closing remote tabs from iOS devices to work.

Because we haven't been able to test the close remote tab feature via the `closeRemoteTabs` feature flag, and because we no longer require this feature to be behind a feature flag to begin with, we are removing it. We are not sure if our inability to test this feature on Firefox Beta is due to an underlying feature flag/nimbus issue or improperly implementing the feature flag logic but we're opting for removal as it's no longer necessary.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [ ] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by lougeniaC64** [comment]
@mdotb-moz Just an FYI, these changes will need to be uplifted to v134, thanks!

**Review by skhamis — APPROVED** [review]
LGTM! Thanks for getting this out.

Also wanted to note we can probably also just remove the associated .yaml now?

- https://github.com/mozilla-mobile/firefox-ios/blob/52186d6e6d8ed4a1ffc7a6cdde07c0d5680eb502/firefox-ios/nimbus-features/remoteTabManagement.yaml#L4
- https://github.com/mozilla-mobile/firefox-ios/blob/52186d6e6d8ed4a1ffc7a6cdde07c0d5680eb502/firefox-ios/nimbus.fml.yaml#L37

However not sure how blocking that needs to be.

**Comment by lougeniaC64** [comment]
> LGTM! Thanks for getting this out.
> 
> Also wanted to note we can probably also just remove the associated .yaml now?
> 
>     * https://github.com/mozilla-mobile/firefox-ios/blob/52186d6e6d8ed4a1ffc7a6cdde07c0d5680eb502/firefox-ios/nimbus-features/remoteTabManagement.yaml#L4
> 
>     * https://github.com/mozilla-mobile/firefox-ios/blob/52186d6e6d8ed4a1ffc7a6cdde07c0d5680eb502/firefox-ios/nimbus.fml.yaml#L37
> 
> 
> However not sure how blocking that needs to be.

I knew I was missing something, thanks! I included those changes in this PR.

**Comment by lougeniaC64** [comment]
@mattreaganmozilla I added you as a reviewer after the github configuration selected Massimo and since you approved the last remote tab management iOS PR, but please feel free to pass the torch if needed. For context, we're removing the nimbus flag from remote tab management as it's no longer needed. This change will need to be uplifted to v134--thanks!

**Comment by mattreaganmozilla** [comment]
@lougeniaC64 This has Do Not Merge in the title. If that's still accurate would you mind adding a Do Not Merge label as well? (and you can probably remove it from the title)

**Comment by lougeniaC64** [comment]
> @lougeniaC64 This has Do Not Merge in the title. If that's still accurate would you mind adding a Do Not Merge label as well? (and you can probably remove it from the title)

@mattreaganmozilla Will do! This PR is a bit of a failsafe so I may end up closing it in a week or so FYI.

**Comment by adudenamedruby** [comment]
IF we do end up merging this, don't forget to backport!!! :)

**Pull request closed without merging**
