### PR TITLE
Fix #6271 - App crash when changing text size

### LINKED ISSUE #6271: App crash when changing text size
STR
1. Open bookmarks panel
2. Go to iOS settings and change the text size
3. Go back to firefox

On Beta 23.1 (17416) the app crashes and the crash reporter dialog pops up.
On Release 23.0, the app _does not_ crash but the bookmark panel closes.

### PR DESCRIPTION
**Pull request by KrystynaKruchkovska**
After text size change in IOS settings, we receive a notification "DynamicFontChanged" sent by the system and immediately we try to get bookmarks but it's not possible when the app is in background. To do it later, I added calling reloadData() on didBecomeActive()

### CODE REVIEW

**Comment by dnarcese** [comment]
hmm, I am still seeing the crash with this change - did yours stop crashing?

**Comment by KrystynaKruchkovska** [comment]
In my case, there was no crash but the bookmark list became empty after text size changed, I tested it on iPhone 7plus  IOS 13.3.1  version firefox 23.0 (screen recording attached ) and on the simulator the same result but after that change of commit 98875b5,  it works fine.
[issue6271.mp4.zip](https://github.com/mozilla-mobile/firefox-ios/files/4355109/issue6271.mp4.zip)

**Comment by dnarcese** [comment]
I'm not sure this is the right approach - it is fixed for the Bookmarks panel but not for the History panel. I am still seeing the content disappear until I restart the app.

**Comment by KrystynaKruchkovska** [comment]
Ok, I finally got my app crash at the History panel. So the reason for the crash is that history was resynced in the background and it is not allowed. I've just fixed it, could you retest?

**Comment by dnarcese** [comment]
Thanks for the contribution, but I don't think this resolves the issue, the fix is in #6881.

**Pull request closed without merging**
