### PR TITLE
Bugfix FXIOS-8249 [v124] Fixed inconsistent UI in ShareTo extension

### PR DESCRIPTION
**Pull request by tisumi99**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-8249)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/18331)

## :bulb: Description
Updated the UI so that the 2 ShareTo tabs are consistent with each other and to Firefox theme.
1. Styled the webpage name and url text in the menu tab with the theme color
2. Styled the tab title in the SendTo tab with the theme color
3. Styled the device list icon, text, and checkmark with the theme color
4. Styled the device list table and cell background with the theme color
5. Adjusted the left margin of the device list so that it is consistent with the menu list from the menu tab
6. Removed the row separators from the device list table so that it is consistent with the menu list

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [x] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [x] If needed I updated documentation / comments for complex code and public methods

image

### CODE REVIEW

**Comment by adudenamedruby** [comment]
@topotropic @Verdi Tagging for design review here before doing a code review, as this affects UI. :)

**Comment by adudenamedruby** [comment]
Design approved. Will take a look at code for this tomorrow. :)

**Review by adudenamedruby — APPROVED** [review]

**Comment by adudenamedruby** [comment]
Seems like this is failing on Swiftlint.

Screenshot 2024-01-30 at 10 17 04 AM

**Comment by tisumi99** [comment]
Removed whitespace from line 56 in DevicePickerViewController.swift and updated pull request.

**Comment by adudenamedruby** [comment]
Thanks so much for your contribution! :D

**Pull request merged**
