### PR TITLE
No Bug - Make Schemes Great Again (MSGA)

### PR DESCRIPTION
**Pull request by sleroux**
When you open the project, we get a bunch of useless schemes for the SQL targets and such. It would be really great if we could use our schemes again for building and testing our frameworks individually! I've been working on the Sync framework lately and I keep making my own scheme to unit test just Sync so I figured I'd just do this for all our framework schemes so it's easier to work with.

### CODE REVIEW

**Comment by sleroux** [comment]
Note: This is built on top of https://github.com/mozilla-mobile/firefox-ios/pull/2293

**Comment by farhanpatel** [comment]
### SwiftLint found issues

#### Warnings

File | Line | Reason |
| --- | ----- | ----- |
FxAContentViewController.swift | 192 | Colons should be next to the identifier when specifying a type. 
#### Errors

File | Line | Reason |
| --- | ----- | ----- |
FxAContentViewController.swift | 123 | Opening braces should be preceded by a single space and on the same line as the declaration. 
FxAContentViewController.swift | 93 | Lines should not have trailing semicolons. 
FxAContentViewController.swift | 127 | Lines should not have trailing semicolons. 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by farhanpatel** [comment]
Looks good. Will we need to change anything on BuddyBuild?

**Comment by farhanpatel** [comment]
I think while you are working on these changes can you add the flag to silent the simulator when debugging please 🙏

**Pull request merged**
