### PR TITLE
Add FXIOS-7301 [v120] added closue_body_length to swiftlint.yaml

### PR DESCRIPTION
**Pull request by Cretus-iosDev**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7301)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/16442)

## :bulb: Description

so I have added the closue_body_length to swiftlint.yaml

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by adudenamedruby** [comment]
Heya @Cretus-iosDev, thanks so much for this. However, adding a swiftlint rule, also means fixing the warnings that xcode gives. I believe there's like 30 or 40 warnings for this rule.

**Comment by Cretus-iosDev** [comment]
hi @adudenamedruby , 
like after adding the rule. I have tried to build the project and tried to give it a run but I didn't get any warnings.
if did something wrong then please guide me on this. I want to contribute to this project.

**Comment by adudenamedruby** [comment]
@Cretus-iosDev that may be because you may not have swiftlint installed on your system - if you don't, I've told xcode to ignore that build step in the script. Try doing a `brew info swiftlint` to see if it's installed. If not, running `brew install swiftlint` will install it. At that point, clean the project in Xcode and rebuild. You may have to quit Xcode before rebuilding as well... you shouldn't, but you never know with Xcode. lol Now when you build xcode, you should see some warnings for some long closures, letting you know where things need to get fixed.

I'll say that some of those closures are tricky, so do pay special attention to them when fixing. While this is a great ticket for contributors to work on, it's not the most beginner friendly work, and one should definitely have a decent understanding of Swift and closures to tackle this.

**Comment by Cretus-iosDev** [comment]
@adudenamedruby 
i'm running swift lint version 0.52.4 but still not getting any warings.

**Pull request closed without merging**
