### PR TITLE
Bugfix FXIOS-6900 [v117]: Removes appended 2 from BundleIdentifer

### PR DESCRIPTION
**Pull request by tarikeshaq**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-6900)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/15351)

## :bulb: Description
An additional `2` in the bundle identifier for the NotificationService in Beta caused the configuration logic in [configuration code](https://github.com/mozilla-mobile/firefox-ios/blob/70257074e78eeef5d7189a928658b5b5c0323fe1/Push/PushConfiguration.swift#L25-L40) to incorrectly throw an invalid scheme error

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and ensured the tests suite is passing
- [x] Implemented accessibility and tested on UI related work (minimum Dynamic Text and VoiceOver)
- [x] Updated documentation / comments for complex code and public methods if needed

### CODE REVIEW

**Review by nbhasin2 — APPROVED** [review]
Good change, now hopefully nothing breaks on BR 🤞🏼

**Comment by tarikeshaq** [comment]
bitrise is green in https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/dffb13a2-bf33-4936-abc4-9a2663c40d01!

**Comment by tarikeshaq** [comment]
Just tried changing the fennec bundle id and do a local build (to emulate what would happen once we try to build beta with a changed bundle id) and got some breakage... Might switch the code depending on the bundle id to not depend on it as a more robust alternative and keep the bundle id unchanged with a ticket to figure out if it needs to change

**Comment by tarikeshaq** [comment]
@nbhasin2 we can land this one if you're comfortable with it! I also created https://github.com/mozilla-mobile/firefox-ios/pull/15374 which would fix my bug regardless if this patch lands or not (just in case this one causes problems 😬)

**Comment by nbhasin2** [comment]
@tarikeshaq I am comfortable landing it and BR complains we can revert and easily rectify the issue

**Comment by nbhasin2** [comment]
Although lets land your other patch first and make this one for v117

**Comment by tarikeshaq** [comment]
last push only changed the commit message to v117

**Review by nbhasin2 — APPROVED** [review]

**Comment by nbhasin2** [comment]
NOTE: if this causes any build issues with builds then please ping @tarikeshaq or @nbhasin2 (me)
cc @isabelrios @clarmso

**Pull request merged**
