### PR TITLE
Remove FXIOS-5869 [v112] today plist extension

### PR DESCRIPTION
**Pull request by razvanlitianu**
Remove the step to add the version in Today Info.plist which no longer exists.

### CODE REVIEW

**Comment by mte-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Edited 1 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 0 files</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 16d9c78a3abf5ee1772d20a37ec024e8fb4aa082
</p>

**Review by isabelrios — APPROVED** [review]
LGTM!
Thanks

**Review by nbhasin2 — APPROVED** [review]

**Review by yoanarios — APPROVED** [review]

**Comment by isabelrios** [comment]
not sure why bitrise is red here, it is green in the Bitrise UI: 
https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/3a94780a-7025-4a89-ad3a-8a80c644f0fc

@nbhasin2, @yoanarios  could you please merge this without running again?

**Comment by yoanarios** [comment]
@Mergifyio backport release/v112

**Pull request merged**
