### PR TITLE
Bug 1337822 make SearchEngines.getUnorderedBundledEngines more robust

### PR DESCRIPTION
**Pull request by jacobwhite**

### CODE REVIEW

**Comment by farhanpatel** [comment]
Was this based off an old branch? BuddyBuild seems to not be able to find the scheme this branch was compiled with. If so could you please rebase this off master.

**Comment by jacobwhite** [comment]
Shouldn't it be built against v7.x?

**Comment by jacobwhite** [comment]
Here's the pull request against master: https://github.com/mozilla-mobile/firefox-ios/pull/2517

**Comment by farhanpatel** [comment]
Dupe of #2517

**Pull request closed without merging**
