### PR TITLE
Bugfix FXIOS-4336 [v123] The bookmark panel button is not correctly displayed

### PR DESCRIPTION
**Pull request by imsanchit**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-4336)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/10925)

## :bulb: Description

Hey, I have tried fixing this issue, it was probably because the stack view distribution was set to fill, I think this should be in some proportion to avoid current issues. However, this has led to some inconsistency with the existing live build UI (in cases when font sizes are small). I have attached screenshots of both before and after PR scenarios, Please have a look and suggest if this requires any changes.
**Smaller Font Before PR**
Screenshot 2023-12-12 at 12 41 55 AM

**Smaller Font After PR**
Screenshot 2023-12-12 at 12 38 55 AM

**Larger Font Before PR**
Screenshot 2023-12-12 at 1 31 01 AM

**Larger Font After PR**
Screenshot 2023-12-12 at 1 32 30 AM

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by lmarceau** [comment]
Should this be opened as `ready for review` ?

**Comment by cyndichin** [comment]
thanks for looking into this @imsanchit, let me tag the design team to see if there's any issues. @Verdi any issues with the update in the UI shown in the screenshot above?

**Comment by Verdi** [comment]
> thanks for looking into this @imsanchit, let me tag the design team to see if there's any issues. @Verdi any issues with the update in the UI shown in the screenshot above?

If I understand this correctly, it looks like the menu would be fixed for large type but the fix introduces bugs for the default type. If that's so, I think we need to address the bugs introduced for the default type. 
Bookmark panel button bugfix

**Comment by lmarceau** [comment]
The extra space above the menu is another bug and I believe shouldn't necessarely be fixed in this PR. The normal font wrapping for "Reading List" should be fixed as Verdi said thought.

**Comment by cyndichin** [comment]
> > thanks for looking into this @imsanchit, let me tag the design team to see if there's any issues. @Verdi any issues with the update in the UI shown in the screenshot above?
> 
> If I understand this correctly, it looks like the menu would be fixed for large type but the fix introduces bugs for the default type. If that's so, I think we need to address the bugs introduced for the default type. Bookmark panel button bugfix

thanks for checking @Verdi ! The extra space above new tab seems to exist prior to this change, so I can open a new ticket for that if you would like. 

@imsanchit thanks for the fix in large fonts, but it seems like we'll want to avoid wrapping for the reading list and the previous experience for the default font is preferred.

**Comment by Verdi** [comment]
> thanks for checking @Verdi ! The extra space above new tab seems to exist prior to this change, so I can open a new ticket for that if you would like.

Yes please!

**Comment by lmarceau** [comment]
I think we have this issue already existing https://github.com/mozilla-mobile/firefox-ios/issues/11642 👀

**Comment by imsanchit** [comment]
Thanks for the review, everyone. I have updated the PR with a few fixes, attaching the screenshots for a quick check. Also, I have raised separate PR for extra spacing issues. Please have a look and share your thoughts!!
Screenshot 2023-12-20 at 12 31 02 AM
Screenshot 2023-12-20 at 12 31 30 AM

**Comment by cyndichin** [comment]
thanks @imsanchit this is looking great on iPhone! 🥳 Seems that there is an edge case on iPad in which I see it cut off when I go from landscape to portrait mode.

simulator_screenshot_75383DE2-8FA2-4D93-AE5F-447C585CB0F5

**Comment by imsanchit** [comment]
hey @cyndichin, thanks for pointing this out, have added a fix for the same. Please have a look at it once again.

**Comment by cyndichin** [comment]
@imsanchit thanks for fixing the previous issue! However, it seems like the view takes up the whole screen instead of a small portion as in production.

simulator_screenshot_7D5A1669-15EB-486A-B1D7-48E0831F24DA

**Comment by imsanchit** [comment]
hey @cyndichin, could you please have a look at the updated PR?

**Comment by cyndichin** [comment]
thank you @imsanchit this looks great now on both iPad and iPhone! appreciate the hard work and iterations to fix this tricky UI issue :) !

**Review by cyndichin — APPROVED** [review]

**Pull request merged**
