### PR TITLE
Bugfix FXIOS-3422 [v111] Add to Reading List is allowed on non-reader mode pages

### LINKED ISSUE #9500: Add to Reading List is allowed on non-reader mode pages
## Steps to reproduce
1. search something on google
2. click PAM
3. add to reading list is available
### Expected behavior
Add to reading list option should not be available because the page is not one that can be converted to reader mode.
### Actual behavior
Add to reading list option should not be in the menu
### Device & build information
* Device: ?
* Build version: ?
### Notes
Attachments:

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3422)

### PR DESCRIPTION
**Pull request by q2r5**
#9500.

Only check the reader mode state if the MIME type is HTML.

### CODE REVIEW

**Comment by nishant2718** [comment]
hi @q2r5 ! As always, it's great seeing your contributions 😄 

With the suggested changes, it looks like we still get the option to add to reading list. At launch, I saw that it wasn't available. But when you search again, you'll see it.

**Comment by q2r5** [comment]
The option to add to reading list is shown on search result pages because they can be converted to reader mode, both with these changes and on v95 (6631). As I understood it, the issue was for pages not available for reader mode.

**Comment by lmarceau** [comment]
I think what you're referring to is #9747 @nishant2718 ?

**Comment by yoanarios** [comment]
@q2r5 I just reviewed and the fix seems to be great, but the variable `readerModeAvailableOrActive` seems to be not used anymore. This is certainly because this PR has been sitting here for too long, but sadly, this means the work doesn't fix the issue anymore. If you kindly make the required changes to make the fix work again I will review it asap. Thank you for your contribution!

**Comment by yoanarios** [comment]
Green build!!
Screen Shot 2023-02-01 at 9 47 19 AM

**Review by yoanarios — APPROVED** [review]

**Comment by yoanarios** [comment]
LGTM, @q2r5 Thank you for your contribution!

**Pull request merged**
