### PR TITLE
Bug 1384056 - New tab create from outside app is not focusing locationbar

### PR DESCRIPTION
**Pull request by garvankeeley**
The app has complex UI rendering, and focus keeps getting stolen while view is setup,
so if setting focus fails once, try again.

### CODE REVIEW

**Comment by farhanpatel** [comment]
This seems a bit _weird_ I dont think we should need to do this in order to focus. We should instead try to figure out what is removing focus and stop that from happening.
When opening a newtab we call `popToBVC` sometimes. This calls `leaveOverlayMode` which will resign first responder. 

There is probably some method that is being called to setup/clear the state that is resigningFirstResponder when a new tab is created.

**Comment by garvankeeley** [comment]
+1, if there are some candidate methods to look at, we should do that first instead of hacking this in

**Comment by vincentpun** [comment]
@garvankeeley What problems did you experience before you used `DispatchQueue`? I tried moving the body out of the `DispatchQueue` and the location field could be focused just fine.

**Comment by garvankeeley** [comment]
Nice! I would see no focus set unless delayed async, maybe the UI code that was stealing focus has been changed/removed.? It would even better if we could figure out how to automate the test for this so if it gets fixed it doesn't get broken accidentally.

**Comment by garvankeeley** [comment]
Removing the set focus delay might break https://bugzilla.mozilla.org/show_bug.cgi?id=1345887

**Pull request closed without merging**
