### PR TITLE
FXIOS-3175 Fix incorrect add button trailing alignment.

### PR DESCRIPTION
**Pull request by kcome**
### Overview

This PR is in reference to [this issue](https://github.com/mozilla-mobile/firefox-ios/issues/9130)

The fix updated an incorrect alignment between Add button and Tabs button on URL bar.

Simulator Screen Shot - iPhone 11 - 2021-09-19 at 20 57 24

### CODE REVIEW

**Comment by nishant2718** [comment]
Hey @kcome! Thanks for looking into this. It looks good on iPhones but have you checked on iPad?

**Comment by kcome** [comment]
@nishant2718 Hi, thanks for the note :) 
On iPad it also works well.
Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2021-09-22 at 08 51 28
Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2021-09-22 at 08 51 44

Screen Shot 2021-09-22 at 08 51 21

**Comment by nishant2718** [comment]
I've tried your fix locally and it works well on iPhone but on iPad. But it looks like New Tab and Home buttons overlap. So when I tap it, it both takes me home and opens a new Home tab. Maybe we can set a condition to make sure the fix is phones only?

**Comment by kcome** [comment]
@nishant2718 I made a fix that will correctly hide Add Tab button on iPad. Now it works well on iPhone portrait, iPhone landscape and iPad (both orientations) ;-)

**Comment by nishant2718** [comment]
Great! It looks good now 👌

**Review by nishant2718 — APPROVED** [review]

**Pull request merged**
