### PR TITLE
FXIOS-3166: Pull to refresh pages

### PR DESCRIPTION
**Pull request by nishant2718**
# Overview

PR in reference to this [JIRA ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-3166) and https://github.com/mozilla-mobile/firefox-ios/issues/9118.

Pull down from the top of a webpage to refresh.

### CODE REVIEW

**Comment by nishant2718** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

_1) What questions will you answer with this data?_

It will answer how many users take advantage of pulling down to refresh a webpage. 

_2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?_

This will provide us information on user behavior around refreshing a page by pulling to refresh, an "expected" behavior. 

_3) What alternative methods did you consider to answer these questions? Why were they not sufficient?_

Since it's a new feature, current methods can't answer this question. 

_4) Can current instrumentation answer these questions?_

No.

_5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki._

_**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**_

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>Did a user pull to refresh?</td>
    <td>Category 2</td>
    <td>#9118</td>
  </tr>
</table>

_6) How long will this data be collected?  Choose one of the following:_

Until 2022-01-01.

_7) What populations will you measure?_

All release channels and locales.

_8) If this data collection is default on, what is the opt-out mechanism for users?_

Users can opt of of data collection by disabling Usage and technical data from _Settings → Send Usage Data_.

_9) Please provide a general description of how you will analyze this data._

Glean 

_10) Where do you intend to share the results of your analysis?_

Only on Glean, mobile teams and BD have internal access.

_12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?_

No.

**Comment by dnarcese** [comment]
r+
# Data Review Form

_1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?_ 

Yes, telemetry is documented at https://dictionary.telemetry.mozilla.org/apps/firefox_ios

_2) Is there a control mechanism that allows the user to turn the data collection on and off?_ 

Yes, Firefox iOS provides data controls in the app settings

_3) If the request is for permanent data collection, is there someone who will monitor the data over time?_

This should be re-reviewed w/ Ashley Thomas every 6mo

_4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?_

Type 2

_5) Is the data collection request for default-on or default-off?_

Default on

_6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?_

No

_7) Is the data collection covered by the existing Firefox privacy notice?_ 

Yes

_8) Does the data collection use a third-party collection tool?_ 

No

**Comment by nbhasin2** [comment]
https://user-images.githubusercontent.com/8919439/134058952-62b4f096-e06a-4f88-b722-ca15b305e160.mp4

@nishant2718 Seems odd that as soon as you pull I see reload icon only a few times.

a) Is this suppose to be a part of iPad as well? 
b) Should we disable this for iPad cc @dnarcese?

**Review by nbhasin2 — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/8919439/134059706-31f9fa98-3a20-4d2d-98ae-057c3ad10a32.mp4

@nishant2718 This doesn't seem right to me 🤔 
The refresh control seem to be below the header image whereas above the webview.

**Comment by dnarcese** [comment]
I think it's fine to leave it on iPad

**Comment by nishant2718** [comment]
I'm not sure if this is right, but I think it might depend on whether the site has a sticky header? The Guardian and NYTimes don't have that issue.

**Comment by nbhasin2** [comment]
> I'm not sure if this is right, but I think it might depend on whether the site has a sticky header? The Guardian and NYTimes don't have that issue.

Maybe this is the reason why other browsers have the pull down to refresh above the page. Reason I say is because it seems odd to refresh a page and not have any feedback with a sticky header. I feel we can improve this implementation. What do you think?

**Comment by nishant2718** [comment]
Yeah can definitely work on that!

**Comment by nishant2718** [comment]
https://user-images.githubusercontent.com/36939381/134073899-ad3c8f46-b8cb-4941-8171-95934b1f423f.MP4

**Comment by nishant2718** [comment]
@topotropic Here's pull to refresh in action. Some things to note:

- Dark/Light mode makes a difference. For sites with a light background and when you're on dark mode, the icon appears lighter (but still visible). For sites with a dark background, you'll hardly see the icon on light mode. But in dark mode, you'll see it clearly. 
- Sites with sticky headers are an issue for the loading icon because the icon appears behind the sticky header. 

There's haptic feedback, so a user'll always know something happens when pulling down past a certain threshold. 

What do you think?

**Comment by topotropic** [comment]
Thanks for sharing. 

What's the plan for the remaining issues that you listed? Is there a way for me to try it out?

**Comment by nishant2718** [comment]
I believe you'll be able to check in beta, when it gets shipped there. For the first bullet point, we are considering changing that icon color based on the background of a web page. For sites with sticky headers, it looks like it's going to be a bigger engineering feat. 

Both will have to come in a later ticket, likely with each bullet being its own ticket. For now, we can try this solution if we have your approval.

**Review by nbhasin2 — APPROVED** [review]

**Pull request merged**
