### PR TITLE
Bugfix FXIOS-10251 iPad not recognizing Firefox pair website

### PR DESCRIPTION
**Pull request by FilippoZazzeroni**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-10251)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/22435)

## :bulb: Description
Bugfix iPad not recognizing Firefox pair website.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by FilippoZazzeroni** [comment]
@Mergify backport release/v133

**Review by cyndichin — COMMENTED** [review]
thanks @FilippoZazzeroni! can we add tests here as well?

**Comment by FilippoZazzeroni** [comment]
Yes sure @cyndichin i'm going to add them

**Review by cyndichin — APPROVED** [review]
looks great, thank you for writing these tests 🔥

**Comment by FilippoZazzeroni** [comment]
Thanks Cyndi 🎉 🎉

**Pull request merged**
