### PR TITLE
Add FXIOS-3181 [v109] Full Webpage Screenshots

### PR DESCRIPTION
**Pull request by q2r5**
[Jira](https://mozilla-hub.atlassian.net/browse/FXIOS-3181)
https://github.com/mozilla-mobile/firefox-ios/issues/9138
image

### CODE REVIEW

**Comment by lmarceau** [comment]
Thanks @q2r5, I started the build but it failed with following error. Would you mind having a look into it? Thanks!
Screen Shot 2022-11-07 at 10 27 32 AM

**Comment by nishant2718** [comment]
Hey @q2r5 ! I'll help you follow this PR through. I'll get back to you after testing it locally

**Comment by nishant2718** [comment]
I'm not seeing the option to capture the full page like you do in your screenshot. I see it DOES succeed and has data with breakpoints, but not sure what's going on. 

Can you list your testing steps @q2r5 ?

**Comment by q2r5** [comment]
The screenshot was taken on device (16.2), however it does seem to work for me in a 14.5 sim as well. All I'm doing is triggering a screenshot (Device->Trigger Screenshot on Simulator) and tapping the preview in the lower left corner of the screen to show the options.

Though before this lands, it'll need to handle the case of screenshotting the homepage. Currently it just returns null on a fresh tab, which still shows the 'full page' option just without any content, or the webview if it exists.

**Comment by nishant2718** [comment]
Okay! Yeah I ran it on my device but didn't see a full page option but see it in sim - we can have QA double check that as well.

As a short term fix for Home, we can try checking if the URL of that webpage `isFxHomeUrl`, and prevent the PDF option. But maybe a more correct approach would be to check if it's an internal url. That might take a little more digging around and experimentation.

**Review by nishant2718 — CHANGES_REQUESTED** [review]
Okay, thought this over and debugged around a bit. 

Currently, you'd get a blank screen for the homepage and settings. What you can do for Homepage is check if the selectedTab's url `isFxHomeUrl`. For the settings page, you can check if the webView.window is nil. 

In the future we may adjust this a bit, but it should be okay for now and we can land it sooner.

**Comment by nishant2718** [comment]
Tested this branch locally for the failing test - I think it may be flaky. Also, it doesn't have much relation to the work done in here. We should be fine.

**Pull request merged**
