### PR TITLE
Bugfix some Xcode warnings to let pipeline pass

### PR DESCRIPTION
**Pull request by FilippoZazzeroni**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-TODO)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/TODO)

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Review by MattLichtenstein — APPROVED** [review]
👌

**Review by clarmso — APPROVED** [review]

**Comment by rvandermeulen** [comment]
@FilippoZazzeroni Can we lower the warning threshold so this doesn't regress down the road?

**Comment by adudenamedruby** [comment]
ew one of these warnings is mine. I"M SORRY!

**Comment by FilippoZazzeroni** [comment]
yes @rvandermeulen in another PR would be nice to lower it or even have it to 0

**Pull request merged**
