### PR TITLE
#8897 - Move to UISceneDelegate

### LINKED ISSUE #8897: Multitasking: Move to Scenes
**Vision**

Switch to scenes, so that we can make use of Apple’s multi-tasking capabilities on iPad

**Acceptance Criteria**

* App uses new UI scene delegate APIs

**Not Included**

* For this ticket, we will only have 1 scene. This does not include breaking the app out to enable multi-tasking
* This is dependent on [https://mozilla-hub.atlassian.net/browse/FXIOS-3005](https://mozilla-hub.atlassian.net/browse/FXIOS-3005|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2997)

### PR DESCRIPTION
**Pull request by q2r5**
Fixes #8897, #9138.

This may be more than required for an initial implementation, but it is what I've been using in my personal builds for a while.

Opening as draft for initial review.

### CODE REVIEW

**Comment by electricRGB** [comment]
Prelim look at this was great. I still haven't pulled and poked around that way, yet. But so far so good. :)

Great work @q2r5

**Comment by lmarceau** [comment]
Hey @q2r5 ! Thanks for keeping this up to date. We're currently working on a major release, and as this PR has potential to be a little more risky we would look into reviewing this PR after v106 soft freeze (in a couple of weeks). Feel free to ping us if this falls under the radar again, as this is good work and we should merge this!

**Comment by lmarceau** [comment]
@q2r5 Hello! Just a quick update, @nishant2718 is looking into everything relating to scenes changes (including work from PR https://github.com/mozilla-mobile/firefox-ios/pull/11308). He'll give you some insights on his research pretty soon. Thank you for your understanding!

**Comment by nishant2718** [comment]
👋  @q2r5 ! It's time to explain the silence. 

I really want to thank you for raising this PR! This is excellent work and we always look forward to seeing your contributions. There's a lot of great stuff here and we seriously discussed how we can merge it, but we had to take a look at the bigger picture first. 

The transition to Scenes is a risky task. We're taking it slow because we've identified quite a few things that needed to happen leading up to being able to work on this, like:
- IDing some initial blockers, like the usage of `foregroundBVC()`
- handling our dependencies reasonably (we're slowly adopting a container based strategy with [Dip](https://github.com/AliSoftware/Dip))
- Isolating window / view setup that's within AppDelegate
- much more

We try giving context where we can, but sometimes it's a bit difficult to convey. And that's why it took a while to respond here. I hope this helps in understanding the journey to a Scened app and eventually, multiple window support :) 

Again, we really appreciate your work and all your contributions, and you'll definitely be listed as a co-author for the work! Catch you on the next one 😄

**Comment by nishant2718** [comment]
For a reference, [here's the PR](https://github.com/mozilla-mobile/firefox-ios/pull/12241) we're working with now to make that transition to a single scene app (pre-multi window support).

**Pull request closed without merging**
