### PR TITLE
Bugfix FXIOS-9320 ⁃ Copy option is missing from share menu

### PR DESCRIPTION
**Pull request by dicarobinho**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-9320)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/20649)

## :bulb: Description
Added back Copy option to the share menu

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Review by cyndichin — COMMENTED** [review]
@dicarobinho thanks for the update, code looks good. Only thing is that we have two copies now in the share sheet, which may confuse users. 

Is this something we want to include from product perspective? @afurlan-firefox 

Screenshot 2024-07-22 at 09 14 34

**Comment by dicarobinho** [comment]
@cyndichin the **UIActivity.ActivityType.copyToPasteboard** option has been added to the excludingActivities list in another PR and that caused few issues with some Tests. The question is: we need the Copy option for Downloaded items or we don't? :)

Thank you!

**Comment by cyndichin** [comment]
> @cyndichin the **UIActivity.ActivityType.copyToPasteboard** option has been added to the excludingActivities list in another PR and that caused few issues with some Tests. The question is: we need the Copy option for Downloaded items or we don't? :)
> 
> Thank you!

Discussed via slack, the concern is to follow up with Product on this decision to add back in the additional copy and if we want the experience of the two copies.

**Comment by cyndichin** [comment]
@dicarobinho feel free to ping me or request another review when ready for another look, don't want to be a blocker on this PR!

**Comment by dicarobinho** [comment]
I removed the duplicate Copy option and this is how it looks now:
ImportedPhoto 744197840 323206
ImportedPhoto 744197840 329483

@afurlan-firefox what do you think?

cc: @cyndichin

**Comment by afurlan-firefox** [comment]
Looks good to me!

**Review by cyndichin — APPROVED** [review]
Thanks for looking into this change!! Looks good 😊

**Pull request merged**
