### PR TITLE
Fix MTE-1528 [119] lock icon secure label

### PR DESCRIPTION
**Pull request by dragosb01**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/MTE-1528)

## :bulb: Description 
Small fix for lock icon secure label.
Added test rail link for testLastOpenedTab test.

### CODE REVIEW

**Review by isabelrios — APPROVED** [review]
LGTM!

**Comment by isabelrios** [comment]
@clarmso is this change according to the PR you were working on last week?

**Comment by clarmso** [comment]
> @clarmso is this change according to the PR you were working on last week?

Yes, I tried to address the root issue on the code rather than just updating the test.

**Comment by isabelrios** [comment]
> > @clarmso is this change according to the PR you were working on last week?
> 
> @isabelrios Yes, I tried to address the root issue on the code rather than just updating the test. #16302

Ok, let's land your PR then and monitor if the issue is fixed...

**Comment by clarmso** [comment]
I have landed https://github.com/mozilla-mobile/firefox-ios/pull/16302.

**Comment by dragosb01** [comment]
Closing this PR, the fix has been addressed in https://github.com/mozilla-mobile/firefox-ios/pull/16302

**Pull request closed without merging**
