### PR TITLE
Bugfix FXIOS-7568 [v122] Close button on the onboarding screen is not the first focusable element

### PR DESCRIPTION
**Pull request by NSOiO**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7568)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/16842)

## :bulb: Description
1. create UIView extension that can change the order of accessibility elements
2. make close button the first focusable element on the onboarding screen

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [x] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by yoanarios** [comment]
There are a few warnings related to swiftlint format at `UIView+Accessibility.swift` and `AccessibilityTests.swift` they need to be fixed for the build to pass

**Comment by NSOiO** [comment]
> There are a few warnings related to swiftlint format at `UIView+Accessibility.swift` and `AccessibilityTests.swift` they need to be fixed for the build to pass

Thank you for pointing that out, I have fixed and pushed it, please check it.

**Review by yoanarios — COMMENTED** [review]
LGTM just checking for @thatswinnie input

**Comment by thatswinnie** [comment]
Thank you for opening the PR for this @NSOiO 🙏 While the solution you have works I will ask for changes for a few reasons: For one we are trying to move away or limit having extensions on Apples API - especially if that extension would only be used once. You can read more about this [here](https://github.com/mozilla-mobile/firefox-ios/wiki/When-To-Use-Extensions). Additionally we have the pattern already in other places in the app where we set `accessibilityElements` instead to determine the order of elements. Would you mind changing your code to use `accessibilityElements` instead?

**Comment by NSOiO** [comment]
> Thank you for opening the PR for this @NSOiO 🙏 While the solution you have works I will ask for changes for a few reasons: For one we are trying to move away or limit having extensions on Apples API - especially if that extension would only be used once. You can read more about this [here](https://github.com/mozilla-mobile/firefox-ios/wiki/When-To-Use-Extensions). Additionally we have the pattern already in other places in the app where we set `accessibilityElements` instead to determine the order of elements. Would you mind changing your code to use `accessibilityElements` instead?

Thank you @thatswinnie , I got it and replaced it with `accessibilityElements`.

**Pull request merged**
