### PR TITLE
Initialize Rust network stack on startup

### PR DESCRIPTION
**Pull request by eoger**
https://github.com/mozilla/application-services/pull/2880 will require iOS users to initialize the rust network stack manually before using it. @garvankeeley is this startup method called everywhere? (I'm thinking extensions etc.)

### CODE REVIEW

**Comment by garvankeeley** [comment]
I am merging rust-integration branch to master today, so this can be a PR against that, I'll let you know when it is ready.

We should put `Viaduct.shared.useReqwestBackend()` in `RustFirefoxAccounts.startup()`.

**Comment by eoger** [comment]
Just to be clear, this change applies to every single rust component that firefox-ios uses (bookmarks, logins etc), are we sure that FirefoxAccounts is initialized before all of them?

**Comment by garvankeeley** [comment]
Yeah that startup needs to be called before all of them.

**Comment by eoger** [comment]
Needs an a-s version bump before merging.

**Comment by eoger** [comment]
Reading to merge assuming it's green.

**Pull request merged**
