### PR TITLE
Bugfix FXIOS-7631 [v121] Default browser tutorial dismissed incorrectly

### PR DESCRIPTION
**Pull request by mattreaganmozilla**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7631)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/17009)

## :bulb: Description

When handling the default browser tutorial router we end up also calling into `dimiss` on the `LaunchCoordinator` child of the `BrowserCoordinator` (related: https://github.com/mozilla-mobile/firefox-ios/pull/16789). The trouble is that the coordinator was added as part of the same recursive handling in `findAndHandle(route:)` which also runs the dismissal code. There are a couple potential approaches to this, and I think it may warrant revisiting at some point later down the road.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by mattreaganmozilla** [comment]
@lmarceau This feels like more of a bandaid; I verified that it fixes the bug, but wanted to be sure I got your eyes on it since I still don't have a great big-picture understanding of how these coordinators/routers interact in some ways.

LMK if you have any thoughts, I'm happy to change this or take a different approach.

**Comment by mattreaganmozilla** [comment]
Based on team chats it sounds like we want to take a closer look at this and the related updates in https://github.com/mozilla-mobile/firefox-ios/pull/16789; going to close this in the meantime until we have a chance to sync up further.

**Comment by lmarceau** [comment]
We discussed and we'll go for this solution until we rework this area with https://github.com/mozilla-mobile/firefox-ios/issues/17043 for alonger term fix

**Comment by mattreaganmozilla** [comment]
@lmarceau Had some trouble reopening this branch after deletion so just opened up a new PR, sorry for any extra noise: https://github.com/mozilla-mobile/firefox-ios/pull/17050/

**Pull request closed without merging**
