### PR TITLE
Wrap long text in ETP message in action sheet popup

### LINKED ISSUE #6867: ETP option in Reload contextual menu is truncated in French
“Reload Without Tracking Protection” option in reload contextual menu is truncated in French

Full string is “Actualiser sans protection contre le pistage“
Same with “Reload With Tracking Protection” (Actualiser avec la protection contre le pistage)

IMG_CF288DA5D79A-1

### Device & build information
* Device: iPhone X
* Build version: 27.0 (18383)

### PR DESCRIPTION
**Pull request by joeyg**
Fixes #6867 by adjusting the text for that cell. Here is a screenshot of that french string hard coded:

Simulator Screen Shot - iPhone 8 - 2020-06-26 at 12 19 54

### CODE REVIEW

**Comment by dnarcese** [comment]
@athomasmoz Not sure who to reach out to from UX about this string behaviour. Question is should the text size dynamically change to fit the string, should it wrap, or should it truncate.

**Comment by athomasmoz** [comment]
I just added the needs UX label. I think @brampitoyo and @betsymi had a recommendation on a similar tracking protection string. Do either of you know off-hand?

**Comment by betsymi** [comment]
> I just added the needs UX label. I think @brampitoyo and @betsymi had a recommendation on a similar tracking protection string. Do either of you know off-hand?

I believe the decision was made to truncate. Dug up issue #5910

**Comment by garvankeeley** [comment]
Truncation means the text may not be comprehensible. Shrinking slightly ensures the text will be comprehensible while increasing risk that it is illegible, but we can control that risk by controlling the amount of shrink. Seems like we should first shrink, then truncate.
Issue #5910 made sense to truncate, because it is an email, likely the users own email, so it is likely still easily understood.

**Comment by betsymi** [comment]
> Truncation means the text may not be comprehensible. Shrinking slightly ensures the text will be comprehensible while increasing risk that it is illegible, but we can control that risk by controlling the amount of shrink. Seems like we should first shrink, then truncate.
> Issue #5910 made sense to truncate, because it is an email, likely the users own email, so it is likely still easily understood.

Ah, I see. Thanks for that context, I had misunderstood and thought this decision would be applicable everywhere. @brampitoyo do you have a POV on shrinking or wrapping?

**Comment by brampitoyo** [comment]
@betsymi @garvankeeley In that case, It’s better to neither truncate nor shrink the text, but to let it reflow to the next line (with the same text size, of course). If required, the tap target should be enlarged.

For instance, here’s what happens when the menu item to toggle Safari Content Blocking doesn’t fit the line:



Would doing something like this be possible?

**Comment by garvankeeley** [comment]
Agreed reflow is a great solution. Some of the widgets we use don't natively support reflowing the text, particularly switches. We should research what solutions exist for that (being mindful to not break accessibility).

**Comment by brampitoyo** [comment]
On iOS 14, it seems that menus no longer appear centred on the screen (with a “Cancel” button) and no longer have a backdrop/scrim. Furthermore, the text inside this menu may also be varied in size.



This is something that we can potentially do going forward. But for now, I would advise just reflowing to the second line. Much safer and more readable that way.

**Comment by nbhasin2** [comment]
@brampitoyo How does this look? 

So far I am thinking of maxing re-flow to 2 lines. 

image

**Comment by brampitoyo** [comment]
@nbhasin2 Yes. I think 3 lines would make the tap area too large. Besides, not many languages will have strings that are so long that it will overflow 2 lines.

So I agree. Let’s do 2 lines.

**Comment by SimonBasca** [comment]
Verified fix on iPhone SE (11.4) on master 0104534 on EN. The text reflows to the next line (with the same text size)
Noted: Checked on a small screen device because on main 0104534 there is no localization.

**Comment by betsymi** [comment]
@AmyYLee just noticed it says Protection twice. The string should read `Reload without Enhanced Tracking Protection.`

**Pull request merged**
