### PR TITLE
Bugfix MTE-939 [v114] Keyboard behaviour for iPad

### PR DESCRIPTION
**Pull request by clarmso**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/MTE-939)

### Description
FXIOS-6260 fixes the behaviour of the keyboard on iPad. Now the keyboard behaves the same on both iPad and iPhone. Now we can remove the if..else statements for iPad for the full functional test.

I've run these tests on both XCode 14.1 and 14.3 on both iPhone and iPad.

### Pull requests checks where applicable
- [X] Fill in the three TODOs above (tickets number and description of your work)
- [ ] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [ ] Unit tests written and passing
- [ ] Documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by clarmso** [comment]
The test failure from bitrise is on `testFirstRunTour()`. This test is not modified in this PR. In addition, the failure occurs because the app did not start.
Screenshot_1_11958056-09D5-4F35-9FC7-EFAD2A0BBF39

**Comment by isabelrios** [comment]
> The test failure from bitrise is on `testFirstRunTour()`. This test is not modified in this PR. In addition, the failure occurs because the app did not start. Screenshot_1_11958056-09D5-4F35-9FC7-EFAD2A0BBF39

I think the test is failing because there was a change in the Onboarding screen (see [PR](https://github.com/mozilla-mobile/firefox-ios/commit/c8381beeab50925a89302e19dbbae4cb8af98282#diff-c8c5cb3060f3f8ddb9d4dd050ecac7f0bf313e93b31ceaf25cb5bdaf5b5f0c38)) rebasing with latest main should fix this

**Comment by isabelrios** [comment]
> > The test failure from bitrise is on `testFirstRunTour()`. This test is not modified in this PR. In addition, the failure occurs because the app did not start.
> 
> @clarmso I think the test is failing because there was a change in the Onboarding screen (see [PR](https://github.com/mozilla-mobile/firefox-ios/commit/c8381beeab50925a89302e19dbbae4cb8af98282#diff-c8c5cb3060f3f8ddb9d4dd050ecac7f0bf313e93b31ceaf25cb5bdaf5b5f0c38)) rebasing with latest main should fix this

Actually, it does not fix it :( that PR breaks the test. For what I see now in the Onboarding, we need to swipe instead of clicking on next (or similar button) to go to the next screen. So we would need to update the test.

Unfortunately, since there is a known unit test failure having red builds, builds are being merged anyways thinking that's the issue and there might be things like this happening.. :( 
I'm disabling the test for now in a PR I have open I need to merge to unblock this situation for now, and you address the test changes here if that sounds good. 

Thanks!

**Comment by yoanarios** [comment]
> r what I see now in the Onboarding, we need to swipe instead of clicking on next (or similar button) to go to the next screen. So we would need to update the test.
> 
> Unfortunately, since there is a known unit test failure having red builds, builds are being merged anyways thinking that's the issue and there might be things like this happening.. :( I'm disabling the test for now in a PR I have open I need to merge to unblock this situation for now, and you address the test changes here if that sounds good.

Currently we have a bug where the click on the buttons is failing in the onboarding but is being fixed by @CatalinNeculaide

**Comment by clarmso** [comment]
@isabelrios Could you please kindly approve this PR? I also need to merge this change back to v113 since #14143 has been merged to v113.

**Review by isabelrios — APPROVED** [review]

**Comment by clarmso** [comment]
@Mergifyio backport release/v113

**Pull request merged**
