### PR TITLE
Build FXIOS-8134 [v124] Stop setting dummy secrets for bitrise-trigge…

### PR DESCRIPTION
**Pull request by ahal**
…r tasks

There's generally not any point in creating a dummy secret for pull requests because the tasks won't do anything useful anyway. There's also no security benefit of doing this because access to this secret is already controlled in Firefox CI's configuration repo: http://hg.mozilla.org/ci/ci-configuration/file/ae2d04f50811dad99be739092eadaf9effce3829/grants.yml#l1740

Instead, let's just always attempt to access the secret and focus on not running these sensitive tasks where it isn't allowed in the first place.

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-8134)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/18100)

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [x] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [x] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by ahal** [comment]
Btw I still don't seem to be able to allow my builds in Bitrise. I wonder if I'm somehow logging into the wrong account or something.

**Comment by clarmso** [comment]
> Btw I still don't seem to be able to allow my builds in Bitrise. I wonder if I'm somehow logging into the wrong account or something.

👋🏼 Let me start Bitrise for you.

**Review by clarmso — APPROVED** [review]

**Comment by isabelrios** [comment]
> Btw I still don't seem to be able to allow my builds in Bitrise. I wonder if I'm somehow logging into the wrong account or something.

Looks like you have not accepted the Bitrise invitation or you are not login there via SSO... we can have a quick zoom to have you set up correctly
Screenshot 2024-01-24 at 09 56 05

I added you to the devs group but not there yet...

**Comment by ahal** [comment]
Thanks! I had apparently signed in via Github prior to the invite, and Bitrise was redirecting me to that account rather than the one associated with my LDAP. After deleting my non-LDAP account, it now works :).

I don't have permission to land PRs though, so if someone could land this, it would be appreciated!

**Pull request merged**
