### PR TITLE
Issue 5491 Send notification After Tab Sent

### PR DESCRIPTION
**Pull request by vuinguyen**
This pull request addresses issue 5491, which is a new feature request.

https://github.com/mozilla-mobile/firefox-ios/issues/5491

This new feature will enable a notification to be sent after a tab is successfully shared from the Page Actions -> Share Page With .... menu. To get to this menu, the user will tap on the "..." or More menu in the upper right corner, and get a screen that looks like this:
PageActionMenuFrom3Dots

Then, the user taps on "Share Page With ..." and get this screen, or something similar, depending on what share apps are available on the user's device:
ShareMenu

For this example, 
I will tap on the Firefox icon, which will get me to this screen. For the purpose of discussion, we will call this the **Firefox-share screen** :
ShareToFirefoxMenu

From here, I will tap on the "Send To Device" option and get this screen:
DevicesScreen

Finally, I would select a device and tap on "Send", and hopefully get something like this:
Simulator Screen Shot - iPhone SE - 2019-10-15 at 20 47 11

However, it does not work this way, and there's more work that needs to be done to get there.

 So, here is a list of items for discussion:

- [ ] As shown in the **Firefox-share screen**, there are multiple share activities. And each share activity has a different number of screens that the user must go through before the activity can be flagged as "completed" in the code. At least that's how it should work.

But as the code behaves today, all screens from this point onward will return a flag of "completed" if true, even if the user cancels out early for any of the share activities, or even if the user cancels out of this screen. Because of this, if we place code here to send a notification, a "Tab Sent" notification will be delivered regardless of whether the user completes the share activity or cancels it by this point. The place where this is happening is in **BrowserViewController.swift** , in the **presentActivityViewController()** method.

- [ ] The Reminders app or activity, as shown in the **Firefox-share screen" has a bug. This one returns a "completed" flag of true even if the user cancels out. The bug is explained here:
https://forums.developer.apple.com/thread/77776

- [ ] I can only test the Firefox and Reminders activities / share apps in the simulator (see the **Firefox-share screen**. )The only way I can test other share activities would be to test it on my device. Do we want / need to test other activities? Or should we focus only on the Firefox share activity for this issue?

- [ ] In order to test more activities on my device, my developer id would need to be added to the Team profile for the **firefox-ios** repo. Will this be necessary for me to continue working on this issue? (see item above)

- [ ] I'd like to get some feedback on this PR before adding tests. What do you think?

I know this is a lot to cover / discuss. 

@garvankeeley  Please let me what questions you have for me, or how you'd like to proceed in working on / reviewing this PR. Thanks for your help!

### CODE REVIEW

**Comment by garvankeeley** [comment]
This is mainly needed for the Firefox Share Tab action, does that simplify things?
I think the fix might be to show a confirmation in the Share Tab screen itself, just like 'Load In Background' is showing a confirmation.

**Comment by vuinguyen** [comment]
I think that does simplify things @garvankeeley ! Sorry for not being as responsive, I'm working on a coding test at the moment ;) Will give you another status, once I have some time .....

**Comment by vuinguyen** [comment]
@garvankeeley 
Reducing the scope of this issue to just the Firefox Share Tab action does help, but we still have the problem of, once we're on the Firefox Share Tab, regardless of whether we complete a share action or cancel it, the code will still send a "Tab Sent" notification. 

I feel that this is a poor user experience, to receive a notification whether a share activity gets completed or not. It would be less confusing to not have a notification sent at all, rather than receive one even if the activity is cancelled.
 
The challenge is that the Firefox Share Tab screen actually consists of multiple sub-activities. In order for the notification feature to behave correctly for the Firefox Share Tab, I feel that the Firefox Share Tab feature may need to be extensively rewritten so that the notification can be handled correctly for each sub-activity.

As a reminder, here's the Firefox Share Tab that I see on my simulator.

ShareToFirefoxMenu


What are your thoughts? What other ways can we can approach this issue?

**Comment by garvankeeley** [comment]
Yeah, this might be too big of a mess to do something simply. I was hoping here it could do something to show the 'tab sent' message: https://github.com/mozilla-mobile/firefox-ios/blob/master/Extensions/ShareTo/SendToDevice.swift#L37

Thanks for all the research on this BTW.

**Comment by vuinguyen** [comment]
I'm going to close this PR for now since the scope and the possible solution to this issue has gotten so complicated ..... Thanks for taking the time to review my work @garvankeeley !

**Pull request closed without merging**
