### PR TITLE
Bugfix FXIOS-7715 [v123] Use new theme system for webviewContainerBackdrop color in browser

### PR DESCRIPTION
**Pull request by tonell-m**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7715)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/17205)

## :bulb: Description

Replaces deprecated use of `UIColor.Photon.Ink90` by replacing it with `currentThem.colors.layer3`. This will use `DarkGrey80` for dark theme, `LightGrey20` for light theme and `Ink90` for private mode theme (I think that this theme is currently unused tho).

Another option is to use `colors.layerScrim` since it seems to be used already as a private mode mask color in other places but that color has an opacity of `0.95` meaning it will still be a little see-through. Let me know what you think given the screenshots below

| Before   |      After (dark)     |  After (light) |
|:---------:|:-------------:|:-----:|
| Simulator Screenshot - iPhone 15 Pro - 2023-12-05 at 15 03 06 | Simulator Screenshot - iPhone 15 Pro - 2023-12-05 at 14 50 48 | Simulator Screenshot - iPhone 15 Pro - 2023-12-05 at 14 50 31 |

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [x] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [x] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by adudenamedruby** [comment]
As per @lmarceau suggestion, any thoughts on this from design: @Verdi @cwzilla? Should we use a different colour than `layer3`

**Comment by cwzilla** [comment]
> As per @lmarceau suggestion, any thoughts on this from design: @Verdi @cwzilla? Should we use a different colour than `layer3`

Just want to better understand the context of this and how it's triggered. Is this the screen color when a user views all their open apps and they are in private mode?

**Comment by lmarceau** [comment]
> Just want to better understand the context of this and how it's triggered. Is this the screen color when a user views all their open apps and they are in private mode?

Yes, whenever someone is in private mode, and they move their Firefox app to background, you would see this to cover up any private information.

**Review by cwzilla — COMMENTED** [review]
`layer3` looks good!

**Comment by lmarceau** [comment]
@tonell-m if you fix the conflicts we can run Bitrise and merge the PR for v123 🙏 Thank you!

**Comment by tonell-m** [comment]
Done @lmarceau!

**Pull request merged**
