### PR TITLE
Refactor FXIOS-9244 - Update Fonts related to HomepageMessageCardCell to use FXFontStyles

### PR DESCRIPTION
**Pull request by DanielDervishi**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-9244)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/20470)

## :bulb: Description

Homepage Font Before
After - Messaging

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by cyndichin** [comment]
@cwzilla can you confirm the font changes here? thank you!

**Comment by cwzilla** [comment]
@DanielDervishi Thank you for the screenshots! Could we adjust the messaging font ('Set links from websites...') to use `subhead`?

**Comment by DanielDervishi** [comment]
> @DanielDervishi Thank you for the screenshots! Could we adjust the messaging font ('Set links from websites...') to use `subhead`?

Sounds Good!

**Review by cwzilla — APPROVED** [review]

**Review by cyndichin — APPROVED** [review]
great work, thanks @DanielDervishi !

**Pull request merged**
