### PR TITLE
Bugfix FXIOS-7373 [v120] Removed extra call from viewWillLayoutSubviews + refactor #14264

### PR DESCRIPTION
**Pull request by imsanchit**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7373)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/16340)

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by yoanarios** [comment]
@imsanchit thank you for the contribution. I've tested the changes and LGTM I want to double-check and wait for @lmarceau approval because she is more familiar with this code and the edge case these changes were fixing

**Review by lmarceau — APPROVED** [review]

**Comment by lmarceau** [comment]
Closing and reopening to trigger Bitrise

**Comment by lmarceau** [comment]
@imsanchit could you rebase with `main`? There has been Xcode 15 changes which aren't compatible with Xcode 14 (making the build fail). Rebasing with `main` should fix the problem.

**Review by yoanarios — APPROVED** [review]

**Comment by imsanchit** [comment]
@lmarceau rebased the feature branch, please have a look.

**Pull request merged**
