### PR TITLE
remove snapkit from history panel #10315

### PR DESCRIPTION
**Pull request by mozead1996**
remove snapkit code from History panel , issue [10305](https://github.com/mozilla-mobile/firefox-ios/issues/10305)

### CODE REVIEW

**Comment by mozead1996** [comment]
tests are passed , also a screenshot of history panel

Screen Shot 2022-03-26 at 6 54 23 PM

Simulator Screen Shot - iPhone 11 Pro - 2022-03-26 at 17 53 58

**Review by lmarceau — COMMENTED** [review]
Hi @mozead1996, this LGTM although one comment is that we're currently in an in-between state with the HistoryPanel. We have a HistoryPanel and HistoryPanelV2 class. The code you modified in func `createEmptyStateOverlayView` is in both class. Would you mind changing the same code in V2 as well? Thanks!

**Comment by mozead1996** [comment]
hi @lmarceau , thanks for your reply. 
sure but i cannot see **HistoryPanelV2** class in the project , do you mean **HistoryPanelWithGroups** ?
cause no snap code in it !?

**Comment by lmarceau** [comment]
> hi @lmarceau , thanks for your reply. sure but i cannot see **HistoryPanelV2** class in the project , do you mean **HistoryPanelWithGroups** ? cause no snap code in it !?

Ah yes, you're right it was renamed! Yes exactly 😄

**Comment by electricRGB** [comment]
Heya. I see that SnapKit has been removed from `HistoryPanelWithGroups`. As such, this PR is no longer valid.

Thank so much for your contribution and sorry we didn't get a chance to merge this code in.

**Pull request closed without merging**
