### PR TITLE
Refactor MTE-1500 [v118] Skipping just the swipe gesture in testDeleteHistoryEntryBySwiping

### PR DESCRIPTION
**Pull request by clarmso**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/MTE-1500)

## :bulb: Description
Instead of disabling the whole test for M1, let's execute the test until the swipe gesture is invoked.

Note that swipe is known not to work on M1.

## :pencil: Checklist
You have to check all boxes before merging
- [X] Filled in the above information (tickets numbers and description of your work)
- [X] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by clarmso** [comment]
Oops. The history page is not working at the moment, so `testDeleteHistoryEntryBySwiping()` should fail.

**Comment by isabelrios** [comment]
> Oops. The history page is not working at the moment, so `testDeleteHistoryEntryBySwiping()` (from Smoketest4) should fail.

yes, that's what I was going to say.. that we may need to hold off on landing until issue #16241 is fixed

**Comment by clarmso** [comment]
@isabelrios [#16302](https://github.com/mozilla-mobile/firefox-ios/pull/16332) has been merged. Could you please kindly approve this PR?

**Comment by clarmso** [comment]
https://github.com/mozilla-mobile/firefox-ios/pull/16332 has been opened. 🚀

**Comment by clarmso** [comment]
I've cherry picked my changes here: https://github.com/mozilla-mobile/firefox-ios/pull/16404

**Pull request closed without merging**
