### PR TITLE
Bugfix FXIOS-6070 [v114] URL bar image don't update when you change the default search engine

### PR DESCRIPTION
**Pull request by nayushi**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-6070)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/13745)

### Description
Fixed the bug when URL bar Image area doesn't reflect when changing the default search engine by calling the `urlBar.searchEnginesDidUpdate()` on viewWillAppear cause if you kept the search bar selected to change the search engine and got back it wouldn't pass through the methods that would reload the image.

### Pull requests checks where applicable
- [x] Fill in the three TODOs above (tickets number and description of your work)
- [x] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [ ] Unit tests written and passing
- [ ] Documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by lmarceau** [comment]
Tagging @rilury for review since this task was in progress in JIRA 🙏

**Comment by nishant2718** [comment]
Hello! There's one swiftLint warning that's a quick fix, 
image

Could you please update that. Otherwise, this patch looks good!

**Comment by nayushi** [comment]
> Please address the SwiftLint issue, and then we'll run our build pipeline on the PR again.

Hi @nishant2718
I removed the whitespace but I have a question, even with swiftlint installed it doesn't warn anything at the firefox project, maybe am I missing something to make it work? Thank you in advance!

**Comment by nishant2718** [comment]
> > Please address the SwiftLint issue, and then we'll run our build pipeline on the PR again.
> 
> Hi @nishant2718 I removed the whitespace but I have a question, even with swiftlint installed it doesn't warn anything at the firefox project, maybe am I missing something to make it work? Thank you in advance!

We noticed that after adopting XCode 14, XCode only occasionally shows errors and warnings in the project. To get the ability to see those again, we turned off "Show live issues". That's located in XCode Preferences --> General tab --> uncheck that option. It's not perfect because seeing live issues is always nice, but seeing errors and warnings inline is much nicer.

**Comment by nishant2718** [comment]
Thanks for the contribution @nayushi !! 🚀

**Pull request merged**
