### PR TITLE
Update FXIOS-9475 Update qwant search engine logo

### PR DESCRIPTION
**Pull request by ih-codes**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-9475)
(Github ticket did not sync)

## :bulb: Description
Updated the Qwant search engine to the new logo.

**Old**:

Screenshot 2024-07-10 at 1 04 59 PM
Screenshot 2024-07-10 at 1 04 57 PM

**New:**

Screenshot 2024-07-10 at 1 00 32 PM

Screenshot 2024-07-10 at 1 00 14 PM

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by ih-codes** [comment]
After reviewing the [search engine documentation](https://github.com/mozilla-mobile/firefox-ios/wiki/Search-Engines-in-Fx-IOS), I used the given 16pt SVG asset, converted that to a PNG, then grabbed the image data URL using the firefox inspector to update the XML file. Not sure if we have another process for this?

I was concerned that the image data shrunk so much, though things appear okay in the sim. @nbhasin2

**Review by nbhasin2 — APPROVED** [review]
I remember this!

**Comment by ih-codes** [comment]
@nbhasin2 You can merge this if it looks good on your physical device too!

**Review by nbhasin2 — APPROVED** [review]

**Comment by nbhasin2** [comment]
> @nbhasin2 You can merge this if it looks good on your physical device too!

Looks good on my device :shipit:

**Pull request merged**
