### PR TITLE
Refactor [v108] Refactor code to work with app-services v95.0.1

### PR DESCRIPTION
**Pull request by bendk**
This requires updating things to work with the new error hierarchy.

### CODE REVIEW

**Comment by lmarceau** [comment]
Hello! Should we also upgrade A-S to 95.0.0 with this PR? cc: @nbhasin2

**Comment by lmarceau** [comment]
> Yes you should. I wasn't sure what the steps were to do it. I actually thought it was automatic, since we updated rust-components-swift, but now realize that there needs to be a manual step.

I'm not sure I can push on your branch, but the upgrade was done by a github-action on the branch [here](https://github.com/mozilla-mobile/firefox-ios/pull/12288/files). Would you mind bringing this change into your branch?

**Comment by bendk** [comment]
Thanks for the link, I just rebased the code to include that change.

**Comment by lmarceau** [comment]
Note: on hold for now since needs adjustments in A-S

**Comment by bendk** [comment]
Made an app-services 95.0.1 release to address the error and updated this PR to use it.  I think this should be ready now :crossed_fingers: .

**Review by lmarceau — APPROVED** [review]

**Pull request merged**
