### PR TITLE
Remove [v114] SyncManagerDeviceType, replacing it with DeviceType.

### PR DESCRIPTION
**Pull request by mhammond**
This is a companion to https://github.com/mozilla/application-services/pull/5316. CC @lougeniaC64 

[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-TODO)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/TODO)

### CODE REVIEW

**Review by lougeniaC64 — APPROVED** [review]
LGTM!

**Comment by nbhasin2** [comment]
Seeing the following error for the change 
cc @lougeniaC64 
```
❌  Providers/RustSyncManager.swift:394:46: cannot convert value of type 'DeviceType' to expected argument type 'SyncManagerDeviceType'
                                kind: device.deviceType))
```

**Comment by lougeniaC64** [comment]
> Seeing the following error for the change cc @lougeniaC64
> 
> ```
> ❌  Providers/RustSyncManager.swift:394:46: cannot convert value of type 'DeviceType' to expected argument type 'SyncManagerDeviceType'
>                                 kind: device.deviceType))
> ```

@nbhasin2 Sorry I was a bit premature with my approval. Until an a-s release is cut with the changes in [a-s PR #5316](https://github.com/mozilla/application-services/pull/5316) and the a-s version is bumped in this PR, the build will fail.

**Comment by tarikeshaq** [comment]
This was done in #14225 and is safe to close!

**Comment by lmarceau** [comment]
Ok closing then!

**Pull request closed without merging**
