### PR TITLE
Add FXIOS-6673 [v117] Tabs count telemetry

### PR DESCRIPTION
**Pull request by nishant2718**
## :scroll: Tickets
[FXIOS-6673](https://mozilla-hub.atlassian.net/browse/FXIOS-6673)
https://github.com/mozilla-mobile/firefox-ios/issues/14906

## :bulb: Description

Tabs quantity telemetry added, following the characteristics described in the JIRA ticket (counter metric type).

One thing to note is that Tabs Quantity telemetry is currently being tracked in a DIFFERENT way. But I assume DS is aware of it and cannot make use of that telemetry collection, so asked for it to be done as described in the JIRA ticket. 

Note the PR and issue of already existing telemetry capture:
- [FXIOS-3514]https://mozilla-hub.atlassian.net/browse/FXIOS-3514
- https://github.com/mozilla-mobile/firefox-ios/issues/9627

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and ensured the tests suite is passing
- [ ] Implemented accessibility and tested on UI related work (minimum Dynamic Text and VoiceOver)
- [ ] Updated documentation / comments for complex code and public methods if needed

### CODE REVIEW

**Comment by nishant2718** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?
How many normal, private and inactive tabs a user currently has open. 

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? 
So the business can determine how many tabs users have of each type.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?
Using the existing cumulative_count metric, but this metric adds tabs to the count each time the user goes into the background. This means a user with a 100 tabs opened but that goes to the background 10 times would have a cumulative count of 1000. This does not tell us that he has 100 tabs only opened. 

4) Can current instrumentation answer these questions?
No

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>Normal tabs amount</td>
    <td>Category 2</td>
    <td>https://github.com/mozilla-mobile/firefox-ios/issues/14906</td>
  </tr>
  <tr>
    <td>Private tabs count</td>
    <td>Category 2</td>
    <td>https://github.com/mozilla-mobile/firefox-ios/issues/14906</td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.

Link to description [here](https://github.com/mozilla-mobile/firefox-ios/blob/440cf137515f213a797815626bf9a293f2025921/Client/metrics.yaml)

7) How long will this data be collected?  Choose one of the following:
This data will be collected for 6 months initially (potentially renewable).

8) What populations will you measure?
All users

9) If this data collection is default on, what is the opt-out mechanism for users?
In Firefox iOS there is a settings preference for telemetry labeled "Send Usage Data" that will be used as the opt-out mechanism.

10) Please provide a general description of how you will analyze this data.
We will look at how many tabs users have opened. Only the quantity is recorded.

11) Where do you intend to share the results of your analysis?
Internal

12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so:
None

**Comment by dnarcese** [comment]
Normal tabs should not include inactive tabs.
Also, what is the number we are sending? Is it 'at this point in time, I have X tabs open', or is it adding the number of tabs throughout the day? I believe that was the problem with our current metric - it was adding 5 + 5 + 3 every time I sent the ping

**Comment by nishant2718** [comment]
Okay! Will update to remove inactive tabs counting from normal tabs.

With this new telemetry, we are sending tab count for each tab type, not a cumulative. Cumulative is also in place and is getting sent, but that's telemetry that's pre-existing.

**Comment by dnarcese** [comment]
R+
# Data Review Form

_1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?_ 

Yes, telemetry is documented at https://dictionary.telemetry.mozilla.org/apps/firefox_ios

_2) Is there a control mechanism that allows the user to turn the data collection on and off?_ 

Yes, Firefox iOS provides data controls in the app settings

_3) If the request is for permanent data collection, is there someone who will monitor the data over time?_

This will be reviewed by me every 6 months

_4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?_

Type 2

_5) Is the data collection request for default-on or default-off?_

Default on

_6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?_

No

_7) Is the data collection covered by the existing Firefox privacy notice?_ 

Yes

_8) Does the data collection use a third-party collection tool?_ 

No

**Comment by nishant2718** [comment]
@dnarcese I commented in the JIRA ticket but also wanna state here that we should utilize metrics collected here, if possible https://github.com/mozilla-mobile/firefox-ios/pull/10272. 

Added a Do Not Merge label for now.

**Review by thatswinnie — APPROVED** [review]

**Comment by dnarcese** [comment]
Can you find out how to look at a quantity type metric? Nothing is showing up in Looker here https://mozilla.cloud.looker.com/explore/firefox_ios/metrics?qid=xfMhphKo4tqvSbOtROABZs&toggle=vis

**Pull request closed without merging**
