### PR TITLE
Refactor MTE-98 [v107] ⚰️ Remove potentially unneeded state in FxScreenGraph

### PR DESCRIPTION
**Pull request by clarmso**
Through the work on refactoring the history tests, I discovered that `Action.OpenSearchBarFromSearchButton` should not have the `stopReloadButton` available. Removing such a state may result in workaround not required in the history tests.

https://mozilla-hub.atlassian.net/browse/MTE-98

### CODE REVIEW

**Comment by isabelrios** [comment]
Thanks for this PR @clarmso! We definitely need to update this file. Can we do more clean up using this PR? since we are modifying only one file, I would try to do as many updates as possible here.

For example, we had this modification pending to do in the FxScreenGraph: https://github.com/mozilla-mobile/firefox-ios/pull/12012#discussion_r978745638

And there might be more...I can take a look and point several more

**Comment by clarmso** [comment]
I've identified the `Action` that is not used currently. I afraid that I may be removing too much code: Some code that may be needed in the future.

Please feel free to comment on the diff. 📝

**Comment by clarmso** [comment]
Argh. I cannot just use a simple text search to determine if a piece of code is used or not. Using the latest version of `FxScreenGraph.swift`, some previously passing tests from History started to fail (locally on my computer). In particular, the change causes something missing for `NewTabScreen`.

Oops, I rebased this branch and introduced extraneous changes. Let me open a new PR.

**Comment by isabelrios** [comment]
> 

Let me know if you need help with this... Also, there might be something related to M1, if tests pass on Bitrise (Intel) that is fine.
For example, the swipe gesture to remove a history item does not work on M1, if you could add a condition, like the one we have in screengraph (see [here](https://github.com/mozilla-mobile/firefox-ios/blob/e643b1577929d581c826587dd4d076e42d96def3/Tests/XCUITests/FxScreenGraph.swift#L995)) for these type of issues, it would be great...

**Pull request closed without merging**
