### PR TITLE
Bugfix FXIOS-6611 [v116] Fix line design on URL bar

### PR DESCRIPTION
**Pull request by lmarceau**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-6611)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/14788)

### Description
Fix line height (was 1 pixel instead of 0.5) and fix that it was disappearing.

#### Dark mode top and bottom
Screenshot 2023-06-13 at 2 36 12 PM

Screenshot 2023-06-13 at 1 49 41 PM

#### Dark mode overlay mode, top and bottom
Screenshot 2023-06-13 at 2 36 20 PM

Screenshot 2023-06-13 at 2 02 16 PM

#### Light mode top and bottom
Screenshot 2023-06-13 at 2 37 30 PM

Screenshot 2023-06-13 at 2 19 03 PM

#### Light mode overlay mode, top and bottom
Screenshot 2023-06-13 at 2 37 34 PM

Screenshot 2023-06-13 at 2 19 07 PM

### Pull requests checks where applicable
- [X] Fill in the three TODOs above (tickets number and description of your work)
- [X] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [ ] Unit tests written and passing
- [ ] Documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by cwzilla** [comment]
The lines look good!

What is the distance between the top/bottom of the address bar to the line? Wondering if we should increase the space by a tiny bit so when the URL bar is in focus mode it won't look like they're touching.

**Review by thatswinnie — APPROVED** [review]

**Comment by lmarceau** [comment]
> What is the distance between the top/bottom of the address bar to the line? Wondering if we should increase the space by a tiny bit so when the URL bar is in focus mode it won't look like they're touching.

Yeah it's true they seems to be touching in the case of the bottom bar. I'll have a look into what we can do

**Comment by lmarceau** [comment]
Made some adjustments and here's what I have now

### Dark mode
Screenshot 2023-06-14 at 3 06 58 PM
Screenshot 2023-06-14 at 3 06 40 PM
Screenshot 2023-06-14 at 3 07 03 PM
Screenshot 2023-06-14 at 3 06 45 PM

### Light mode
Screenshot 2023-06-14 at 3 07 57 PM
Screenshot 2023-06-14 at 3 08 16 PM
Screenshot 2023-06-14 at 3 08 01 PM
Screenshot 2023-06-14 at 3 08 12 PM

### iPad dark mode
Screenshot 2023-06-14 at 3 09 30 PM
Screenshot 2023-06-14 at 3 09 35 PM

### iPad light mode
Screenshot 2023-06-14 at 3 08 33 PM
Screenshot 2023-06-14 at 3 08 44 PM

**Comment by lmarceau** [comment]
@cwzilla and while we're at it, are the colors with iPad top tabs right? I'm not entirely sure (if not I can open another issue so we fix those).

**Comment by lmarceau** [comment]
Scratch my latest changes - realized this breaks the URL bar entirely when typing in it lol. I'm afraid the line spacing will need to stay as is for now. This has a lot of ramifications and I feel this goes beyond the scope of this ticket.

**Comment by lmarceau** [comment]
Build is green [here](https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/93431807-3435-4c96-8635-05b444d55bf6)

**Comment by cwzilla** [comment]
@lmarceau ok no worries. iPad tab colours look good!

**Pull request merged**
