### PR TITLE
Fix UIView.isHidden must be used from main thread only

### PR DESCRIPTION
**Pull request by muhasturk**

### CODE REVIEW

**Comment by garvankeeley** [comment]
Thanks for catching this. I think the bug is that FirefoxAccountStateChange notification should be wrapped to notify on the main thread.

**Comment by muhasturk** [comment]
> Thanks for catching this. I think the bug is that FirefoxAccountStateChange notification should be wrapped to notify on the main thread.

I could fix by wrapping FirefoxAccountStateChange post notification. Which way is more suitable for you?

```swift
DispatchQueue.main.async {
    NotificationCenter.default.addObserver(self, selector: #selector(appMenuBadgeUpdate), name: .FirefoxAccountStateChange, object: nil)
}
```

**Comment by garvankeeley** [comment]
Yes that would be a good fix

**Comment by muhasturk** [comment]
Pushed

**Pull request merged**
