### PR TITLE
Refactor FXIOS-5905 [v113] made MockHistoryHighlightsDataAdaptor's delegate weak, add memory leak unit test

### PR DESCRIPTION
**Pull request by cschumake**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-5905)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/13443)

### Description
- Made MockHistoryHighlightsDataAdaptor's delegate weak
- Added memory leak unit test for HistoryHighlightsDataAdaptorImplementation

### Pull requests checks where applicable
- [x] Fill in the three TODOs above (tickets number and description of your work)
- [x] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [x] Unit tests written and passing
- [ ] Documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by mte-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Edited 2 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 0 files</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 639b8c8afa61c6fc2997015472e46ff9201cfea4
</p>

**Review by lmarceau — APPROVED** [review]
Thank you @cschumake !

**Comment by lmarceau** [comment]
There was an artefact issue on Bitrise when running the build. I'll close and reopen the PR to retrigger it.

**Comment by lmarceau** [comment]
@cschumake no problem on your end, we're just having some issues with Bitrise today it seems. I'll run the tests locally and then we should be good to merge.

**Comment by lmarceau** [comment]
Ran the tests locally, all seems good! Merging.

**Pull request merged**
