### PR TITLE
Removed NSPhotoLibraryUsageDescription for iOS14 default browser support

### PR DESCRIPTION
**Pull request by nbhasin2**
**Note:** Couldn't find any place in our app that we use this string. 

We only use the one where we save but not upload pic. 

image

### CODE REVIEW

**Comment by nbhasin2** [comment]
PS. should just merge as I highly doubt if BB is building PR made against iOS14 branch. 

iOS14 branch itself should Build thought

**Comment by kaylagalway** [comment]
I believe that any website that let's you upload a photo would launch our photo uploader and ask for firefox photo permissions, so we may still need this upload string and to switch to the new picker?

**Comment by kaylagalway** [comment]
> I believe that any website that lets you upload a photo would launch our photo uploader and ask for firefox photo permissions, so we may still need to switch to the new photo picker in order to get rid of this plist string?

On second thought - it seems photo uploads on websites bypass Firefox completely, and we never use `UIImagePickerController`. The web applications must be handling mobile uploads in their code, so iOS permissions are not required from us.

**Comment by nbhasin2** [comment]
Good find @kaylagalway this is likely why https://imgbb.com/ just launches imagepicker but there is none built in Firefox.

**Pull request merged**
