### PR TITLE
Bugfix MTE-1045 [v115] Forward button for both iPhone and iPad

### PR DESCRIPTION
**Pull request by clarmso**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/MTE-1045)

### Description
Some accessibility identifiers are applied inconsistently between iPhone and iPad: https://github.com/mozilla-mobile/firefox-ios/issues/14539. The issue on the "Foward" ➡️ button causes some tests to fail on iPad or on both platforms (`testTabHistory`, `testNavigation` and `testLandscapeNavigationWithTabSwitch`). Since the tests are unable to locate the button, the tests fail.

This PR is to apply the label/identifier that works for the current state of the app to rule out legitimate test failures in the near future.

### Pull requests checks where applicable
- [X] Fill in the three TODOs above (tickets number and description of your work)
- [X] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [ ] Unit tests written and passing
- [ ] Documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by clarmso** [comment]
I rerun the previously aborted `Smoketest2` and it passed.
https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/42ff3a5c-4d28-479b-b071-77e14e6b62d4

**Comment by lmarceau** [comment]
I opened a PR that will hopefully fix this problem 🤞https://github.com/mozilla-mobile/firefox-ios/pull/14595

**Comment by clarmso** [comment]
https://github.com/mozilla-mobile/firefox-ios/pull/14595 addresses some issues on the identifiers and labels. Let me wait until #14595 is merge and then investigate again.

**Comment by clarmso** [comment]
@lmarceau 's work on https://github.com/mozilla-mobile/firefox-ios/pull/14595 supersede this PR. 🎉

**Pull request closed without merging**
