### PR TITLE
Warnings Cleanup

### PR DESCRIPTION
**Pull request by muhasturk**
Fix Followings

- Skipping duplicate build file in Copy Bundle Resources build phase: /Users/tcmhasturk/Documents/Work/firefox-ios/Client/en.lproj/InfoPlist.strings
- Skipping duplicate build file in Compile Sources build phase: /Users/tcmhasturk/Documents/Work/firefox-ios/Client/Frontend/Home/PanelDataObservers.swift
- The CFBundleShortVersionString of an app extension ('1.0') must match that of its containing parent app ('0.0.1').

### CODE REVIEW

**Comment by muhasturk** [comment]
> This pull request has conflicts when rebasing. Could you fix it @muhasturk?

fixed

**Comment by lmarceau** [comment]
Just to note:
This was the Xcode warnings in the UI before:
warnings_before

And now after:
warnings_after

This warning is also fixed in this PR:
also_fixed

**Review by lmarceau — DISMISSED** [review]

**Comment by lmarceau** [comment]
Ah sorry I approved but then just realized that indeed the warning is fixed for `PanelDataObservers` but we still see the file in two places. I would suggest we only keep it as a reference in one folder, maybe in the Providers folder. 
Screen Shot 2021-11-05 at 11 38 54 AM

**Comment by lmarceau** [comment]
Closing this PR here since I reopened it with the rebase and small comment fix [here](https://github.com/mozilla-mobile/firefox-ios/pull/9759/checks?check_run_id=4779069474)

**Pull request closed without merging**
