### PR TITLE
Add FXIOS-9927 - Enable Password Manager In Private Tabs

### PR DESCRIPTION
**Pull request by issammani**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-9927)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/21780)

## :bulb: Description
This PR:
- Removes `tab.isPrivate` check when injecting password manager in a tab. 
- For more context see [this slack thread](https://mozilla.slack.com/archives/C02KRP2SH7Y/p1725313307966849).

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] ~Wrote unit tests and/or ensured the tests suite is passing~
- [ ] ~When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)~
- [ ] ~If needed, I updated documentation / comments for complex code and public methods~
- [ ] ~If needed, added a backport comment (example `@Mergifyio backport release/v120`)~

### CODE REVIEW

**Review by nbhasin2 — APPROVED** [review]
Cc @razvanlitianu for second set of eyes

**Review by razvanlitianu — APPROVED** [review]

**Comment by razvanlitianu** [comment]
@issammani should we uplift this for v131?

**Comment by issammani** [comment]
> @issammani should we uplift this for v131?

I think that makes sense. cc @afurlan-firefox

**Comment by issammani** [comment]
@mergify backport release/v131

**Pull request merged**
