### PR TITLE
Bugfix FXIOS-5457 [v112] Adjust "Sync and Save Data" button width

### PR DESCRIPTION
**Pull request by rilury**
This PR will fix Sync and Save Data button width for iPad and also for iPhone in landscape orientation.

### CODE REVIEW

**Comment by mte-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Project coverage: 30.15%</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Edited 1 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 0 files</td>
    </tr>
  </tbody>
</table>

## Client.app: Coverage: 27.05
| File | Coverage ||
| --- | --- | --- |
RemoteTabsErrorCell.swift | 0.0% | ⚠️

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 95bb2dce90b79eb4af99f24b632d2d99b4af0807
</p>

**Comment by nbhasin2** [comment]
@Mergifyio backport release/v110.2

**Comment by lmarceau** [comment]
@mergifyio backport release/v111.0

**Comment by JohanLorenzo** [comment]
@mergifyio backport release/v111.0

**Comment by JohanLorenzo** [comment]
@Mergifyio backport release/v111.0

**Comment by JohanLorenzo** [comment]
I figured out why we got this error in https://github.com/mozilla-mobile/firefox-ios/pull/13319#issuecomment-1458137517. I don't know how it happened but the branch `mergify/bp/release/v111.0/pr-13319` somehow already existed on this repo. That's why Mergify couldn't create the PR. I deleted the branch, then mergify could make the backport correctly.

**Pull request merged**
