### PR TITLE
Refactor  FXIOS-8557 [v125] Update GitHub actions to latest versions

### PR DESCRIPTION
**Pull request by isabelrios**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-TODO)

Please see slack thread for more info: https://mozilla.slack.com/archives/C04J0S92Z8X/p1709661199164479?thread_ts=1709652153.436889&cid=C04J0S92Z8X

## :pencil: Checklist
You have to check all boxes before merging
- [ ] Filled in the above information (tickets numbers and description of your work)
- [ ] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by flodolo** [comment]
Rebased since there was a conflict with the Rust workflow unification.

Also:
* Changed the l10n workflows to make them more consistent, and shortened the names.
* Removed duplicate Glean workflow

**Comment by flodolo** [comment]
Note that the l10n workflows remain quite different, with the FIrefox one much more complex.

**Comment by isabelrios** [comment]
> Note that the l10n workflows remain quite different, with the FIrefox one much more complex.

Since Focus was in maintenance we did not apply some of the changes we did to Firefox's one, for example, we added some more steps to automatically add the [v12x] version to the PR title. We were running the github action weekly instead of daily. If it makes sense to change to daily and consolidate both github actions into one, we could do that. 
We are working in one github action at a time to not to mix several in a PR.

**Comment by flodolo** [comment]
I would probably keep the l10n workflows separate, if nothing else for clarity when looking at the commit history.

**Comment by isabelrios** [comment]
We will add the script to set the target version in the PR title for focus github action.

**Comment by isabelrios** [comment]
need to close-repopen to trigger bitrise (something was not working with regular re-try)

**Review by AaronMT — APPROVED** [review]

**Pull request merged**
