### PR TITLE
NTP Stretch Goals

### LINKED ISSUE #8206: FXIOS-1634 ⁃ New Tab Page stretch goal: recolour backgrounds
https://www.figma.com/file/WboC4Dn9iu9wie2GodfSAg/Post-MR1?node-id=631%3A27544

| Element | Theme | Current | Proposed |
| --- | --- | --- | --- |
| New Tab Page background | Light | `white` | `Light Grey 10` `#f9f9fb` |
|  | Dark | `#29282d` | `Dark Grey 60` `#2b2a33` |
| Shortcut Tile background | Light | `transparent` | `white` |
|  | Dark | `transparent` | `Dark Grey 30` `#42414d` |

new-tab-page

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1634)

### LINKED ISSUE #8207: FXIOS-1635 ⁃ New Tab Page stretch goal: change text styles and colours
Figma: https://www.figma.com/file/WboC4Dn9iu9wie2GodfSAg/Post-MR1?node-id=631%3A27544
## Text styles

| Element | Proposed |
| --- | --- |
| Headings | Title 3 [`UIFontTextStyleTitle3`](https://developer.apple.com/documentation/uikit/uifonttextstyle) || Headings | 
| Links to the side of headings (e.g. “More”) | Subheadline [`UIFontTextStyleSubheadline`](https://developer.apple.com/documentation/uikit/uifonttextstylesubheadline) |
| Pocket article text | Subheadline [`UIFontTextStyleSubheadline`](https://developer.apple.com/documentation/uikit/uifonttextstylesubheadline) |
| Shortcut tile labels | Caption 1 [`UIFontTextStyleCaption1`](https://developer.apple.com/documentation/uikit/uifonttextstylecaption1) |

## Colours

| Element | Theme | Proposed |
| --- | --- | --- |
| Text and headings (this also applies to Pocket) | Light | `Dark Grey 90` `#15141a` |
|  | Dark | `Light Grey 05` `#fbfbfe` |
| Links to the side of headings (e.g. “More” – this also applies to Pocket) | Light | `Blue 50` `#0060df` |
|  | Dark | `Blue 20` `#00ddff` |
| Pin icon | Light | `Dark Grey 05` `#5b5b67` | 
|  | Dark | `Light Grey 05` `#fbfbfe` |

new-tab-page

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1635)

### LINKED ISSUE #8208: FXIOS-1636 ⁃ New Tab Page stretch goal: add shadow to shortcut tiles
Figma: https://www.figma.com/file/WboC4Dn9iu9wie2GodfSAg/Post-MR1?node-id=631%3A27544

| Element | Theme | Proposed |
| --- | --- | --- |
| Shortcut tile shadow | Light | `Drop shadow Radius: 6 pt, Offset: 0 pt 2 pt, rgba 0.23, 0.22, 0.27, 0.2` |
|  | Dark | `Drop shadow Radius: 6 pt, Offset: 0 pt 2 pt, rgba 0.11, 0.11, 0.13, 0.5` |

Inspect the `Tile` object using Figma to see full shadow values.

Screen Shot 2021-05-12 at 3 34 40 PM Screen Shot 2021-05-12 at 3 36 56 PM

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1636)

### LINKED ISSUE #8209: FXIOS-1637 ⁃ New Tab Page stretch goal: reorder the position of History
Figma: https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=631%3A27544

History used to be the last (4th) item on the list, taking the place of Synced Tabs. We’d like to reorder its position to be the 2nd item on the list.

The new order is (left to right):

- Bookmarks
- History
- Downloads
- Reading List

This mirrors the ordering in both the Library Tray, and the Main Application Menu.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1637)

### LINKED ISSUE #8210: FXIOS-1639 ⁃ New Tab Page stretch goal: Restyle and resize shortcut tiles
Figma: https://www.figma.com/file/WboC4Dn9iu9wie2GodfSAg/Post-MR1?node-id=631%3A27544

- Library shortcut tiles are currently sized and styled differently than all other shortcut tiles. Let’s make them identical.
- Shortcut tiles currently have content that fill the whole container. Let’s resize them so they’re smaller.

### Shape

| Element | Current | Proposed |
| --- | --- | --- |
| Library tiles | Oval | Rounded rect, border radius 8 with smooth corner |
| Shortcut tiles | Rounded rect, border radius 4 with smooth corner | Rounded rect, border radius 8 with smooth corner |

### Size of Content

| Element | Current | Proposed |
| --- | --- | --- |
| Library tiles content | 16×16px | 24×24px (same as all other icons within the app), centred in container |
| Shortcut tiles content | Fill container, no padding | 36×36px, centred in container, border radius 4 with smooth corner |

Screen Shot 2021-05-12 at 3 28 01 PM Screen Shot 2021-05-12 at 3 27 36 PM

### Background colour
All shortcut tiles, including Library ones, should have the same background colours. This is already addressed by #8206.

### Library icon colours

From left to right:

| Element | Proposed |
| --- | --- |
| Bookmarks | `Blue 40` `#0090ed` |
| History | `Violet 50` `#9059ff` |
| Downloads | `Green 60` `#2ac3a2` |
| Reading List | `Pink 40` `#ff4aa2` |

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1639)

### LINKED ISSUE #8211: FXIOS-1638 ⁃ New Tab Page stretch goal: remove "See All" link from Your Library
Figma: https://www.figma.com/file/lfgj15zbNkL9Pp4hdZGJgp/Proton-Mobile-UI?node-id=631%3A27544

Previously, Your Library contains one extra item: History.

Now that History is visible in this section, it no longer makes sense to have a link to “See All”. Let’s remove it.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1638)

### PR DESCRIPTION
**Pull request by q2r5**
Fixes #8206, fixes #8207, fixes #8208, fixes #8209, fixes #8210, fixes #8211

<table>
<tr>
	<td>
		Simulator Screen Shot - iPhone 11 Pro - 2021-04-20 at 17 48 45
	<td>
		Simulator Screen Shot - iPhone 11 Pro - 2021-04-20 at 17 49 37
</table>

### CODE REVIEW

**Comment by dnarcese** [comment]
Could you update this to use the colours that just landed in this commit https://github.com/mozilla-mobile/firefox-ios/commit/7217539cabcf0a0c8cd1b5291e5879aa90dd1c08

**Review by dnarcese — CHANGES_REQUESTED** [review]
Here is a screenshot of the Figma mock:
A few things that need to be updated:
- the size of the tiles should be 60x60
- the size of the Library button images should be 22x22
- headings should be bolded
image

**Review by dnarcese — CHANGES_REQUESTED** [review]
- headers shouldn't be bold
- spacing between headers and content should be 16px
- spacing between tile and title should be 8px
- pin icon should be right beside the title
image

- tile titles should wrap to a second line
- placeholder top site size is too big
- collection view is not dynamic for screen size: as seen on iPhone SE
Simulator Screen Shot - iPhone SE - 2021-04-26 at 12 04 40

**Comment by q2r5** [comment]
Simulator Screen Shot - iPod touch (7th generation) - 2021-04-26 at 21 24 45

Here's an updated screenshot for smaller screens.

**Review by dnarcese — CHANGES_REQUESTED** [review]
Getting closer! Thanks for all your hard work.

There seem to be some constraint issues on iPhone SE with iOS 12.4 specifically. Let me know if you would like suggestions on how to fix this.
Simulator Screen Shot - iPhone SE - 2021-05-19 at 15 52 49

- Is it possible to add a small space between the pin and the site title like in the mocks?

**Comment by q2r5** [comment]
Simulator Screen Shot - iPhone SE (1st generation) - 2021-05-19 at 22 30 35

Fixed the iOS 12.4 issue and the clipped shadows. The pin spacing was fixed in a prior commit, but can be increased if needed.

**Comment by dnarcese** [comment]
@brampitoyo looking for a UX review from you on the last screenshot ^

**Comment by dnarcese** [comment]
Need to check #8531 against this PR

**Comment by brampitoyo** [comment]
@dnarcese @q2r5 Thanks for all your work on this!

I just returned from PTO, and think that we’re almost there.

Comparing your current screenshot and the design spec (on iPhone SE 1st Gen):

| Current | Proposed |
| --- | --- |
|  | New Tab Page - iPhone - Light@2x |

The remaining changes I would recommend are:

- Increase font-weight of headings: semibold `600`
- Size “pin” icon so it appears sharp: 16x16
- Baseline text align “Recommended by Pocket” and “More” (“More” is currently nudged up)

Additionally, here are two changes that MR2 is expecting on the New Tab Page, that we can land now. We can either do it as part of this issue, or create a new one:

- Remove heading: “Shortcuts”
- Remove section: “Your Library” (we will have these items easily accessible in our main application menu)

**Comment by q2r5** [comment]
Simulator Screen Shot - iPod touch (7th generation) - 2021-05-30 at 22 32 20

Unfortunately, there doesn't seem to be an 'approved' way to set a specific font weight to a system text style. Per the [HIG](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography/), the only 'Dynamic Type' that is available in semi-bold is `.headline`, which would be a drop in font size of 3pt.

**Comment by brampitoyo** [comment]
@q2r5 Thanks for confirming that!

If there’s no system-approved way to set font weight, I’d be happy to go with your current implementation. This will help ensure that our type will resize dynamically.

All the changes look good to me!

**Review by dnarcese — APPROVED** [review]
There are some accessibility bugs when we make the font size larger - but lets get this merged and we can fix that in another issue.

**Comment by dnarcese** [comment]
@q2r5 Sorry, can we add back the Library section. @brampitoyo chatting with Ashley, she would like to keep it for now and removing it will be in an A/B test.

**Comment by q2r5** [comment]
Library removal should be reverted now.

**Pull request merged**
