### PR TITLE
Bugfix #9894 - Fixed login issues with A~S by combining components into single MozillaAppServices dlyb

### PR DESCRIPTION
**Pull request by nbhasin2**
Also, updated A~S to its official v91.0.1 release

This is a cleaned-up version of https://github.com/mozilla-mobile/firefox-ios/pull/9938

Co-authored-by: Sammy Khamis <skhamis@mozilla.com>
Co-authored-by: Tarik Eshaq <teshaq@mozilla.com>

### CODE REVIEW

**Review by tarikeshaq — APPROVED** [review]
Awesome 🎉 🎉 !!!
Tested this locally:
- FxA login works
- Syncing works
- Sending tabs works
- Nimbus fetching experiments works
- RustLogs are visible in the xcode logger

:shipit: from me!

**Comment by nbhasin2** [comment]
I am going to try this on M1 VM and also run a few tests before merging it in

**Review by skhamis — APPROVED** [review]
🚀

**Comment by nbhasin2** [comment]
image

The test that is failing on BR passes locally

**Review by yoanarios — APPROVED** [review]

**Pull request merged**
