### PR TITLE
AppServices Places Uniffication Updates

### PR DESCRIPTION
**Pull request by lougeniaC64**
This PR handles the breaking changes created by [the places uniffication work](https://github.com/mozilla/application-services/pull/4770) which was released in [a-s v90.0.0](https://github.com/mozilla/application-services/releases/tag/v90.0.0). The uniffication process is a refactor of our API using [the Uniffi tool](https://github.com/mozilla/uniffi-rs) and doesn't include any significant logical changes.

**Note:** Until that release is cut, this PR will not pass CI.

### CODE REVIEW

**Comment by nishant2718** [comment]
Looks good! Will wait on v90 and a 👍 BR run.

**Comment by lougeniaC64** [comment]
> Looks good! Will wait on v90 and a 👍 BR run.

Great! Thanks @nishant2718! 🎉

**Comment by nbhasin2** [comment]
Merging this to SPM branch

**Comment by nbhasin2** [comment]
This is required so we can get A~S v90.0.1

**Pull request merged**
