### PR TITLE
Fix #5450 - Use globe icon for default favicon

### LINKED ISSUE #5450: Use globe icon for default favicon
CURRENT (cropped screen of all tabs)
IMAGE 2019-09-13 14:59:13

PROPOSED
https://design.firefox.com/icons/viewer/#globe

### PR DESCRIPTION
**Pull request by isabelrios**
This PR tries to fix #5450 

First time doing this but wanted to try and help with some (easy) issues.
I took the image from the issue and converted it to have all sizes/resolutions but I may have done that process incorrectly or there is a better way...

### CODE REVIEW

**Comment by garvankeeley** [comment]
Thanks for tackling this! The image sizes don't seem correct, they should be rough 30,60,90 px in size but they aren't increasing in size like that (instead it is 30,50,58)

**Comment by isabelrios** [comment]
> Thanks for tackling this! The image sizes don't seem correct, they should be rough 30,60,90 px in size but they aren't increasing in size like that (instead it is 30,50,58)
> 

Oh, okay sorry about that 🙈  let me check if I can change the images to use those sizes!

**Comment by garvankeeley** [comment]
This is what the other default icon looks like image

**Comment by npark-mozilla** [comment]
@isabelrios checking through the PRs and noticing ones that have been around for a while- I guess this is good for merge?

**Comment by isabelrios** [comment]
> @isabelrios checking through the PRs and noticing ones that have been around for a while- I guess this is good for merge?

not yet, we are waiting for the correct icons to be shared with us so that we can use them here. Then ones in this PR are not sizewise correct yet.

**Comment by garvankeeley** [comment]
Feel free to re-open, just leaning up the PR list

**Pull request closed without merging**
