### PR TITLE
Adjust Empty State View to stay in center of empty Reading List

### PR DESCRIPTION
**Pull request by finebel**
This PR adjust the Empty State View for an empty Reading List so that it stays in the center. See #9870 for reference.
New Empty State View:

Simulator Screen Shot - iPhone 13 - 2022-01-26 at 22 27 52

Simulator Screen Shot - iPhone 13 - 2022-01-26 at 22 27 47

### CODE REVIEW

**Comment by lmarceau** [comment]
@finebel Thanks for noting this issue! 
So I tested on iPad and here is how it looks like:

Simulator Screen Shot - iPad Pro (9 7-inch) - 2022-01-27 at 18 03 04

One suggestion to improve is to center vertically like our sync page in the tab tray (centered on both iPhone and iPad).
Simulator Screen Shot - iPad Pro (9 7-inch) - 2022-01-27 at 18 03 28

Could you have a look into that? 🙏

**Comment by finebel** [comment]
Ok, then it would like so:
iPhone:

Screenshot 2022-01-28 at 10 40 20

iPad:
Screenshot 2022-01-28 at 10 38 44

Notice that I have added a vertical offset, because I think it looks better. Without the offset the empty state view is displayed like so:
Screenshot 2022-01-28 at 10 34 55

**Comment by lmarceau** [comment]
Mmmh 🤔 @dnarcese do we have designs for this page? Not sure what was the initial look and how it should be fixed.

**Comment by dnarcese** [comment]
@lmarceau Let's follow the design of our other empty states like Synced Tabs and Downloads. ie use that vertical offset instead of centreing

**Comment by lmarceau** [comment]
@finebel Sorry for the change, could you use the same spacing as the Download page then? 🙏 Thanks so much!
Screen Shot 2022-01-28 at 1 40 06 PM

**Comment by finebel** [comment]
Ok, i will look into it later...

**Comment by finebel** [comment]
Now the Empty State View for the Reading List uses the same top padding as the Empty State View for the Downloads Tab (120).

**Comment by lmarceau** [comment]
Hey @finebel, could you rebase with main? So BR can run with latest fixes 👍 Thanks!

**Comment by finebel** [comment]
Like so?

**Comment by lmarceau** [comment]
@finebel Mhh, something went wrong, there isn't supposed to be that many file change:

Screen Shot 2022-02-02 at 8 10 47 PM

You can maybe revert your last commit, and instead merge latest main into your branch. This will also work (and it's ok if history isn't perfect since when we merge to main, we squash the commits anyway). Let me know if you need any more details on this 💪

**Review by lmarceau — APPROVED** [review]
Thanks a lot @finebel 🎉

**Pull request merged**
