### PR TITLE
Refactor FXIOS-11530 [v106] Sync Tests Update Navigation Bar ID

### LINKED ISSUE #11530: [Sync Int Tests] Navigation bar's id for the FxA log in page has changed
The sync integration tests are all failing (see [logs](https://storage.googleapis.com/mobile-reports/public/firefox-ios-M1/result_215/SyncIntegrationTests/results/index.html)) because the navigation bar's id we are expecting to be sure the FxA log in site is completely loaded has changed.
We need to update [that id ](https://github.com/mozilla-mobile/firefox-ios/blob/fb24eab5caa18733ce01f893080ea7982ffdfe09/Tests/XCUITests/IntegrationTests.swift#L59)` Turn on Sync` with the new one `Sync and Save Data`:
Simulator Screen Shot - iPhone 11 - 2022-08-08 at 02 12 13

cc @jjSDET, just FYi and so that you are aware of the kind of issues related to these tests

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-4716)

### PR DESCRIPTION
**Pull request by isabelrios**
Fixes #11530

### CODE REVIEW

**Review by jjSDET — COMMENTED** [review]
Looks like `app.navigationBars["Turn on Sync"]` also exists within IntegrationTests.swift:59. Does that need updated too?

**Comment by isabelrios** [comment]
> Looks like `app.navigationBars["Turn on Sync"]` also exists within IntegrationTests.swift:59. Does that need updated too?

oh thanks! I missed that one, modifying it right away

**Review by jjSDET — COMMENTED** [review]
There are six other references to tests that interact with the `buttons["Continue"]` element:

IntegrationTests.swift: 200, 255
SaveLoginsTests.swift: 46,47,238,239

Do these need updated as well?

**Comment by isabelrios** [comment]
> There are six other references to tests that interact with the `buttons["Continue"]` element:
> 
> IntegrationTests.swift: 200, 255 SaveLoginsTests.swift: 46,47,238,239
> 
> Do these need updated as well?

Oh, that Continue button is a different one, that's for the logins view. 
Simulator Screen Shot - iPhone 11 - 2022-08-09 at 19 03 14


No need to update that one. Only the Continue button in the FxA log in page has changed.
Simulator Screen Shot - iPhone 11 - 2022-08-09 at 19 03 00

**Review by jjSDET — APPROVED** [review]

**Pull request merged**
