### PR TITLE
Bug 1256470 – Enable Passcode/Touch ID for Private Browsing Mode

### PR DESCRIPTION
**Pull request by varkor**
Hopefully this time, we’ve got it right.
This addresses all the problems with the previous version of the feature, as well as quite a number that we didn’t come across previously.
Unit tests are all passing, including new ones that catch problems that the previous patch was failing.
Localization issues should also be sorted out.

### CODE REVIEW

**Comment by sleroux** [comment]
Thanks for making the new PR and bringing the fixes over. I haven't taken a look at the code yet but ran some tests on the iPad Air 2 simulator. Found a couple more issues. Not sure how many are already present on master from top tabs work or not though.

* Launching the app after building the new branch on an iPad Air 2 simulator crashes it to crash when trying to add a tab from the top left add button while in normal mode.

* When launching a new private tab from the menu on iPad, the background color of the selected tab becomes dark themed slightly after the panel/url bar background does. Not sure if this is related to presenting the touch ID prompt or an existing bug with the top tabs implementation.

* Backgrounding the app, reentering, and tapping 'Cancel' when the passcode prompt is displayed crashes the app. Looks like it's crashing here [1]

* Turn on Touch ID for private mode. Navigate to tab tray on iPad Air 2, background the app and come back. Enter a mismatch finger. Navigating to 'Enter Passcode' presents a blank passcode screen and shows the touch ID prompt again. Pressing cancel shows the passcode entry screen as normal. Also, after pressing cancel, the tabs in the background switch to normal mode and entering the passcode doesn't toggle private mode afterwards.

* Following the above steps but in the browser view causes the app to crash when tapping on the second touch ID prompt.

[1] https://github.com/mozilla/firefox-ios/blob/master/Client/Frontend/Browser/BrowserTrayAnimators.swift#L124

**Comment by varkor** [comment]
>- Launching the app after building the new branch on an iPad Air 2 simulator crashes it to crash when trying to add a tab from the top left add button while in normal mode.

I'm having trouble reliably reproducing this one. I managed it twice, by resetting the simulator and trying to add a new tab, but now it's no longer working. It's a strange crash as well — there's an assertion in one of the private methods that's failing, but the datasource integrity seems to be intact...

>- Backgrounding the app, reentering, and tapping 'Cancel' when the passcode prompt is displayed crashes the app.

I can't reproduce this at all. Was this in the BVC or the tab tray?

Below are the issues I've encountered now. Annoyingly, I can't reproduce any of them every time yet... Working on it.
- [ ] Adding a new tab at the beginning, via the top tabs + button sometimes causes a crash.
- [ ] Occasionally, cancelling a "stay in private browsing" prompt and then switching to a home controller will cause the home controller to have the private theme still.
- [ ] There's an animation issue when transitioning to/from tab tray / BVC after hitting Cancel on the passcode view.

**Comment by varkor** [comment]
I've fixed all the issues I could find. There was at some stage an issue with the styling of the home panel controller under very rare cases, but I can no longer reproduce it — so if it is still extent, it's very much an edge case (and can probably be fixed separately if it rears its head).
Could you check to see if any of the issues are still happening for you? I think I fixed them all, but I had trouble reproducing a couple of them at one point.
It feels so close now...

**Comment by farhanpatel** [comment]
Thanks for this PR! We just finished a major migration to swift 3.0 making merging in most patches pretty difficult. If you feel like this patch is still important please feel free to update your PR to swift 3 and reopen this PR 😄

**Comment by varkor** [comment]
This was a large amount of work, and it's disappointing that it couldn't be merged before the migration, but I don't have time to update something this large now, so unless someone else is willing to pick this up, the work will probably all be lost.

**Pull request closed without merging**
