### PR TITLE
Update master with current shipping locales

### PR DESCRIPTION
**Pull request by Delphine**
(excluding 4 RTL locales)

### CODE REVIEW

**Comment by st3fan** [comment]
Not sure if we need to do this on master. The builds we do from master include all locales by default, even ones that are incomplete. Let me know if you had something else in mind with this patch.

**Comment by Delphine** [comment]
Ah ok - I believe we used to do that each time with @flodolo, but maybe I'm mistaken. We can wait for him to chime in, this wouldn't be urgent anyways.
When I look at the current shipping_locales on master it's missing a bunch of locales, but maybe you're getting them from somewhere else?

**Comment by flodolo** [comment]
We usually keep master in sync with the latest branch to avoid confusion.

Since there's already a v10.x branch, you need two PRs.

**Comment by flodolo** [comment]
Never mind, I missed #3411 because it was already merged.

**Comment by flodolo** [comment]
Not sure if someone can merge this, overriding the buddybuild check, or rerun it.

**Pull request merged**
