### PR TITLE
Add EXP-3764 [v119] Updates to allow for experiment integration tests to run locally.

### PR DESCRIPTION
**Pull request by jrbenny35**
## :scroll: Tickets
https://mozilla-hub.atlassian.net/browse/EXP-3764

## :bulb: Description
Adds the capability to run the experiment integration tests locally

## :pencil: Checklist
You have to check all boxes before merging
- [✅] Filled in the above information (tickets numbers and description of your work)
- [✅] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [✅] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by jrbenny35** [comment]
I can't change this to draft, will update when I can

**Comment by lmarceau** [comment]
@jrbenny35 I updated to draft ✅

**Review by isabelrios — APPROVED** [review]
Changes look good to me in terms of the configuration and what could affect the current tests using this python framework. For the experiments part, not sure how to test it.

**Review by adudenamedruby — APPROVED** [review]
LGTM

**Comment by jrbenny35** [comment]
> Changes look good to me in terms of the configuration and what could affect the current tests using this python framework. For the experiments part, not sure how to test it.

If you pull the branch you would go into the ```experimentintegration``` folder and run

```
pipenv install
pipenv run pytest --experiment viewpoint-ios-aug-2023
```

It should start the test against that experiment.

**Comment by jrbenny35** [comment]
@adudenamedruby can you merge pls 🙏🏾

**Comment by lmarceau** [comment]
I'm not sure how this relates, but this test failed two times in a row:
Screenshot 2023-09-08 at 4 47 14 PM

**Comment by isabelrios** [comment]
@jrbenny35 I can not get it working, see the error I see locally [Logs.pdf](https://github.com/mozilla-mobile/firefox-ios/files/12574019/Logs.pdf)

The Unit Test failure is a different one, not sure why Unit tests are failing as I think they are not related..
```
testManagerGetMessage_experiments_exposureEvents()
ClientTests / GleanPlumbMessageManagerTests
```

**Comment by jrbenny35** [comment]
> @jrbenny35 I can not get it working, see the error I see locally [Logs.pdf](https://github.com/mozilla-mobile/firefox-ios/files/12574019/Logs.pdf)
> 
> The Unit Test failure is a different one, not sure why Unit tests are failing as I think they are not related..
> 
> ```
> testManagerGetMessage_experiments_exposureEvents()
> ClientTests / GleanPlumbMessageManagerTests
> ```

Just updated. Please do a ```pipenv install``` as the ```pytest-html``` plugin has a bug currently.

**Review by adudenamedruby — APPROVED** [review]

**Comment by isabelrios** [comment]
@jrbenny35 I see the simulator starting but the test still fails, not sure if that's expected as I may need some more set up? I will share the logs on slack

**Comment by clarmso** [comment]
:( A test is failing on my end as well.
```
test_integration.py::test_survey_navigates_correctly[branch]
```

**Comment by jrbenny35** [comment]
> 😞 A test is failing on my end as well.
> 
> ```
> test_integration.py::test_survey_navigates_correctly[branch]
> ```

Yeah, its expected the fail, but the test should run at least

**Comment by isabelrios** [comment]
@jrbenny35 I'm afraid you need to get latest main here so that that failing test is fixed... sorry about that! 🙏 once that is here and green I will merge the PR

**Comment by jrbenny35** [comment]
> @jrbenny35 I'm afraid you need to get latest main here so that that failing test is fixed... sorry about that! 🙏 once that is here and green I will merge the PR

Okay, just rebased on main

**Comment by lmarceau** [comment]
It's green so I'll merge!

**Pull request merged**
