### PR TITLE
Add FXIOS-9916 Upgrade sentry to version 8.36.0

### PR DESCRIPTION
**Pull request by OrlaM**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-9916)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/21742)

## :bulb: Description
Sentry are recommending testing out upgrading to 8.36.0. I'm not expecting this to fix the issue because they still have no idea why it's happening so will likely need to revert this before 133 goes live.

## :pencil: Checklist
You have to check all boxes before merging
- [ ] Filled in the above information (tickets numbers and description of your work)
- [ ] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by OrlaM** [comment]
@MergifyIO backport release/v133

cc @rvandermeulen fyi, testing to see if this works in 133 beta, we will likely need to back it out before hard freeze.

**Review by ih-codes — APPROVED** [review]
Fingers crossed! 🤞

**Comment by ih-codes** [comment]
FYI @OrlaM Looks like BitRise is failing:
```Dependencies could not be resolved because 'browserkit' depends on 'sentry-cocoa' 8.36.0 and root depends on 'sentry-cocoa' 8.21.0.```

**Comment by OrlaM** [comment]
I forgot to also update Focus. Should be working now.

**Pull request merged**
