### PR TITLE
Add FXIOS-9042 - Add optional badge to ToolbarElement/ToolbarButton

### PR DESCRIPTION
**Pull request by PARAIPAN9**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-9042)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/19977)

### Example
demo

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Review by thatswinnie — COMMENTED** [review]
The icon should have a background as otherwise the icon underneath shines through. 
Simulator Screenshot - iPhone 15 Pro Max - 2024-05-03 at 10 18 31

**Review by thatswinnie — COMMENTED** [review]
The icon `privateModeCircleFillMediumPurple` needs to be updated in Client as well.

**Review by thatswinnie — APPROVED** [review]

**Review by Karma197617 — COMMENTED** [review]
What is left for me to do

**Comment by thatswinnie** [comment]
> What is left for me to do

Nothing on this PR, @Karma197617. If you'd like to contribute you could look for issues [here](https://github.com/mozilla-mobile/firefox-ios/labels/Contributor%20OK) and please make sure to read through our [contributing wiki article](https://github.com/mozilla-mobile/firefox-ios/blob/main/CONTRIBUTING.md) 🙏

**Pull request merged**
