### PR TITLE
Bug 1159439 - Add long press to all Home Panels for invoking context menu actions.

### PR DESCRIPTION
**Pull request by farhanpatel**
Continuing from https://github.com/mozilla-mobile/firefox-ios/pull/2567

Git is hard sometimes 😢

### CODE REVIEW

**Comment by farhanpatel** [comment]
### SwiftLint found issues

#### Warnings

File | Line | Reason |
| --- | ----- | ----- |
BrowserViewController.swift | 941 | Force casts should be avoided. 
BrowserViewController.swift | 2022 | Force casts should be avoided. 
BrowserViewController.swift | 2026 | Force casts should be avoided. 
ActivityStreamPanel.swift | 235 | Force casts should be avoided. 
ActivityStreamPanel.swift | 265 | Force casts should be avoided. 
ActivityStreamPanel.swift | 337 | Force casts should be avoided. 
ActivityStreamPanel.swift | 346 | Force casts should be avoided. 
ActivityStreamPanel.swift | 352 | Force casts should be avoided. 
ActivityStreamPanel.swift | 504 | Force casts should be avoided. 
ActivityStreamPanel.swift | 573 | Force casts should be avoided. 
ReaderPanel.swift | 383 | Force casts should be avoided. 
RemoteTabsPanel.swift | 164 | Force casts should be avoided. 
RemoteTabsPanel.swift | 205 | Force casts should be avoided. 
TopSitesPanel.swift | 201 | Force casts should be avoided. 
TopSitesPanel.swift | 211 | Force casts should be avoided. 
TopSitesPanel.swift | 690 | Force casts should be avoided. 
TopSitesPanel.swift | 726 | Force casts should be avoided. 
ActionOverlayTableViewController.swift | 81 | Force casts should be avoided. 
ActionOverlayTableViewController.swift | 166 | Force casts should be avoided. 
ActionOverlayTableViewController.swift | 173 | Force casts should be avoided. 
ActionOverlayTableViewController.swift | 94 | Limit vertical whitespace to a single empty line. Currently 3. 
ActivityStreamTests.swift | 99 | Force casts should be avoided. 
ActivityStreamTests.swift | 112 | Force casts should be avoided. 
ActivityStreamTests.swift | 129 | Force casts should be avoided. 
ActivityStreamTests.swift | 142 | Force casts should be avoided. 
ActivityStreamTests.swift | 148 | Force casts should be avoided. 
ActivityStreamTests.swift | 178 | Force casts should be avoided. 
ActivityStreamTests.swift | 209 | Force casts should be avoided. 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by mauryat** [comment]
@farhanpatel thanks for taking care of the rebase! 😃

**Comment by mauryat** [comment]
@farhanpatel is it possible to add the individual commits?

**Comment by farhanpatel** [comment]
No we usually have a rebase merge approach for the project. So all commits are folded into one when merging.

**Pull request merged**
