### PR TITLE
Updating  FXIOS-7705 [v120] Update onboarding string versions and default behavior

### PR DESCRIPTION
**Pull request by jnrahme**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7705)

## :bulb: Description
Updated onboarding string versions in the YAML file to reflect the correct version.
Updated default behavior for the first onboarding card primary button to show the instructions popup

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Review by adudenamedruby — APPROVED** [review]
I approve this message.

**Comment by adudenamedruby** [comment]
Is this actually for 120?

**Review by yoanarios — APPROVED** [review]

**Comment by yoanarios** [comment]
small nit: PR name Updating is not a valid keyword check https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide#keyword for options

**Comment by jnrahme** [comment]
@Mergifyio backport release/v120

**Pull request merged**
