### PR TITLE
Bugfix FXIOS-6790 [v118] fix the `Use saved card` button background in both Dark and Light mode (#15127)

### PR DESCRIPTION
**Pull request by petruSt24**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-6790)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/15127)

## :bulb: Description

Updated the color for the background of the Use Saved Card button
## :pencil: Checklist
You have to check all boxes before merging
- [X] Filled in the above information (tickets numbers and description of your work)
- [X] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [X] Wrote unit tests and/or ensured the tests suite is passing
- [X] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [X If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by nbhasin2** [comment]
@petruSt24 this looks good although a small video or some sort of media for dark / light mode would be nice to show case your change :)

In short R+ for your change

**Review by nbhasin2 — APPROVED** [review]

**Comment by petruSt24** [comment]
appearance before change: 
CD2FB6E7-E52E-4D71-9E60-52E6C02BC3F2
02C45DD9-3176-4012-8D2D-E17187919C51

**Comment by petruSt24** [comment]
appearance after this change
DAB71D79-F70C-47C8-810D-9447E72D69AF
3B575971-B6AF-4D86-978C-8ED0E756ADD0

**Comment by lmarceau** [comment]
Do we need UX approval for this change @petruSt24 ? Who should be tagged?

**Comment by nbhasin2** [comment]
cc @jeffreygee for UX

**Comment by jeffreygee** [comment]
The original light version was correct before the changes.

The updated dark version looks good to go - thanks!

**Comment by petruSt24** [comment]
@lmarceau UX seems to want a color for light mode and a different color for dark mode, which goes against your [indications](https://github.com/mozilla-mobile/firefox-ios/pull/14200#discussion_r1184126860) about the theming system. Should this color be an exception to that or should UX change one of the colors to match the other?

**Comment by lmarceau** [comment]
@petruSt24 colors added and used in the application needs to be in the [mobile theme](https://www.figma.com/file/pEyGeE4KV5ytYHeXMfLcEr/Mobile-Styles?type=design&node-id=896-72781&mode=dev).

**Comment by lmarceau** [comment]
@petruSt24 for adding colors in the mobile theme, I think it needs to be discussed with @cwzilla

**Pull request merged**
