### PR TITLE
Bug 1400937 - Onboarding pagination dots not tappable Fixed

### PR DESCRIPTION
**Pull request by varun989**
used implementation of point(inside point: CGPoint, with event: UIEvent?) to enable pageControl's user interaction by placing pageControl above scrollView in the view heirarchy

### CODE REVIEW

**Comment by varun989** [comment]
@garvankeeley Hi there! How should we proceed with this PR?”

**Comment by garvankeeley** [comment]
This isn't working reliably for me. Sometimes the tap registers, other times it doesn't.

**Comment by varun989** [comment]
@garvankeeley I increased the tappable area for pagecontrol and also updated Bugzilla. Please suggest if I need to do anything else.

**Comment by varun989** [comment]
@garvankeeley @justindarc is there anything else that needs to be done here?

**Pull request closed without merging**
