### PR TITLE
 Bugfix FXIOS-9483 Bugzilla 1905749 

### PR DESCRIPTION
**Pull request by nbhasin2**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-9483)
https://bugzilla.mozilla.org/show_bug.cgi?id=1905749

## :pencil: Checklist
You have to check all boxes before merging
- [ ] Filled in the above information (tickets numbers and description of your work)
- [ ] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by mattreaganmozilla** [comment]
Initial changes LGTM, do we have clear repro steps for validating? I noticed your recent comment on the Bugzilla, looks like there still might be details we're trying to clarify with the reporter?

**Comment by mattreaganmozilla** [comment]
@nbhasin2 Quick follow-up: is there any update on this? LMK if you want to sync further or hand this ticket off etc.

**Comment by nbhasin2** [comment]
@mattreaganmozilla handing over to you, let me know if this fix is good enough for the time being

**Comment by mattreaganmozilla** [comment]
@nbhasin2 I reviewed the Bugzilla again and compared the behavior in this branch vs `main` and this looks Ok to me. Based on what I can see in the ticket I think we should be good to merge this and have QA validate and/or clarify any remaining questions with the reporter if needed.

**Review by mattreaganmozilla — APPROVED** [review]

**Comment by mattreaganmozilla** [comment]
@nbhasin2 Just double-checking: any concerns with me merging?

**Comment by nbhasin2** [comment]
> @nbhasin2 Just double-checking: any concerns with me merging?

No concern from my end

**Pull request merged**
