### PR TITLE
Add FXIOS move Shared library to SPM

### PR DESCRIPTION
**Pull request by FilippoZazzeroni**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-TODO)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/TODO)

## :bulb: Description
Move the whole Shared library to SPM, Also the Shared Test have been moved there into an SPM test target.
The only change to the code is in `AppInfo.applicationBundle` inside Shared lib, that was removed the fatalError if the bundle is not an app or an appex. I don't know if it is a good solution to remove it, but the reason of the removal is because it would crash the Shared tests since the bundle loaded is not an app or an appex. 
I look at the code that uses that property and only `SentryWrapper`, `WallpaperURLProvider` and `AppInfo` it self, so there shouldn't be side effects.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Comment by nbhasin2** [comment]
Something doesn't seem right, shared libs shouldn't be this big but lets talk tomorrow to find out.

I also wonder what will happen with the strings and will moving strings cause any issues.

**Comment by nbhasin2** [comment]
Screenshot 2024-11-04 at 3 34 35 PM
This change will be too much for us to review, there has too be a way to do this without these many modifications 🤔

**Comment by FilippoZazzeroni** [comment]
True @nbhasin2 i believe there should be less intrusive way. Probably the main problem are the Localizations.

**Comment by FilippoZazzeroni** [comment]
Closing this in order to split it in two separate PRs as discussed with @nbhasin2

**Pull request closed without merging**
