### PR TITLE
Refactor FXIOS-18459 [v124] Fix Redux unit tests

### PR DESCRIPTION
**Pull request by kmohan97**
## :scroll: Tickets
[Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-8330)
https://github.com/mozilla-mobile/firefox-ios/issues/18459

## :bulb: Description

Confirming to Action Protocol

SS: 

Screenshot 2024-01-30 at 8 22 25 AM

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by isabelrios** [comment]
@kmohan97 thank you for your PR! Looks like there are some swiflint issues that need to be fixed before we can run your PR on CI, could you please fix them? Thank you!

**Review by mattreaganmozilla — APPROVED** [review]
Changes look Ok to me, but might also be good to get eyes from @isabelrios or @clarmso

**Comment by clarmso** [comment]
Same. LGTM. I pushed a change on the lint error and started a pipeline on Bitrise.

🎉 There's no test failures from `ReduxTests` even after running them 100 times.
```
xcodebuild test -target Client -scheme Fennec -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' -only-testing:ReduxTests -test-iterations 100
```

**Review by clarmso — APPROVED** [review]

**Review by mattreaganmozilla — APPROVED** [review]

**Comment by kmohan97** [comment]
Going forward, will keep in mind to run the lint.

**Pull request merged**
