### PR TITLE
No Bug - General Repo Cleaning

### PR DESCRIPTION
**Pull request by sleroux**
It's been a long while since we've looked at the source directory and cleaned up some of the cruf. These series of patches removes some unused files, moves files to where they should be, and tidies up the Xcode references for easier navigation.

### CODE REVIEW

**Comment by sleroux** [comment]
@farhanpatel First in a series of PRs to clean up our codebase a bit. Getting tired of seeing random files laying around. There's more to be done but I'll put those into new PRs so I don't overload one. 

Let me know what your thoughts are on cleaning this up!

**Comment by farhanpatel** [comment]
### SwiftLint found issues

#### Warnings

File | Line | Reason |
| --- | ----- | ----- |
FxAContentViewController.swift | 192 | Colons should be next to the identifier when specifying a type. 
#### Errors

File | Line | Reason |
| --- | ----- | ----- |
FxAContentViewController.swift | 123 | Opening braces should be preceded by a single space and on the same line as the declaration. 
FxAContentViewController.swift | 93 | Lines should not have trailing semicolons. 
FxAContentViewController.swift | 127 | Lines should not have trailing semicolons. 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by farhanpatel** [comment]
I dont know when the changes to `FxAContentViewController` where made. But If you could fix those nits that would be awesome.

**Comment by farhanpatel** [comment]
Also that sqlite.playground in the sqlite project. It likes to complain sometimes during compile time. Can we remove that too?

**Comment by sleroux** [comment]
@farhanpatel Added the changes. Mind if I merge this into master now that we're starting the 7.0 cycle?

**Pull request merged**
