### PR TITLE
Refactor FXIOS-5599 [v112] Show default browser message after 72 hours from install

### PR DESCRIPTION
**Pull request by thatswinnie**
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-5599)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/12955)

### Description
This adds a trigger to only show the default browser card 3 days (72 hours) after app install.

### Pull requests checks where applicable
- [x] Fill in the three TODOs above (tickets number and description of your work)
- [x] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
~- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)~
~- [ ] Unit tests written and passing~
~- [ ] Documentation / comments for complex code and public methods~

### CODE REVIEW

**Review by yoanarios — APPROVED** [review]

**Comment by mte-test** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Edited 1 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 0 files</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against f04cb11a734956e1712e911e73c86693b74b75b9
</p>

**Comment by thatswinnie** [comment]
Build is green
Screenshot 2023-03-14 at 10 03 11

**Comment by nbhasin2** [comment]
You are too fast!! @thatswinnie 🔥

**Comment by yoanarios** [comment]
@Mergifyio backport release/v112

**Pull request merged**
