### PR TITLE
Bugfix MTE-2524 testPrivateClosedSiteDoesNotAppearOnRecentlyClosed fails

### PR DESCRIPTION
**Pull request by clarmso**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/MTE-2076)

## :bulb: Description
`HistoryTests.testPrivateClosedSiteDoesNotAppearOnRecentlyClosed` fails because closing a tab does not open the tab tray. Such an action opens the tab instead.

Before opening the new tab, we tell the tests that we have a browser tab opened.

## :pencil: Checklist
You have to check all boxes before merging
- [ ] Filled in the above information (tickets numbers and description of your work)
- [ ] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

### CODE REVIEW

**Review by dragosb01 — COMMENTED** [review]
@clarmso there is actually a bug logged for this one: https://github.com/mozilla-mobile/firefox-ios/issues/18728. So we either add this as a workaround or leave the test to fail until the issue is fixed

**Comment by isabelrios** [comment]
> @clarmso there is actually a bug logged for this one: #18728. So we either add this as a workaround or leave the test to fail until the issue is fixed

@dragosb01 do you know if that issue is being prioritized? if not and it may take too long to be fixed, let's try to have a workaround in the meantime. If devs are already working on this, we could wait. 
Thanks!

**Comment by dragosb01** [comment]
> > @clarmso there is actually a bug logged for this one: #18728. So we either add this as a workaround or leave the test to fail until the issue is fixed
> 
> @dragosb01 do you know if that issue is being prioritized? if not and it may take too long to be fixed, let's try to have a workaround in the meantime. If devs are already working on this, we could wait. Thanks!

@isabelrios don't know the priority on this one. We could add the workaround, but making sure the test passes on iPhone and iPad as well.

**Comment by isabelrios** [comment]
> > > @clarmso there is actually a bug logged for this one: #18728. So we either add this as a workaround or leave the test to fail until the issue is fixed
> > 
> > 
> > @dragosb01 do you know if that issue is being prioritized? if not and it may take too long to be fixed, let's try to have a workaround in the meantime. If devs are already working on this, we could wait. Thanks!
> 
> @isabelrios don't know the priority on this one. We could add the workaround, but making sure the test passes on iPhone and iPad as well.

Yes, that makes total sense, thanks

**Comment by clarmso** [comment]
Let me close this PR on a workaround for #18728. This issue should be addressed.

**Pull request closed without merging**
