### PR TITLE
Added FXIOS-7094 [v117] sponsored shortcut telemetry

### PR DESCRIPTION
**Pull request by OrlaM**
## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7094)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/15767)

## :bulb: Description
Added telemetry to track the users preference for sponsored shortcuts

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [x] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [x] If needed I updated documentation / comments for complex code and public methods

### CODE REVIEW

**Comment by OrlaM** [comment]
# Request for data collection review form

1) What questions will you answer with this data?
- We need to be able to identify clients with sponsored tiles disabled to count home screen views where sponsored tiles should have been displayed. 

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:
- This will be used to calculate sponsored tile fill rate, which is a metric included as a contractual obligation with our ads partners.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?
- There are no other methods

4) Can current instrumentation answer these questions?
- No

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>If the user has enabled sponsored shortcuts</td>
    <td>Category 2</td>
    <td>https://mozilla-hub.atlassian.net/browse/FXIOS-7094</td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
 * Often the Privacy Notice for your product will link to where the documentation is expected to be.
 * Common examples for Mozilla products/services:
    * If this collection is Telemetry you can state "This collection is documented in its definitions files Histograms.json, Scalars.yaml, and/or Events.yaml and in the Probe Dictionary at https://probes.telemetry.mozilla.org."
    * If this data is collected using the Glean SDK you can state “This collection is documented in the Glean Dictionary at https://dictionary.telemetry.mozilla.org/"
 * In some cases, documentation is included in the project’s repository.

7) How long will this data be collected?  Choose one of the following:
- Currently set to expire 2023-12-01

8) What populations will you measure?

* Which release channels?
- All

* Which countries?
- All

* Which locales?
- All

9) If this data collection is default on, what is the opt-out mechanism for users?
- The user can opt out

10) Please provide a general description of how you will analyze this data.
- Glean

11) Where do you intend to share the results of your analysis?
- Glean and ad partners

12) Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection? If so:
- No third party tools

**Comment by dnarcese** [comment]
I see the bugzilla also asks "What percent of eligible sponsored tiles slots are actually filled with tiles?".
How can we answer that here too - maybe we need to also send how many sponsored tiles are showing.

**Comment by OrlaM** [comment]
I think there is enough data to calculate that. They know how many ads are fed from the ad server, the data is there for how many active users there are and with this there will be the number of those users who have the sponsored shortcuts disabled. From that you can calculate how many unfilled ad spots there were.

**Comment by dnarcese** [comment]
@OrlaM can you please just confirm that with the original requester for this data? I want to make sure we are implementing what they expect.

**Comment by m-d-bowerman** [comment]
Hey @OrlaM and @dnarcese -- I can confirm, this is the last piece we need to calculate the percent of eligible sponsored tiles slots that are filled with a tile. We already have a count of tile impressions and a count of home screen views to calculate available tile slots, and this is the last piece missing -- the ability to filter out clients with sponsored tile disabled.

**Comment by dnarcese** [comment]
r+
# Data Review Form

_1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?_ 

Yes, telemetry is documented at https://dictionary.telemetry.mozilla.org/apps/firefox_ios

_2) Is there a control mechanism that allows the user to turn the data collection on and off?_ 

Yes, Firefox iOS provides data controls in the app settings

_3) If the request is for permanent data collection, is there someone who will monitor the data over time?_

This will be reviewed by me every 6 months

_4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?_

Type 2

_5) Is the data collection request for default-on or default-off?_

Default on

_6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?_

No

_7) Is the data collection covered by the existing Firefox privacy notice?_ 

Yes

_8) Does the data collection use a third-party collection tool?_ 

No

**Pull request merged**
